Contiki-NG: RPL-lite
RPL-lite
Network layer
RPL-lite is a lightweight implementation of RPL tailored for reliability.
Files
file rpl-dag-root.c
DAG root utility functions for RPL.
file rpl-dag-root.h
DAG root utility functions for RPL.
file rpl-dag.c
Logic for Directed Acyclic Graphs in RPL.
file rpl-ext-header.c
Management of extension headers for ContikiRPL.
file rpl-ext-header.h
Header file for rpl-ext-header.
file rpl-icmp6.c
ICMP6 I/O for RPL control messages.
file rpl-icmp6.h
Header file for rpl-ext-header.
file rpl-mrhof.c
The Minimum Rank with Hysteresis Objective Function (MRHOF), RFC6719.
file rpl-nbr-policy.c
Default RPL NBR policy decides when to add a new discovered node to the nbr table from RPL.
file rpl-neighbor.c
Logic for DAG neighbors in RPL.
file rpl-ns.c
RPL non-storing mode specific functions.
file rpl-ns.h
RPL non-storing mode specific functions.
file rpl-of0.c
An implementation of RPL's objective function 0, RFC6552.
file rpl-timers.c
RPL timer management.
file rpl.c
ContikiRPL, an implementation of RPL: IPv6 Routing Protocol for Low-Power and Lossy Networks (IETF RFC 6550)
Functions
void rpl_dag_root_init (uip_ipaddr_t *prefix, uip_ipaddr_t *iid)
Initialize dag-root module and sets a prefix in case the node is later set as dag root.
int rpl_dag_root_init_dag_immediately (void)
Initializes the node as DAG root immediatly.
void rpl_dag_root_init_dag_delay (void)
Initializes the node as DAG root after a delay.
int rpl_dag_root_is_root (void)
Tells whether we are DAG root or not.
const char * rpl_dag_state_to_str (enum rpl_dag_state state)
Returns a textual description of the current DAG state.
void rpl_dag_leave (void)
Leaves the current DAG.
void rpl_dag_poison_and_leave (void)
Start poisoning and leave the DAG after a delay.
void rpl_dag_periodic (unsigned seconds)
A function called periodically.
int rpl_is_addr_in_our_dag (const uip_ipaddr_t *addr)
Tells whether a given global IPv6 address is in our current DAG.
rpl_instance_t * rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
rpl_dag_t * rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
void rpl_global_repair (void)
Triggers a RPL global repair.
void rpl_local_repair (const char *str)
Triggers a RPL local repair.
int rpl_dag_ready_to_advertise (void)
Tells whether RPL is ready to advertise the DAG.
void rpl_dag_update_state (void)
Updates RPL internal state: selects preferred parent, updates rank & metreic container, triggers control traffic accordingly and updates uIP6 internal state.
void rpl_process_dio (uip_ipaddr_t *from, rpl_dio_t *dio)
Processes incoming DIO.
void rpl_process_dis (uip_ipaddr_t *from, int is_multicast)
Processes incoming DIS.
void rpl_process_dao (uip_ipaddr_t *from, rpl_dao_t *dao)
Processes incoming DAO.
int rpl_process_hbh (rpl_nbr_t *sender, uint16_t sender_rank, int loop_detected, int rank_error_signaled)
Processes Hop-by-Hop (HBH) Extension Header of a packet currently being forwrded.
void rpl_dag_init_root (uint8_t instance_id, uip_ipaddr_t *dag_id, uip_ipaddr_t *prefix, unsigned prefix_len, uint8_t prefix_flags)
Initializes DAG internal structure for a root node.
void rpl_dag_init (void)
Initializes rpl-dag module.
int rpl_ext_header_srh_get_next_hop (uip_ipaddr_t *ipaddr)
Look for next hop from SRH of current uIP packet.
int rpl_ext_header_srh_update (void)
Process and update SRH in-place, i.e.
int rpl_ext_header_hbh_update (int uip_ext_opt_offset)
Process and update the RPL extension headers of the current uIP packet.
int rpl_ext_header_update (void)
Adds/updates RPL extension headers to current uIP packet.
void rpl_ext_header_remove (void)
Removes all RPL extension headers.
uip_ds6_nbr_t * rpl_icmp6_update_nbr_table (uip_ipaddr_t *from, nbr_table_reason_t reason, void *data)
Updates IPv6 neighbor cache on incoming link-local RPL ICMPv6 messages.
void rpl_icmp6_dis_output (uip_ipaddr_t *addr)
Creates an ICMPv6 DIS packet and sends it.
void rpl_icmp6_dio_output (uip_ipaddr_t *uc_addr)
Creates an ICMPv6 DIO packet and sends it.
void rpl_icmp6_dao_output (uint8_t lifetime)
Creates an ICMPv6 DAO packet and sends it to the root, advertising the current preferred parent, and with our global address as prefix.
void rpl_icmp6_init (void)
Initializes rpl-icmp6 module, registers ICMPv6 handlers for all RPL ICMPv6 messages: DIO, DIS, DAO and DAO-ACK.
void rpl_icmp6_dao_ack_output (uip_ipaddr_t *dest, uint8_t sequence, uint8_t status)
Creates an ICMPv6 DAO-ACK packet and sends it to the originator of the ACK.
void rpl_neighbor_print_list (const char *str)
Prints a summary of all RPL neighbors and their properties.
int rpl_neighbor_count (void)
Returns the number of nodes in the RPL neighbor table.
rpl_nbr_t * rpl_neighbor_get_from_lladdr (uip_lladdr_t *addr)
Returns a neighbor from its link-layer address.
int rpl_neighbor_is_acceptable_parent (rpl_nbr_t *nbr)
Tells whether a nbr is acceptable as per the OF's definition.
uint16_t rpl_neighbor_get_link_metric (rpl_nbr_t *nbr)
Returns a neighbor's link metric.
rpl_rank_t rpl_neighbor_rank_via_nbr (rpl_nbr_t *nbr)
Returns our rank if selecting a given parent as preferred parent.
const linkaddr_t * rpl_neighbor_get_lladdr (rpl_nbr_t *nbr)
Returns a neighbors's link-layer address.
uip_ipaddr_t * rpl_neighbor_get_ipaddr (rpl_nbr_t *nbr)
Returns a neighbor's (link-local) IPv6 address.
const struct link_stats * rpl_neighbor_get_link_stats (rpl_nbr_t *nbr)
Returns a neighbor's link statistics.
int rpl_neighbor_is_fresh (rpl_nbr_t *nbr)
Tells wether we have fresh link information towards a given neighbor.
int rpl_neighbor_is_reachable (rpl_nbr_t *nbr)
Tells wether we a given neighbor is reachable.
int rpl_neighbor_is_parent (rpl_nbr_t *nbr)
Tells whether a neighbor is in the parent set.
void rpl_neighbor_set_preferred_parent (rpl_nbr_t *nbr)
Set current RPL preferred parent and update DS6 default route accordingly.
void rpl_neighbor_remove_all (void)
Empty the RPL neighbor table.
rpl_nbr_t * rpl_neighbor_get_from_ipaddr (uip_ipaddr_t *addr)
Returns a neighbor from its link-local IPv6 address.
rpl_nbr_t * rpl_neighbor_select_best (void)
Returns the best candidate for preferred parent.
void rpl_neighbor_init (void)
Initialize rpl-dag-neighbor module.
int rpl_ns_num_nodes (void)
Tells how many nodes are currently stored in the graph.
rpl_ns_node_t * rpl_ns_get_node (const uip_ipaddr_t *addr)
Looks up for a RPL NS node from its IPv6 global address.
int rpl_ns_is_addr_reachable (const uip_ipaddr_t *addr)
Telle whether an address is reachable, i.e.
void rpl_ns_expire_parent (const uip_ipaddr_t *child, const uip_ipaddr_t *parent)
Expires a given child-parent link.
rpl_ns_node_t * rpl_ns_update_node (const uip_ipaddr_t *child, const uip_ipaddr_t *parent, uint32_t lifetime)
Updates a child-parent link.
void rpl_ns_init (void)
Initialize rpl-ns module.
rpl_ns_node_t * rpl_ns_node_head (void)
Returns the head of the non-storing node list.
rpl_ns_node_t * rpl_ns_node_next (rpl_ns_node_t *item)
Returns the next element of the non-storing node list.
int rpl_ns_get_node_global_addr (uip_ipaddr_t *addr, rpl_ns_node_t *node)
Finds the global address of a given node.
void rpl_ns_periodic (unsigned seconds)
A function called periodically.
void rpl_ns_free_all (void)
Deallocate all neighbors.
void rpl_timers_schedule_periodic_dis (void)
Schedule periodic DIS with a random delay based on RPL_DIS_INTERVAL, until we join a DAG.
void rpl_timers_dio_reset (const char *str)
Reset DIO Trickle timer.
void rpl_timers_schedule_unicast_dio (rpl_nbr_t *target)
Schedule unicast DIO with no delay.
void rpl_timers_schedule_dao (void)
Schedule a DAO with random delay based on RPL_DAO_DELAY.
void rpl_timers_unschedule_leaving (void)
Cancel scheduled leaving if any.
void rpl_timers_schedule_leaving (void)
Schedule leaving after RPL_DELAY_BEFORE_LEAVING.
void rpl_timers_init (void)
Initialize rpl-timers module.
void rpl_timers_stop_dag_timers (void)
Stop all timers related to the DAG.
void rpl_timers_unschedule_state_update (void)
Cancelled any scheduled state update.
void rpl_timers_schedule_state_update (void)
Schedule a state update ASAP.
int rpl_lollipop_greater_than (int a, int b)
Greater-than function for a lollipop counter.
const uip_ipaddr_t * rpl_get_global_address (void)
Get one of the node's global addresses.
void rpl_link_callback (const linkaddr_t *addr, int status, int numtx)
Called by lower layers after every packet transmission.
int rpl_is_reachable (void)
Get the RPL's best guess on if we are reachable via have downward route or not.
void rpl_reset_prefix (rpl_prefix_t *last_prefix)
Removes current prefx.
int rpl_set_prefix_from_addr (uip_ipaddr_t *addr, unsigned len, uint8_t flags)
Set prefix from an IPv6 address.
int rpl_set_prefix (rpl_prefix_t *prefix)
Set prefix from an prefix data structure (from DIO)
void rpl_init (void)
Initialize RPL main module.
Detailed Description
RPL-lite is a lightweight implementation of RPL tailored for reliability.
Supports only non-storing mode, one instance and one DAG.
Function Documentation
void rpl_dag_init_root (uint8_t instance_id, uip_ipaddr_t * dag_id, uip_ipaddr_t * prefix, unsigned prefix_len, uint8_t flags)
Initializes DAG internal structure for a root node.
Parameters
instance_id The instance ID
dag_id The DAG ID
prefix The prefix
prefix_len The prefix length
flags The prefix flags (from DIO)
Definition at line 657 of file rpl-dag.c.
References rpl_dag_leave(), and rpl_timers_dio_reset().
Referenced by rpl_dag_root_init_dag_immediately().
void rpl_dag_leave (void)
Leaves the current DAG.
Definition at line 82 of file rpl-dag.c.
References rpl_dag_root_is_root(), rpl_icmp6_dao_output(), rpl_neighbor_remove_all(), rpl_ns_free_all(), rpl_reset_prefix(), and rpl_timers_stop_dag_timers().
Referenced by rpl_dag_init_root().
void rpl_dag_periodic (unsigned seconds)
A function called periodically.
Used to age the DAG (decrease lifetime and expire DAG accordingly)
Parameters
seconds The number of seconds elapsted since last call
Definition at line 121 of file rpl-dag.c.
References rpl_icmp6_dis_output(), rpl_neighbor_get_ipaddr(), and rpl_timers_schedule_state_update().
void rpl_dag_poison_and_leave (void)
Start poisoning and leave the DAG after a delay.
Definition at line 114 of file rpl-dag.c.
References rpl_timers_schedule_state_update().
int rpl_dag_ready_to_advertise (void)
Tells whether RPL is ready to advertise the DAG.
Returns
1 is ready, 0 otherwise
Definition at line 220 of file rpl-dag.c.
Referenced by rpl_timers_dio_reset().
void rpl_dag_root_init (uip_ipaddr_t * prefix, uip_ipaddr_t * iid)
Initialize dag-root module and sets a prefix in case the node is later set as dag root.
Parameters
prefix The prefix. If NULL, UIP_DS6_DEFAULT_PREFIX is used instead
iid The IID. If NULL, it will be built from uip_ds6_set_addr_iid.
Definition at line 128 of file rpl-dag-root.c.
Referenced by rpl_dag_root_init_dag_delay(), and rpl_dag_root_init_dag_immediately().
void rpl_dag_root_init_dag_delay (void)
Initializes the node as DAG root after a delay.
Until the delay, the node gets a chance to hear another DAG and join it instead.
Definition at line 174 of file rpl-dag-root.c.
References ctimer_set(), rpl_dag_root_init(), and rpl_icmp6_dis_output().
int rpl_dag_root_init_dag_immediately (void)
Initializes the node as DAG root immediatly.
Returns
0 in case of success, -1 otherwise
Definition at line 140 of file rpl-dag-root.c.
References rpl_dag_init_root(), rpl_dag_root_init(), rpl_dag_update_state(), rpl_get_any_dag(), rpl_get_global_address(), uip_ds6_if, uip_ip6addr, and uip_is_addr_linklocal.
int rpl_dag_root_is_root (void)
Tells whether we are DAG root or not.
Returns
1 if we are dag root, 0 otherwise
Definition at line 186 of file rpl-dag-root.c.
References rpl_get_default_instance().
Referenced by rpl_dag_leave(), rpl_dag_update_state(), rpl_ext_header_update(), rpl_global_repair(), rpl_local_repair(), rpl_neighbor_select_best(), and rpl_process_dio().
const char* rpl_dag_state_to_str (enum rpl_dag_state state)
Returns a textual description of the current DAG state.
Parameters
state The DAG state
Returns
The description string
Definition at line 65 of file rpl-dag.c.
Referenced by rpl_neighbor_print_list().
int rpl_ext_header_hbh_update (int uip_ext_opt_offset)
Process and update the RPL extension headers of the current uIP packet.
Parameters
uip_ext_opt_offset The offset within the uIP packet where extension headers start
Returns
1 in case the packet is valid and to be processed further, 0 in case the packet must be dropped.
Definition at line 358 of file rpl-ext-header.c.
References rpl_process_hbh(), UIP_HTONS, and UIP_IP_BUF.
int rpl_ext_header_srh_get_next_hop (uip_ipaddr_t * ipaddr)
Look for next hop from SRH of current uIP packet.
Parameters
ipaddr A pointer to the address where to store the next hop.
Returns
1 if a next hop was found, 0 otherwise
Definition at line 67 of file rpl-ext-header.c.
References rpl_is_addr_in_our_dag(), rpl_ns_get_node(), uip_ext_len, UIP_IP_BUF, uip_ipaddr_copy, uip_next_hdr, and UIP_PROTO_HBHO.
int rpl_ext_header_srh_update (void)
Process and update SRH in-place, i.e.
internal address swapping as per RFC6554
Returns
1 if SRH found, 0 otherwise
Definition at line 122 of file rpl-ext-header.c.
References uip_ext_len, UIP_IP_BUF, uip_ipaddr_copy, uip_next_hdr, and UIP_PROTO_HBHO.
Referenced by uip_process().
int rpl_ext_header_update (void)
Adds/updates RPL extension headers to current uIP packet.
Returns
1 in case of success, 0 otherwise
Definition at line 500 of file rpl-ext-header.c.
References rpl_dag_root_is_root(), rpl_ext_header_remove(), rpl_is_addr_in_our_dag(), uip_ds6_if, UIP_IP_BUF, uip_is_addr_linklocal, and uip_is_addr_mcast.
rpl_dag_t* rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
Returns
A pointer to the only supported DAG
Definition at line 154 of file rpl-dag.c.
rpl_instance_t* rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
Returns
A pointer to the only supported instance
Definition at line 148 of file rpl-dag.c.
const uip_ipaddr_t* rpl_get_global_address (void)
Get one of the node's global addresses.
Returns
A (constant) pointer to the global IPv6 address found. The pointer directs to the internals of DS6, should only be used in the current function's local scope
Definition at line 69 of file rpl.c.
References ipaddr, uip_ds6_if, and uip_is_addr_linklocal.
Referenced by rpl_dag_root_init_dag_immediately(), rpl_icmp6_dao_output(), and rpl_neighbor_print_list().
void rpl_icmp6_dao_ack_output (uip_ipaddr_t * dest, uint8_t sequence, uint8_t status)
Creates an ICMPv6 DAO-ACK packet and sends it to the originator of the ACK.
Parameters
dest The DAO-ACK destination (was source of the DAO)
sequence The sequence number of the DAO being ACKed
status The status of the DAO-ACK (see RPL_DAO_ACK_* defines)
void rpl_icmp6_dao_output (uint8_t lifetime)
Creates an ICMPv6 DAO packet and sends it to the root, advertising the current preferred parent, and with our global address as prefix.
Parameters
lifetime The DAO lifetime. Use 0 to send a No-path DAO
Definition at line 547 of file rpl-icmp6.c.
References ICMP6_RPL, rpl_dag_update_state(), rpl_get_global_address(), rpl_neighbor_get_ipaddr(), and uip_icmp6_send().
Referenced by rpl_dag_leave().
void rpl_icmp6_dio_output (uip_ipaddr_t * uc_addr)
Creates an ICMPv6 DIO packet and sends it.
Can be unicast or multicast
Parameters
uc_addr The link-local address of the target host, if any. Else, a multicast DIO will be sent.
Definition at line 336 of file rpl-icmp6.c.
References addr, ICMP6_RPL, rpl_dag_update_state(), and uip_icmp6_send().
Referenced by rpl_process_dis().
void rpl_icmp6_dis_output (uip_ipaddr_t * addr)
Creates an ICMPv6 DIS packet and sends it.
Can be unicast or multicast.
Parameters
addr The link-local address of the target host, if any. Else, a multicast DIS will be sent.
Definition at line 154 of file rpl-icmp6.c.
References ICMP6_RPL, rpl_dag_update_state(), and uip_icmp6_send().
Referenced by rpl_dag_periodic(), and rpl_dag_root_init_dag_delay().
uip_ds6_nbr_t* rpl_icmp6_update_nbr_table (uip_ipaddr_t * from, nbr_table_reason_t reason, void * data)
Updates IPv6 neighbor cache on incoming link-local RPL ICMPv6 messages.
Parameters
from The source link-local IPv6 address
reason What triggered the update (maps to RPL packet types)
data Generic pointer, used for instance to store parsed DIO data
Returns
A pointer to the new neighbor cache entry, NULL if there was no space left.
Definition at line 116 of file rpl-icmp6.c.
References nbr, and uip_ds6_nbr_add().
int rpl_is_addr_in_our_dag (const uip_ipaddr_t * addr)
Tells whether a given global IPv6 address is in our current DAG.
Parameters
addr The global IPv6 address to be tested
Returns
1 if addr is in our current DAG, 0 otherwise
Definition at line 141 of file rpl-dag.c.
Referenced by rpl_ext_header_srh_get_next_hop(), and rpl_ext_header_update().
int rpl_is_reachable (void)
Get the RPL's best guess on if we are reachable via have downward route or not.
Returns
1 if we are reachable, 0 otherwise.
Definition at line 103 of file rpl.c.
void rpl_link_callback (const linkaddr_t * addr, int status, int numtx)
Called by lower layers after every packet transmission.
Parameters
addr The link-layer addrress of the packet destination
status The transmission status (see os/net/mac/mac.h)
numtx The total number of transmission attempts
Definition at line 87 of file rpl.c.
References ipaddr, nbr, rpl_neighbor_get_from_lladdr(), rpl_neighbor_get_link_metric(), rpl_timers_schedule_state_update(), uip_ds6_set_addr_iid(), and uip_ip6addr.
void rpl_local_repair (const char * str)
Triggers a RPL local repair.
Parameters
str A textual description of the cause for triggering a repair
Definition at line 204 of file rpl-dag.c.
References rpl_dag_root_is_root(), rpl_neighbor_remove_all(), rpl_timers_dio_reset(), and rpl_timers_schedule_state_update().
Referenced by rpl_global_repair().
int rpl_lollipop_greater_than (int a, int b)
Greater-than function for a lollipop counter.
Parameters
a The first counter
b The second counter
Returns
1 is a>b else 0
Definition at line 55 of file rpl.c.
int rpl_neighbor_count (void)
Returns the number of nodes in the RPL neighbor table.
Returns
the neighbor count
Definition at line 126 of file rpl-neighbor.c.
References nbr.
Referenced by rpl_neighbor_print_list().
rpl_nbr_t* rpl_neighbor_get_from_ipaddr (uip_ipaddr_t * addr)
Returns a neighbor from its link-local IPv6 address.
Parameters
addr The link-local IPv6 address
Returns
The neighbor if found, NULL otherwise
Definition at line 298 of file rpl-neighbor.c.
rpl_nbr_t* rpl_neighbor_get_from_lladdr (uip_lladdr_t * addr)
Returns a neighbor from its link-layer address.
Parameters
addr The link-layer address
Returns
The neighbor if found, NULL otherwise
Definition at line 168 of file rpl-neighbor.c.
Referenced by rpl_link_callback().
uip_ipaddr_t* rpl_neighbor_get_ipaddr (rpl_nbr_t * nbr)
Returns a neighbor's (link-local) IPv6 address.
Parameters
nbr The neighbor
Returns
The link-local IPv6 address if any, NULL otherwise
Definition at line 207 of file rpl-neighbor.c.
References rpl_neighbor_get_lladdr().
Referenced by rpl_dag_periodic(), rpl_dag_update_state(), rpl_icmp6_dao_output(), rpl_neighbor_print_list(), rpl_neighbor_select_best(), and rpl_neighbor_set_preferred_parent().
uint16_t rpl_neighbor_get_link_metric (rpl_nbr_t * nbr)
Returns a neighbor's link metric.
Parameters
nbr The neighbor
Returns
The link metric if any, 0xffff otherwise
Definition at line 183 of file rpl-neighbor.c.
Referenced by rpl_link_callback(), and rpl_neighbor_print_list().
const struct link_stats* rpl_neighbor_get_link_stats (rpl_nbr_t * nbr)
Returns a neighbor's link statistics.
Parameters
nbr The neighbor
Returns
The link_stats structure address if any, NULL otherwise
Definition at line 214 of file rpl-neighbor.c.
References rpl_neighbor_get_lladdr().
Referenced by rpl_neighbor_is_fresh(), and rpl_neighbor_print_list().
const linkaddr_t* rpl_neighbor_get_lladdr (rpl_nbr_t * nbr)
Returns a neighbors's link-layer address.
Parameters
nbr The neighbor
Returns
The link-layer address if any, NULL otherwise
Definition at line 201 of file rpl-neighbor.c.
Referenced by rpl_neighbor_get_ipaddr(), and rpl_neighbor_get_link_stats().
int rpl_neighbor_is_acceptable_parent (rpl_nbr_t * nbr)
Tells whether a nbr is acceptable as per the OF's definition.
Parameters
nbr The neighbor
Returns
1 if acceptable, 0 otherwise
Definition at line 174 of file rpl-neighbor.c.
Referenced by rpl_neighbor_print_list().
int rpl_neighbor_is_fresh (rpl_nbr_t * nbr)
Tells wether we have fresh link information towards a given neighbor.
Parameters
nbr The neighbor
Returns
1 if we have fresh link information, 0 otherwise
Definition at line 221 of file rpl-neighbor.c.
References rpl_neighbor_get_link_stats().
Referenced by rpl_neighbor_is_reachable(), and rpl_neighbor_select_best().
int rpl_neighbor_is_parent (rpl_nbr_t * nbr)
Tells whether a neighbor is in the parent set.
Parameters
nbr The neighbor to be tested
Returns
1 if nbr is in the parent set, 0 otherwise
Definition at line 245 of file rpl-neighbor.c.
int rpl_neighbor_is_reachable (rpl_nbr_t * nbr)
Tells wether we a given neighbor is reachable.
Parameters
nbr The neighbor
Returns
1 if the parent is reachable, 0 otherwise
Definition at line 228 of file rpl-neighbor.c.
References rpl_neighbor_is_fresh().
void rpl_neighbor_print_list (const char * str)
Prints a summary of all RPL neighbors and their properties.
Parameters
str A descriptive text on the caller
Definition at line 78 of file rpl-neighbor.c.
References CLOCK_SECOND, clock_time(), nbr, rpl_dag_state_to_str(), rpl_get_global_address(), rpl_neighbor_count(), rpl_neighbor_get_ipaddr(), rpl_neighbor_get_link_metric(), rpl_neighbor_get_link_stats(), rpl_neighbor_is_acceptable_parent(), and rpl_neighbor_rank_via_nbr().
Referenced by rpl_dag_update_state(), and rpl_global_repair().
rpl_rank_t rpl_neighbor_rank_via_nbr (rpl_nbr_t * nbr)
Returns our rank if selecting a given parent as preferred parent.
Parameters
nbr The neighbor
Returns
The resulting rank if any, RPL_INFINITE_RANK otherwise
Definition at line 192 of file rpl-neighbor.c.
Referenced by rpl_dag_update_state(), and rpl_neighbor_print_list().
rpl_nbr_t* rpl_neighbor_select_best (void)
Returns the best candidate for preferred parent.
Returns
The best candidate, NULL if no usable parent is found
Definition at line 346 of file rpl-neighbor.c.
References rpl_dag_root_is_root(), rpl_neighbor_get_ipaddr(), and rpl_neighbor_is_fresh().
Referenced by rpl_dag_update_state().
void rpl_neighbor_set_preferred_parent (rpl_nbr_t * nbr)
Set current RPL preferred parent and update DS6 default route accordingly.
Parameters
nbr The new preferred parent
Definition at line 251 of file rpl-neighbor.c.
References nbr, and rpl_neighbor_get_ipaddr().
Referenced by rpl_dag_update_state().
void rpl_ns_expire_parent (const uip_ipaddr_t * child, const uip_ipaddr_t * parent)
Expires a given child-parent link.
Parameters
child The IPv6 address of the child
parent The IPv6 address of the parent
Definition at line 102 of file rpl-ns.c.
References rpl_ns_get_node().
Referenced by rpl_process_dao().
rpl_ns_node_t * rpl_ns_get_node (const uip_ipaddr_t * addr)
Looks up for a RPL NS node from its IPv6 global address.
Parameters
addr The target address
Returns
A pointer to the node
Definition at line 76 of file rpl-ns.c.
References list_head(), and list_item_next().
Referenced by rpl_ext_header_srh_get_next_hop(), rpl_ns_expire_parent(), rpl_ns_is_addr_reachable(), and rpl_ns_update_node().
int rpl_ns_get_node_global_addr (uip_ipaddr_t * addr, rpl_ns_node_t * node)
Finds the global address of a given node.
Parameters
addr A pointer to the address to be written
node The target node
Returns
1 if success, 0 otherwise
Definition at line 194 of file rpl-ns.c.
Referenced by rpl_ns_periodic().
int rpl_ns_is_addr_reachable (const uip_ipaddr_t * addr)
Telle whether an address is reachable, i.e.
if there exists a path from the root to the node in the current RPL NS graph
Parameters
addr The target IPv6 global address
Returns
1 if the node is reachable, 0 otherwise
Definition at line 89 of file rpl-ns.c.
References rpl_ns_get_node().
Referenced by rpl_ns_update_node().
rpl_ns_node_t* rpl_ns_node_head (void)
Returns the head of the non-storing node list.
Returns
The head of the list
Definition at line 182 of file rpl-ns.c.
References list_head().
rpl_ns_node_t* rpl_ns_node_next (rpl_ns_node_t * item)
Returns the next element of the non-storing node list.
Parameters
item The current element in the list
Returns
The next element of the list
Definition at line 188 of file rpl-ns.c.
References list_item_next().
int rpl_ns_num_nodes (void)
Tells how many nodes are currently stored in the graph.
Returns
The number of nodes
Definition at line 61 of file rpl-ns.c.
void rpl_ns_periodic (unsigned seconds)
A function called periodically.
Used to age the links (decrease lifetime and expire links accordingly)
Parameters
seconds The number of seconds elapsted since last call
Definition at line 206 of file rpl-ns.c.
References list_head(), list_item_next(), list_remove(), memb_free(), and rpl_ns_get_node_global_addr().
rpl_ns_node_t * rpl_ns_update_node (const uip_ipaddr_t * child, const uip_ipaddr_t * parent, uint32_t lifetime)
Updates a child-parent link.
Parameters
child The IPv6 address of the child
parent The IPv6 address of the parent
lifetime The link lifetime in seconds
Definition at line 112 of file rpl-ns.c.
References list_add(), memb_alloc(), rpl_ns_get_node(), and rpl_ns_is_addr_reachable().
Referenced by rpl_process_dao().
void rpl_process_dao (uip_ipaddr_t * from, rpl_dao_t * dao)
Processes incoming DAO.
Parameters
from The IPv6 address of the originator
dao A pointer to a parsed DAO
Definition at line 579 of file rpl-dag.c.
References rpl_ns_expire_parent(), and rpl_ns_update_node().
void rpl_process_dio (uip_ipaddr_t * from, rpl_dio_t * dio)
Processes incoming DIO.
Parameters
from The IPv6 address of the originator
dio A pointer to a parsed DIO
Definition at line 546 of file rpl-dag.c.
References rpl_dag_root_is_root(), and rpl_dag_update_state().
void rpl_process_dis (uip_ipaddr_t * from, int is_multicast)
Processes incoming DIS.
Parameters
from The IPv6 address of the originator
is_multicast Set to 1 for multicast DIS, 0 for unicast DIS
Definition at line 565 of file rpl-dag.c.
References rpl_icmp6_dio_output(), rpl_icmp6_update_nbr_table(), and rpl_timers_dio_reset().
int rpl_process_hbh (rpl_nbr_t * sender, uint16_t sender_rank, int loop_detected, int rank_error_signaled)
Processes Hop-by-Hop (HBH) Extension Header of a packet currently being forwrded.
Parameters
sender The IPv6 address of the originator
sender_rank The rank advertised by the sender in the HBH header
loop_detected 1 if we could detect a loop while forwarding, 0 otherwise
rank_error_signaled 1 if the HBH header advertises a rank error, 0 otherwise
Returns
1 if the packet is to be forwarded, 0 if it is to be dropped
Definition at line 624 of file rpl-dag.c.
References rpl_dag_update_state(), rpl_timers_dio_reset(), and rpl_timers_schedule_unicast_dio().
Referenced by rpl_ext_header_hbh_update().
void rpl_reset_prefix (rpl_prefix_t * last_prefix)
Removes current prefx.
Parameters
last_prefix The last prefix (which is to be removed)
Definition at line 117 of file rpl.c.
References ipaddr.
Referenced by rpl_dag_leave().
int rpl_set_prefix (rpl_prefix_t * prefix)
Set prefix from an prefix data structure (from DIO)
Parameters
prefix The prefix
Returns
1 if success, 0 otherwise
Definition at line 161 of file rpl.c.
References rpl_set_prefix_from_addr().
int rpl_set_prefix_from_addr (uip_ipaddr_t * addr, unsigned len, uint8_t flags)
Set prefix from an IPv6 address.
Parameters
addr The prefix
len The prefix length
flags The DIO prefix flags
Returns
1 if success, 0 otherwise
Definition at line 133 of file rpl.c.
References ipaddr, and uip_ds6_addr_add().
Referenced by rpl_set_prefix().
void rpl_timers_dio_reset (const char * str)
Reset DIO Trickle timer.
Parameters
str A textual description of caused the DIO timer reset
Definition at line 148 of file rpl-timers.c.
References rpl_dag_ready_to_advertise().
Referenced by rpl_dag_init_root(), rpl_dag_update_state(), rpl_local_repair(), rpl_process_dis(), and rpl_process_hbh().
void rpl_timers_schedule_state_update (void)
Schedule a state update ASAP.
Useful to force an update from a context where updating directly would be unsafe.
Definition at line 549 of file rpl-timers.c.
References ctimer_set().
Referenced by rpl_dag_periodic(), rpl_dag_poison_and_leave(), rpl_link_callback(), and rpl_local_repair().