Contiki-NG: Nullnet
Nullnet
Network layer
A network layer that does nothing.
Typedefs
typedef void(* nullnet_input_callback)(const void *data, uint16_t len, const linkaddr_t *src, const linkaddr_t *dest)
Function prototype for NullNet input callback.
Functions
void nullnet_set_input_callback (nullnet_input_callback callback)
Set input callback for NullNet.
void nullnet_output (const void *data, uint16_t len, const linkaddr_t *dest)
Send data with NullNet.
Detailed Description
A network layer that does nothing.
Useful for lower-layer testing and for non-IPv6 scenarios.
Function Documentation
void nullnet_output (const void * data, uint16_t len, const linkaddr_t * dest)
Send data with NullNet.
Parameters
data The payload
len The payload len
dest The destination link-layer address
Definition at line 84 of file nullnet.c.
References linkaddr_node_addr, linkaddr_null, packetbuf_clear(), packetbuf_copyfrom(), packetbuf_datalen(), and mac_driver::send.
void nullnet_set_input_callback (nullnet_input_callback callback)
Set input callback for NullNet.
Parameters
callback The input callback
Definition at line 78 of file nullnet.c.