ContikiNG: ARM Cortex-M support for Contiki multi-threading
ARM Cortex-M support for Contiki multi-threading
ContikiNG CPUs » ARM
All the Cortex-M devices supported by CMSIS-CORE are supported.
Files
file mtarch.c
Implmentation of the ARM Cortex-M support for Contiki multi-threading.
file mtarch.h
Header file for the ARM Cortex-M support for Contiki multi-threading.
Data Structures
struct mtarch_thread_context
Structure of a saved thread context.
Macros
#define MTARCH_CONF_STACKSIZE 256
Thread stack size configuration, expressed as a number of 32-bit words.
#define MTARCH_STACKSIZE
Actual stack size, with minimum size and alignment requirements enforced.
Functions
void svcall_handler (void)
SVCall system handler.
void pendsv_handler (void)
PendSV system handler.
void mtarch_init (void)
Initialize the architecture specific support functions for the multi-thread library.
void mtarch_start (struct mtarch_thread *thread, void(*function)(void *data), void *data)
Setup the stack frame for a thread that is being started.
void mtarch_exec (struct mtarch_thread *thread)
Start executing a thread.
void mtarch_yield (void)
Yield the processor.
void mtarch_stop (struct mtarch_thread *thread)
Clean up the stack of a thread.
void mtarch_remove (void)
Uninstall library and clean up.
Detailed Description
All the Cortex-M devices supported by CMSIS-CORE are supported.
An exception handler can decide to make the main Contiki thread preempt any running mt thread by calling mtarch_pstart() (e.g. to perform urgent operations that have been triggered by some event or that had been scheduled). If the running thread is already the main Contiki thread, then nothing happens. The corresponding task switch takes place when leaving Handler mode. The main Contiki thread then resumes after the call to mt_exec() that yielded to the preempted mt thread.
Macro Definition Documentation
MTARCH_CONF_STACKSIZE
#define MTARCH_CONF_STACKSIZE 256
Thread stack size configuration, expressed as a number of 32-bit words.
Definition at line 61 of file mtarch.h.
MTARCH_STACKSIZE
#define MTARCH_STACKSIZE
Value:
((MAX(MTARCH_CONF_STACKSIZE, \
                                      sizeof(struct mtarch_thread_context) / \
                                      sizeof(uint32_t)) + 1) & ~1)
Actual stack size, with minimum size and alignment requirements enforced.
Definition at line 64 of file mtarch.h.
Function Documentation
mtarch_exec()
void mtarch_exec (struct mtarch_thread * thread)
Start executing a thread.
This function is called from mt_exec() and the purpose of the function is to start execution of the thread. The function should switch in the stack of the thread, and does not return until the thread has explicitly yielded (using mt_yield()) or until it is preempted.
Parameters
thread A pointer to a struct mtarch_thread for the thread to be executed.
Definition at line 243 of file mtarch.c.
mtarch_init()
void mtarch_init (void)
Initialize the architecture specific support functions for the multi-thread library.
This function is implemented by the architecture specific functions for the multi-thread library and is called by the mt_init() function as part of the initialization of the library. The mtarch_init() function can be used for, e.g., starting preemption timers or other architecture specific mechanisms required for the operation of the library.
Definition at line 181 of file mtarch.c.
Referenced by mt_init().
mtarch_start()
void mtarch_start (struct mtarch_thread * thread, void(*)(void *data) function, void * data)
Setup the stack frame for a thread that is being started.
This function is called by the mt_start() function in order to set up the architecture specific stack of the thread to be started.
Parameters
thread A pointer to a struct mtarch_thread for the thread to be started.
function A pointer to the function that the thread will start executing the first time it is scheduled to run.
data A pointer to the argument that the function should be passed.
Definition at line 224 of file mtarch.c.
Referenced by mtarch_init().
mtarch_stop()
void mtarch_stop (struct mtarch_thread * thread)
Clean up the stack of a thread.
This function is called by the mt_stop() function in order to clean up the architecture specific stack of the thread to be stopped.
Note
If the stack is wholly contained in struct mtarch_thread this function may very well be empty.
Parameters
thread A pointer to a struct mtarch_thread for the thread to be stopped.
Definition at line 263 of file mtarch.c.
Referenced by mt_stop().
mtarch_yield()
void mtarch_yield (void)
Yield the processor.
This function is called by the mt_yield() function, which is called from the running thread in order to give up the processor.
Definition at line 255 of file mtarch.c.
pendsv_handler()
void pendsv_handler (void)
PendSV system handler.
This exception handler executes following a call to mtarch_pstart() from another exception handler. It performs a task switch to the main Contiki thread if it is not already running.
Definition at line 125 of file mtarch.c.
svcall_handler()
void svcall_handler (void)
SVCall system handler.
This exception handler executes the action requested by the corresponding svc instruction, which is a task switch from the main Contiki thread to an mt thread or the other way around.
Definition at line 69 of file mtarch.c.