ContikiNG: SensorTag 2.0 Button Sensor
SensorTag 2.0 Button Sensor
ContikiNG platforms » TI CC26xx-powered Platforms » SmartRF+CC13xx/CC26xx EM, SensorTags and LaunchPads » Sensortag CC1350/CC2650 common
One of the buttons can be configured as general purpose or as an on/off key.
Files
file button-sensor.c
Driver for Sensortag buttons.
file button-sensor.h
Header file for the Sensortag Button Driver.
Functions
static void button_press_handler (uint8_t ioid)
Handler for Sensortag-CC26XX button presses.
static void config_buttons (int type, int c, uint32_t key)
Configuration function for the button sensor for all buttons.
static int config_left (int type, int value)
Configuration function for the left button.
static int config_right (int type, int value)
Configuration function for the right button.
static int status (int type, uint32_t key_io_id)
Status function for all buttons.
static int status_left (int type)
Status function for the left button.
static int status_right (int type)
Status function for the right button.
Variables
const struct sensors_sensor button_left_sensor
Exports a global symbol to be used by the sensor API.
Detailed Description
One of the buttons can be configured as general purpose or as an on/off key.
Function Documentation
config_buttons()
static void config_buttons (int type, int c, uint32_t key) static
Configuration function for the button sensor for all buttons.
Parameters
type This function does nothing unless type == SENSORS_ACTIVE
c 0: disable the button, non-zero: enable
key One of BOARD_KEY_LEFT, BOARD_KEY_RIGHT etc
Definition at line 131 of file button-sensor.c.
Referenced by config_left(), and config_right().
config_left()
static int config_left (int type, int value) static
Configuration function for the left button.
Parameters are passed onto config_buttons, which does the actual configuration Parameters are ignored. They have been included because the prototype is dictated by the core sensor API. The return value is also required by the API but otherwise ignored.
Parameters
type passed to config_buttons as-is
value passed to config_buttons as-is
Returns
ignored
Definition at line 170 of file button-sensor.c.
References config_buttons().
config_right()
static int config_right (int type, int value) static
Configuration function for the right button.
Parameters are passed onto config_buttons, which does the actual configuration Parameters are ignored. They have been included because the prototype is dictated by the core sensor api. The return value is also required by the API but otherwise ignored.
Parameters
type passed to config_buttons as-is
value passed to config_buttons as-is
Returns
ignored
Definition at line 192 of file button-sensor.c.
References config_buttons().
status()
static int status (int type, uint32_t key_io_id) static
Status function for all buttons.
Parameters
type SENSORS_ACTIVE or SENSORS_READY
key_io_id BOARD_IOID_KEY_LEFT, BOARD_IOID_KEY_RIGHT etc
Returns
1 if the button's port interrupt is enabled (edge detect)
This function will only be called by status_left, status_right and the called will pass the correct key_io_id
Definition at line 209 of file button-sensor.c.
Referenced by status_left(), and status_right().
status_left()
static int status_left (int type) static
Status function for the left button.
Parameters
type SENSORS_ACTIVE or SENSORS_READY
Returns
1 if the button's port interrupt is enabled (edge detect)
This function will call status. It will pass type verbatim and it will also pass the correct key_io_id
Definition at line 257 of file button-sensor.c.
References status().
status_right()
static int status_right (int type) static
Status function for the right button.
Parameters
type SENSORS_ACTIVE or SENSORS_READY
Returns
1 if the button's port interrupt is enabled (edge detect)
This function will call status. It will pass type verbatim and it will also pass the correct key_io_id
Definition at line 271 of file button-sensor.c.
References status().