ContikiNG: Zolertia Zoul core module
Zolertia Zoul core module
ContikiNG platforms
The Zoul comprises the CC2538SF53 and CC1200 in a single module format, which allows a fast reuse of its core components in different formats and form-factors.
Modules
Zolertia platforms based on the Zoul core module
The Zoul allows a fast reuse and easy integration to most applications and products.
Zoul CC1200 arch
CC1200 Zoul arch specifics.
Zoul LED driver
LED driver implementation for the Zoul-based platforms.
Zoul Sensors
Generic module controlling sensors on the Zoul platform.
RE-Mote revision B arch LED
LED driver implementation for the RE-Mote revision B.
Files
file contiki-conf.h
Configuration for the Zoul-based platforms.
file contiki-main.c
Main module for the Zolertia Zoul core and based platforms.
Functions
void board_init (void)
Board specific iniatialisation.
int main (void)
Main routine for the Zoul-based platforms.
Compiler configuration and platform-specific type definitions
Those values are not meant to be modified by the user
typedef uint32_t clock_time_t
typedef uint32_t uip_stats_t
typedef uint32_t rtimer_clock_t
#define CLOCK_CONF_SECOND 128
#define CCIF
#define CLIF
#define RTIMER_CLOCK_DIFF(a, b) ((int32_t)((a) - (b)))
Serial Boot Loader Backdoor configuration
#define FLASH_CCA_CONF_BOOTLDR_BACKDOOR 1
Enable the boot loader backdoor.
#define FLASH_CCA_CONF_BOOTLDR_BACKDOOR_PORT_A_PIN 3
Pin PA_3 (user button), activates the boot loader.
#define FLASH_CCA_CONF_BOOTLDR_BACKDOOR_ACTIVE_HIGH 0
A logic low level activates the boot loader.
CC2538 System Control configuration
#define SYS_CTRL_CONF_OSC32K_USE_XTAL 1
Use the on-board 32.768-kHz crystal.
CFS configuration
#define COFFEE_CONF_SIZE (4 * COFFEE_SECTOR_SIZE)
Watchdog Timer configuration
#define WATCHDOG_CONF_ENABLE 1
Enable the watchdog timer.
USB 'core' configuration
Those values are not meant to be modified by the user, except where stated otherwise
#define CTRL_EP_SIZE 8
#define USB_EP1_SIZE 32
#define USB_EP2_SIZE 64
#define USB_EP3_SIZE 64
#define USB_ARCH_WRITE_NOTIFY 0
#define USB_ARCH_CONF_DMA 1
Change to Enable/Disable USB DMA.
Generic Configuration directives
#define STARTUP_CONF_VERBOSE 1
Set to 0 to decrease startup verbosity.
uDMA Configuration and channel allocations
#define USB_ARCH_CONF_RX_DMA_CHAN 0
USB -> RAM DMA channel.
#define USB_ARCH_CONF_TX_DMA_CHAN 1
RAM -> USB DMA channel.
#define CC2538_RF_CONF_TX_DMA_CHAN 2
RF -> RAM DMA channel.
#define CC2538_RF_CONF_RX_DMA_CHAN 3
RAM -> RF DMA channel.
#define UDMA_CONF_MAX_CHANNEL CC2538_RF_CONF_RX_DMA_CHAN
Character I/O Configuration
#define UART_CONF_ENABLE 1
Enable/Disable UART I/O.
#define UART0_CONF_BAUD_RATE 115200
Default UART0 baud rate.
#define UART1_CONF_BAUD_RATE 115200
Default UART1 baud rate.
#define SLIP_ARCH_CONF_USB 0
SLIP over UART by default.
#define DBG_CONF_USB 0
All debugging over UART by default.
#define SERIAL_LINE_CONF_UART 0
UART to use with serial line.
#define SLIP_ARCH_CONF_UART 0
UART to use with SLIP.
#define DBG_CONF_UART 0
UART to use for debugging.
#define UART1_CONF_UART 0
UART to use for examples relying on the uart1_* API.
#define SLIP_BRIDGE_CONF_NO_PUTCHAR 1
#define SLIP_RADIO_CONF_NO_PUTCHAR 1
#define CC2538_CONF_QUIET 0
Define this as 1 to build a headless node.
#define USB_SERIAL_CONF_ENABLE
Enable the USB core only if we need it.
#define UART_IN_USE_BY_SERIAL_LINE(u) (SERIAL_LINE_CONF_UART == (u))
#define UART_IN_USE_BY_SLIP(u)
#define UART_IN_USE_BY_DBG(u) (!DBG_CONF_USB && DBG_CONF_UART == (u))
#define UART_IN_USE_BY_UART1(u) (UART1_CONF_UART == (u))
#define UART_IN_USE(u)
Radio Configuration
#define NETSTACK_CONF_RADIO cc2538_rf_driver
#define ANTENNA_SW_SELECT_DEFAULT ANTENNA_SW_SELECT_2_4GHZ
LPM configuration
#define LPM_CONF_ENABLE 1
Set to 0 to disable LPM entirely.
#define LPM_CONF_MAX_PM 2
Maximum PM.
#define LPM_CONF_STATS 0
Set to 1 to enable LPM-related stats.
IEEE address configuration
Used to generate our link-layer & IPv6 address
#define IEEE_ADDR_CONF_HARDCODED 0
Location of the IEEE address 0 => Read from InfoPage, 1 => Use a hardcoded address, configured by IEEE_ADDR_CONF_ADDRESS.
#define IEEE_ADDR_CONF_ADDRESS { 0x00, 0x12, 0x4B, 0x00, 0x89, 0xAB, 0xCD, 0xEF }
The hardcoded IEEE address to be used when IEEE_ADDR_CONF_HARDCODED is defined as 1.
#define IEEE_ADDR_CONF_USE_SECONDARY_LOCATION 0
Location of the IEEE address in the InfoPage when IEEE_ADDR_CONF_HARDCODED is defined as 0 0 => Use the primary address location 1 => Use the secondary address location.
RF configuration
#define CC2538_RF_CONF_CHANNEL 26
#define CC2538_RF_CONF_AUTOACK 1
RF H/W generates ACKs.
#define CC2538_RF_CONF_TX_USE_DMA 1
RF TX over DMA.
#define CC2538_RF_CONF_RX_USE_DMA 1
RF RX over DMA.
Security
#define CRYPTO_CONF_INIT 1
Whether to init cryptoprocessor.
#define AES_128_CONF cc2538_aes_128_driver
AES-128 driver.
#define CCM_STAR_CONF cc2538_ccm_star_driver
AES-CCM* driver.
RTC
#define RTC_CONF_INIT 0
Detailed Description
The Zoul comprises the CC2538SF53 and CC1200 in a single module format, which allows a fast reuse of its core components in different formats and form-factors.
Macro Definition Documentation
CC2538_CONF_QUIET
#define CC2538_CONF_QUIET 0
Define this as 1 to build a headless node.
The UART will not be initialised its clock will be gated, offering some energy savings. The USB will not be initialised either
Definition at line 260 of file contiki-conf.h.
LPM_CONF_MAX_PM
#define LPM_CONF_MAX_PM 2
Maximum PM.
The SoC will never drop to a Power Mode deeper than the one specified here. 0 for PM0, 1 for PM1 and 2 for PM2
Definition at line 375 of file contiki-conf.h.
Function Documentation
main()
int main (void)
Main routine for the Zoul-based platforms.
Main routine for the cc2538dk platform.
Definition at line 205 of file contiki-main.c.
References clock_init(), gpio_init(), ioc_init(), lpm_init(), nvic_init(), rtimer_init(), and sys_ctrl_init().