ContikiNG: Uip6
Uip6
Modules
IPv6 Multicast Forwarding
We currently support 2 engines:
Files
file uip-ds6-nbr.c
IPv6 Neighbor cache (link-layer/IPv6 address mapping)
file uip-ds6-nbr.h
IPv6 Neighbor cache (link-layer/IPv6 address mapping)
file uip-ds6-route.c
Routing table manipulation.
file uip-ds6-route.h
Header file for routing table manipulation.
file uip-ds6.c
IPv6 data structure manipulation.
file uip-ds6.h
Header file for IPv6-related data structures.
file uip-icmp6.c
ICMPv6 (RFC 4443) implementation, with message and error handling.
file uip-icmp6.h
Header file for ICMPv6 message and error handing (RFC 4443)
file uip-nameserver.c
    uIP Name Server interface
file uip-nameserver.h
    uIP Name Server interface
file uip-nd6.c
Neighbor discovery (RFC 4861)
file uip-nd6.h
Header file for IPv6 Neighbor discovery (RFC 4861)
file uip6.c
The uIP TCP/IPv6 stack code.
file rpl-nbr-policy.c
Default RPL NBR policy decides when to add a new discovered node to the nbr table from RPL.
file rpl-nbr-policy.c
Default RPL NBR policy decides when to add a new discovered node to the nbr table from RPL.
Data Structures
struct uip_ds6_nbr
An entry in the nbr cache.
struct uip_ds6_route_neighbor_routes
The neighbor routes hold a list of routing table entries that are attached to a specific neihbor.
struct uip_ds6_route
An entry in the routing table.
struct uip_ds6_route_neighbor_route
A neighbor route list entry, used on the uip_ds6_route->neighbor_routes->route_list list.
struct uip_ds6_defrt
An entry in the default router list.
struct uip_ds6_prefix
A prefix list entry.
struct uip_ds6_addr
Unicast address structure.
struct uip_ds6_aaddr
Anycast address.
struct uip_ds6_maddr
A multicast address.
struct uip_ds6_netif
Interface structure (contains all the interface variables)
struct uip_ds6_element
Generic type for a DS6, to use a common loop though all DS.
struct uip_icmp6_error
ICMPv6 Error message constant part.
struct uip_nd6_ns
A neighbor solicitation constant part.
struct uip_nd6_na
A neighbor advertisement constant part.
struct uip_nd6_rs
A router solicitation constant part.
struct uip_nd6_ra
A router advertisement constant part.
struct uip_nd6_redirect
A redirect message constant part.
struct uip_nd6_opt_hdr
ND option header.
struct uip_nd6_opt_prefix_info
ND option prefix information.
struct uip_nd6_opt_mtu
ND option MTU.
struct uip_nd6_opt_dns
ND option RDNSS.
Macros
#define NBR_INCOMPLETE 0
Possible states for the nbr cache entries.
#define UIP_DS6_ROUTE_STATE_TYPE rpl_route_entry_t
define some additional RPL related route state and neighbor callback for RPL - if not a DS6_ROUTE_STATE is already set
#define UIP_DS6_DEFRT_NBS 0
Configuration.
#define ADDR_TENTATIVE 0
Possible states for the an address (RFC 4862)
#define ADDR_ANYTYPE 0
How the address was acquired: Autoconf, DHCP or manually.
#define UIP_DS6_PERIOD (CLOCK_SECOND/10)
General DS6 definitions.
#define UIP_ICMP6_ECHO_REQUEST_LEN 4
Echo Request constant part length.
#define UIP_ICMP6_ERROR_LEN 4
ICMPv6 Error message constant part length.
#define DNS_EXPIRATION(r)
Expiration time in seconds.
#define UIP_ND6_OPT_HDR_BUF ((uip_nd6_opt_hdr *)&uip_buf[uip_l2_l3_icmp_hdr_len + nd6_opt_offset])
Pointer to ND option.
#define UIP_ND6_DEF_MAXDADNS UIP_ND6_SEND_NS
Do not try DAD when using EUI-64 as allowed by draft-ietf-6lowpan-nd-15 section 8.2.
#define uip_create_linklocal_rplnodes_mcast(addr) uip_ip6addr((addr), 0xff02, 0, 0, 0, 0, 0, 0, 0x001a)
Set IP address addr to the link-local, all-rpl-nodes multicast address.
#define uip_is_addr_linklocal_rplnodes_mcast(addr)
Is IPv6 address addr the link-local, all-RPL-nodes multicast address?
Typedefs
typedef struct uip_ds6_nbr uip_ds6_nbr_t
An entry in the nbr cache.
typedef struct uip_ds6_route uip_ds6_route_t
An entry in the routing table.
typedef struct uip_ds6_defrt uip_ds6_defrt_t
An entry in the default router list.
typedef struct uip_ds6_prefix uip_ds6_prefix_t
A prefix list entry.
typedef struct uip_ds6_addr uip_ds6_addr_t
Unicast address structure.
typedef struct uip_ds6_aaddr uip_ds6_aaddr_t
Anycast address.
typedef struct uip_ds6_maddr uip_ds6_maddr_t
A multicast address.
typedef struct uip_ds6_netif uip_ds6_netif_t
Interface structure (contains all the interface variables)
typedef struct uip_ds6_element uip_ds6_element_t
Generic type for a DS6, to use a common loop though all DS.
typedef struct uip_icmp6_error uip_icmp6_error
ICMPv6 Error message constant part.
typedef struct uip_nameserver_record uip_nameserver_record
Nameserver record.
Functions
uip_ds6_nbr_t * uip_ds6_nbr_add (const uip_ipaddr_t *ipaddr, const uip_lladdr_t *lladdr, uint8_t isrouter, uint8_t state, nbr_table_reason_t reason, void *data)
Neighbor Cache basic routines.
uip_ds6_nbr_t * uip_ds6_get_least_lifetime_neighbor (void)
This searches inside the neighbor table for the neighbor that is about to expire the next.
void uip_ds6_init (void)
Initialize data structures.
void uip_ds6_periodic (void)
Periodic processing of data structures.
uint8_t uip_ds6_list_loop (uip_ds6_element_t *list, uint8_t size, uint16_t elementsize, uip_ipaddr_t *ipaddr, uint8_t ipaddrlen, uip_ds6_element_t **out_element)
Generic loop routine on an abstract data structure, which generalizes all data structures used in DS6.
uip_ds6_addr_t * uip_ds6_addr_add (uip_ipaddr_t *ipaddr, unsigned long vlifetime, uint8_t type)
Add a unicast address to the interface.
void uip_ds6_select_src (uip_ipaddr_t *src, uip_ipaddr_t *dst)
Source address selection, see RFC 3484.
void uip_ds6_set_addr_iid (uip_ipaddr_t *ipaddr, uip_lladdr_t *lladdr)
set the last 64 bits of an IP address based on the MAC address
void uip_ds6_set_lladdr_from_iid (uip_lladdr_t *lladdr, const uip_ipaddr_t *ipaddr)
Build a link-layer address from an IPv6 address based on its UUID64.
uint8_t get_match_length (uip_ipaddr_t *src, uip_ipaddr_t *dst)
Get the number of matching bits of two addresses.
void uip_ds6_dad (uip_ds6_addr_t *addr)
Perform Duplicate Address Selection on one address.
int uip_ds6_dad_failed (uip_ds6_addr_t *addr)
Callback when DAD failed.
void uip_ds6_send_rs (void)
Send periodic RS to find router.
uint32_t uip_ds6_compute_reachable_time (void)
Compute the reachable time based on base reachable time, see RFC 4861.
void uip_add32 (uint8_t *op32, uint16_t op16)
Carry out a 32-bit addition.
uint16_t uip_chksum (uint16_t *data, uint16_t len)
Calculate the Internet checksum over a buffer.
uint16_t uip_ipchksum (void)
Calculate the IP header checksum of the packet header in uip_buf.
uint16_t uip_icmp6chksum (void)
Calculate the ICMP checksum of the packet in uip_buf.
uint16_t uip_tcpchksum (void)
Calculate the TCP checksum of the packet in uip_buf and uip_appdata.
void uip_init (void)
uIP initialization function.
struct uip_udp_conn * uip_udp_new (const uip_ipaddr_t *ripaddr, uint16_t rport)
Set up a new UDP connection.
void uip_unlisten (uint16_t port)
Stop listening to the specified port.
void uip_listen (uint16_t port)
Start listening to the specified port.
void uip_reass_over (void)
Abandon the reassembly of the current packet.
static uint8_t ext_hdr_options_process (void)
Process the options in Destination and Hop By Hop extension headers.
void uip_process (uint8_t flag)
process the options within a hop by hop or destination option header
uint16_t uip_htons (uint16_t val)
Convert a 16-bit quantity from host byte order to network byte order.
void uip_send (const void *data, int len)
Send data on the current connection.
void rpl_dag_init (void)
Initializes rpl-dag module.
rpl_instance_t * rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
int rpl_has_downward_route (void)
Get the RPL's best guess on if we have downward route or not.
rpl_dag_t * rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
void rpl_process_dio (uip_ipaddr_t *from, rpl_dio_t *dio)
Processes incoming DIO.
int rpl_ext_header_hbh_update (int uip_ext_opt_offset)
Process and update the RPL extension headers of the current uIP packet.
void rpl_ext_header_remove (void)
Removes all RPL extension headers.
int rpl_ext_header_update (void)
Adds/updates RPL extension headers to current uIP packet.
uip_ds6_nbr_t * rpl_icmp6_update_nbr_table (uip_ipaddr_t *from, nbr_table_reason_t reason, void *data)
Updates IPv6 neighbor cache on incoming link-local RPL ICMPv6 messages.
enum rpl_mode rpl_get_mode (void)
Get the RPL mode.
enum rpl_mode rpl_set_mode (enum rpl_mode m)
Set the RPL mode.
void rpl_link_callback (const linkaddr_t *addr, int status, int numtx)
Called by lower layers after every packet transmission.
void rpl_init (void)
Initialize RPL main module.
void rpl_dag_root_init (uip_ipaddr_t *prefix, uip_ipaddr_t *iid)
Initialize dag-root module and sets a prefix in case the node is later set as dag root.
void rpl_dag_root_init_dag_delay (void)
Initializes the node as DAG root after a delay.
int rpl_dag_root_init_dag_immediately (void)
Initializes the node as DAG root immediatly.
int rpl_dag_root_is_root (void)
Tells whether we are DAG root or not.
const char * rpl_dag_state_to_str (enum rpl_dag_state state)
Returns a textual description of the current DAG state.
void rpl_dag_leave (void)
Leaves the current DAG.
void rpl_dag_poison_and_leave (void)
Start poisoning and leave the DAG after a delay.
void rpl_dag_periodic (unsigned seconds)
A function called periodically.
int rpl_is_addr_in_our_dag (const uip_ipaddr_t *addr)
Tells whether a given global IPv6 address is in our current DAG.
void rpl_global_repair (void)
Triggers a RPL global repair.
void rpl_local_repair (const char *str)
Triggers a RPL local repair.
int rpl_dag_ready_to_advertise (void)
Tells whether RPL is ready to advertise the DAG.
void rpl_dag_update_state (void)
Updates RPL internal state: selects preferred parent, updates rank & metreic container, triggers control traffic accordingly and updates uIP6 internal state.
void rpl_process_dis (uip_ipaddr_t *from, int is_multicast)
Processes incoming DIS.
void rpl_process_dao (uip_ipaddr_t *from, rpl_dao_t *dao)
Processes incoming DAO.
int rpl_process_hbh (rpl_nbr_t *sender, uint16_t sender_rank, int loop_detected, int rank_error_signaled)
Processes Hop-by-Hop (HBH) Extension Header of a packet currently being forwrded.
void rpl_dag_init_root (uint8_t instance_id, uip_ipaddr_t *dag_id, uip_ipaddr_t *prefix, unsigned prefix_len, uint8_t flags)
Initializes DAG internal structure for a root node.
void rpl_process_dao_ack (uint8_t sequence, uint8_t status)
Processes incoming DAO-ACK.
int rpl_ext_header_srh_get_next_hop (uip_ipaddr_t *ipaddr)
Look for next hop from SRH of current uIP packet.
int rpl_ext_header_srh_update (void)
Process and update SRH in-place, i.e.
void rpl_icmp6_dis_output (uip_ipaddr_t *addr)
Creates an ICMPv6 DIS packet and sends it.
void rpl_icmp6_dio_output (uip_ipaddr_t *uc_addr)
Creates an ICMPv6 DIO packet and sends it.
void rpl_icmp6_dao_output (uint8_t lifetime)
Creates an ICMPv6 DAO packet and sends it to the root, advertising the current preferred parent, and with our global address as prefix.
void rpl_icmp6_init (void)
Initializes rpl-icmp6 module, registers ICMPv6 handlers for all RPL ICMPv6 messages: DIO, DIS, DAO and DAO-ACK.
void rpl_icmp6_dao_ack_output (uip_ipaddr_t *dest, uint8_t sequence, uint8_t status)
Creates an ICMPv6 DAO-ACK packet and sends it to the originator of the ACK.
void rpl_neighbor_print_list (const char *str)
Prints a summary of all RPL neighbors and their properties.
int rpl_neighbor_count (void)
Returns the number of nodes in the RPL neighbor table.
rpl_nbr_t * rpl_neighbor_get_from_lladdr (uip_lladdr_t *addr)
Returns a neighbor from its link-layer address.
int rpl_neighbor_is_acceptable_parent (rpl_nbr_t *nbr)
Tells whether a nbr is acceptable as per the OF's definition.
uint16_t rpl_neighbor_get_link_metric (rpl_nbr_t *nbr)
Returns a neighbor's link metric.
rpl_rank_t rpl_neighbor_rank_via_nbr (rpl_nbr_t *nbr)
Returns our rank if selecting a given parent as preferred parent.
const linkaddr_t * rpl_neighbor_get_lladdr (rpl_nbr_t *nbr)
Returns a neighbors's link-layer address.
uip_ipaddr_t * rpl_neighbor_get_ipaddr (rpl_nbr_t *nbr)
Returns a neighbor's (link-local) IPv6 address.
const struct link_stats * rpl_neighbor_get_link_stats (rpl_nbr_t *nbr)
Returns a neighbor's link statistics.
int rpl_neighbor_is_fresh (rpl_nbr_t *nbr)
Tells wether we have fresh link information towards a given neighbor.
int rpl_neighbor_is_reachable (rpl_nbr_t *nbr)
Tells wether we a given neighbor is reachable.
int rpl_neighbor_is_parent (rpl_nbr_t *nbr)
Tells whether a neighbor is in the parent set.
void rpl_neighbor_set_preferred_parent (rpl_nbr_t *nbr)
Set current RPL preferred parent and update DS6 default route accordingly.
void rpl_neighbor_remove_all (void)
Empty the RPL neighbor table.
rpl_nbr_t * rpl_neighbor_get_from_ipaddr (uip_ipaddr_t *addr)
Returns a neighbor from its link-local IPv6 address.
rpl_nbr_t * rpl_neighbor_select_best (void)
Returns the best candidate for preferred parent.
void rpl_neighbor_init (void)
Initialize rpl-dag-neighbor module.
int rpl_ns_num_nodes (void)
Tells how many nodes are currently stored in the graph.
void rpl_ns_expire_parent (const uip_ipaddr_t *child, const uip_ipaddr_t *parent)
Expires a given child-parent link.
rpl_ns_node_t * rpl_ns_update_node (const uip_ipaddr_t *child, const uip_ipaddr_t *parent, uint32_t lifetime)
Updates a child-parent link.
rpl_ns_node_t * rpl_ns_node_head (void)
Returns the head of the non-storing node list.
rpl_ns_node_t * rpl_ns_node_next (rpl_ns_node_t *item)
Returns the next element of the non-storing node list.
rpl_ns_node_t * rpl_ns_get_node (const uip_ipaddr_t *addr)
Looks up for a RPL NS node from its IPv6 global address.
int rpl_ns_is_addr_reachable (const uip_ipaddr_t *addr)
Telle whether an address is reachable, i.e.
int rpl_ns_get_node_global_addr (uip_ipaddr_t *addr, rpl_ns_node_t *node)
Finds the global address of a given node.
void rpl_ns_periodic (unsigned seconds)
A function called periodically.
void rpl_ns_init (void)
Initialize rpl-ns module.
void rpl_ns_free_all (void)
Deallocate all neighbors.
void rpl_timers_schedule_periodic_dis (void)
Schedule periodic DIS with a random delay based on RPL_DIS_INTERVAL, until we join a DAG.
void rpl_timers_dio_reset (const char *str)
Reset DIO Trickle timer.
void rpl_timers_schedule_unicast_dio (rpl_nbr_t *target)
Schedule unicast DIO with no delay.
void rpl_timers_schedule_dao (void)
Schedule a DAO with random delay based on RPL_DAO_DELAY.
void rpl_timers_unschedule_leaving (void)
Cancel scheduled leaving if any.
void rpl_timers_schedule_leaving (void)
Schedule leaving after RPL_DELAY_BEFORE_LEAVING.
void rpl_timers_init (void)
Initialize rpl-timers module.
void rpl_timers_stop_dag_timers (void)
Stop all timers related to the DAG.
void rpl_timers_unschedule_state_update (void)
Cancelled any scheduled state update.
void rpl_timers_schedule_state_update (void)
Schedule a state update ASAP.
void rpl_timers_schedule_dao_ack (uip_ipaddr_t *target, uint16_t sequence)
Schedule a DAO-ACK with no delay.
void rpl_schedule_probing (void)
Schedule probing with delay RPL_PROBING_DELAY_FUNC()
int rpl_lollipop_greater_than (int a, int b)
Greater-than function for a lollipop counter.
const uip_ipaddr_t * rpl_get_global_address (void)
Get one of the node's global addresses.
int rpl_is_reachable (void)
Get the RPL's best guess on if we are reachable via have downward route or not.
void rpl_reset_prefix (rpl_prefix_t *last_prefix)
Removes current prefx.
int rpl_set_prefix_from_addr (uip_ipaddr_t *addr, unsigned len, uint8_t flags)
Set prefix from an IPv6 address.
int rpl_set_prefix (rpl_prefix_t *prefix)
Set prefix from an prefix data structure (from DIO)
Variables
struct etimer uip_ds6_timer_periodic
Timer for maintenance of data structures.
struct etimer uip_ds6_timer_rs
RS timer, to schedule RS sending.
static uint8_t rscount
number of rs already sent
uip_ds6_netif_t uip_ds6_if
The single interface.
struct etimer uip_ds6_timer_periodic
Timer for maintenance of data structures.
struct etimer uip_ds6_timer_rs
RS timer, to schedule RS sending.
static uip_ipaddr_t tmp_ipaddr
temporary IP address
struct etimer uip_reass_timer
Timer for reassembly.
Default router list basic routines
uip_ds6_defrt_t * uip_ds6_defrt_head (void)
uip_ds6_defrt_t * uip_ds6_defrt_add (uip_ipaddr_t *ipaddr, unsigned long interval)
void uip_ds6_defrt_rm (uip_ds6_defrt_t *defrt)
uip_ds6_defrt_t * uip_ds6_defrt_lookup (uip_ipaddr_t *ipaddr)
uip_ipaddr_t * uip_ds6_defrt_choose (void)
void uip_ds6_defrt_periodic (void)
Routing Table basic routines
uip_ipaddr_t * uip_ds6_route_nexthop (uip_ds6_route_t *route)
uip_ds6_route_t * uip_ds6_route_head (void)
uip_ds6_route_t * uip_ds6_route_next (uip_ds6_route_t *r)
int uip_ds6_route_is_nexthop (const uip_ipaddr_t *ipaddr)
int uip_ds6_route_num_routes (void)
uip_ds6_route_t * uip_ds6_route_lookup (uip_ipaddr_t *addr)
uip_ds6_route_t * uip_ds6_route_add (uip_ipaddr_t *ipaddr, uint8_t length, uip_ipaddr_t *nexthop)
void uip_ds6_route_rm (uip_ds6_route_t *route)
void uip_ds6_route_rm_by_nexthop (uip_ipaddr_t *nexthop)
"DS6" Data structures
uip_ds6_netif_t uip_ds6_if
The single interface.
uip_ds6_prefix_t uip_ds6_prefix_list [UIP_DS6_PREFIX_NB]
Prefix list.
uint8_t uip_ds6_addr_size
uint8_t uip_ds6_netif_addr_list_offset
ICMPv6 message types
#define ICMP6_DST_UNREACH 1
dest unreachable
#define ICMP6_PACKET_TOO_BIG 2
packet too big
#define ICMP6_TIME_EXCEEDED 3
time exceeded
#define ICMP6_PARAM_PROB 4
ip6 header bad
#define ICMP6_ECHO_REQUEST 128
Echo request.
#define ICMP6_ECHO_REPLY 129
Echo reply.
#define ICMP6_RS 133
Router Solicitation.
#define ICMP6_RA 134
Router Advertisement.
#define ICMP6_NS 135
Neighbor Solicitation.
#define ICMP6_NA 136
Neighbor advertisement.
#define ICMP6_REDIRECT 137
Redirect.
#define ICMP6_RPL 155
RPL.
#define ICMP6_PRIV_EXP_100 100
Private Experimentation.
#define ICMP6_PRIV_EXP_101 101
Private Experimentation.
#define ICMP6_PRIV_EXP_200 200
Private Experimentation.
#define ICMP6_PRIV_EXP_201 201
Private Experimentation.
#define ICMP6_ROLL_TM ICMP6_PRIV_EXP_200
ROLL Trickle Multicast.
#define ICMP6_ESMRF ICMP6_PRIV_EXP_201
ESMRF Multicast.
ICMPv6 Destination Unreachable message codes
#define ICMP6_DST_UNREACH_NOROUTE 0
no route to destination
#define ICMP6_DST_UNREACH_ADMIN 1
administratively prohibited
#define ICMP6_DST_UNREACH_NOTNEIGHBOR 2
not a neighbor(obsolete)
#define ICMP6_DST_UNREACH_BEYONDSCOPE 2
beyond scope of source address
#define ICMP6_DST_UNREACH_ADDR 3
address unreachable
#define ICMP6_DST_UNREACH_NOPORT 4
port unreachable
ICMPv6 Time Exceeded message codes
#define ICMP6_TIME_EXCEED_TRANSIT 0
ttl==0 in transit
#define ICMP6_TIME_EXCEED_REASSEMBLY 1
ttl==0 in reass
ICMPv6 Parameter Problem message codes
#define ICMP6_PARAMPROB_HEADER 0
erroneous header field
#define ICMP6_PARAMPROB_NEXTHEADER 1
unrecognized next header
#define ICMP6_PARAMPROB_OPTION 2
unrecognized option
ICMPv6 RFC4443 Message processing and sending
typedef void(* uip_icmp6_echo_reply_callback_t) (uip_ipaddr_t *source, uint8_t ttl, uint8_t *data, uint16_t datalen)
typedef struct uip_icmp6_input_handler uip_icmp6_input_handler_t
uint8_t uip_icmp6_input (uint8_t type, uint8_t icode)
Handle an incoming ICMPv6 message.
void uip_icmp6_register_input_handler (uip_icmp6_input_handler_t *handler)
Register a handler which can handle a specific ICMPv6 message type.
void uip_icmp6_error_output (uint8_t type, uint8_t code, uint32_t param)
Send an icmpv6 error message.
void uip_icmp6_send (const uip_ipaddr_t *dest, int type, int code, int payload_len)
Send an icmpv6 message.
void uip_icmp6_echo_reply_callback_add (struct uip_icmp6_echo_reply_notification *n, uip_icmp6_echo_reply_callback_t c)
Add a callback function for ping replies.
void uip_icmp6_echo_reply_callback_rm (struct uip_icmp6_echo_reply_notification *n)
Remove a callback function for ping replies.
void uip_icmp6_init (void)
Initialise the uIP ICMPv6 core.
#define UIP_ICMP6_INPUT_SUCCESS 0
#define UIP_ICMP6_INPUT_ERROR 1
#define UIP_ICMP6_HANDLER_CODE_ANY 0xFF /* Handle all codes for this type */
#define UIP_ICMP6_HANDLER(name, type, code, func) static uip_icmp6_input_handler_t name = { NULL, type, code, func }
List and memory block
static uip_ipaddr_t serveraddr
static uint32_t serverlifetime
General
#define UIP_NAMESERVER_POOL_SIZE 1
Number of Nameservers to keep.
#define UIP_NAMESERVER_INFINITE_LIFETIME 0xFFFFFFFF
Infinite Lifetime indicator.
Nameserver maintenance
void uip_nameserver_update (const uip_ipaddr_t *nameserver, uint32_t lifetime)
Initialize the module variables.
uip_ipaddr_t * uip_nameserver_get (uint8_t num)
Get a Nameserver ip address given in RA.
uint32_t uip_nameserver_next_expiration (void)
Get next expiration time.
uint16_t uip_nameserver_count (void)
Get the number of recorded name servers.
Pointers to the header structures.
All pointers except UIP_IP_BUF depend on uip_ext_len, which at packet reception, is the total length of the extension headers.
The pointer to ND6 options header also depends on nd6_opt_offset, which we set in each function.
Care should be taken when manipulating these buffers about the value of these length variables
#define UIP_IP_BUF ((struct uip_ip_hdr *)&uip_buf[UIP_LLH_LEN])
Pointer to IP header.
#define UIP_ICMP_BUF ((struct uip_icmp_hdr *)&uip_buf[uip_l2_l3_hdr_len])
Pointer to ICMP header.
#define UIP_ND6_RS_BUF ((uip_nd6_rs *)&uip_buf[uip_l2_l3_icmp_hdr_len])
#define UIP_ND6_RA_BUF ((uip_nd6_ra *)&uip_buf[uip_l2_l3_icmp_hdr_len])
#define UIP_ND6_NS_BUF ((uip_nd6_ns *)&uip_buf[uip_l2_l3_icmp_hdr_len])
#define UIP_ND6_NA_BUF ((uip_nd6_na *)&uip_buf[uip_l2_l3_icmp_hdr_len])
General
#define UIP_ND6_HOP_LIMIT 255
HOP LIMIT to be used when sending ND messages (255)
#define UIP_ND6_INFINITE_LIFETIME 0xFFFFFFFF
INFINITE lifetime.
RFC 4861 Host constant
#define UIP_ND6_MAX_RTR_SOLICITATION_DELAY 1
Maximum router solicitation delay.
#define UIP_ND6_RTR_SOLICITATION_INTERVAL 4
Router solicitation interval.
#define UIP_ND6_MAX_RTR_SOLICITATIONS 3
Maximum router solicitations.
RFC 4861 Router constants
#define UIP_ND6_SEND_RA 1 /* enable/disable RA sending */
#define UIP_ND6_SEND_NS 1 /* enable/disable NS sending */
#define UIP_ND6_SEND_NA 1 /* enable/disable NA sending */
#define UIP_ND6_AUTOFILL_NBR_CACHE 0
#define UIP_ND6_MAX_RA_INTERVAL 600
#define UIP_ND6_MIN_RA_INTERVAL (UIP_ND6_MAX_RA_INTERVAL / 3)
#define UIP_ND6_M_FLAG 0
#define UIP_ND6_O_FLAG (UIP_ND6_RA_RDNSS || UIP_ND6_RA_DNSSL)
#define UIP_ND6_ROUTER_LIFETIME 3 * UIP_ND6_MAX_RA_INTERVAL
#define UIP_ND6_MAX_INITIAL_RA_INTERVAL 16 /*seconds*/
#define UIP_ND6_MAX_INITIAL_RAS 3 /*transmissions*/
#define UIP_ND6_MIN_DELAY_BETWEEN_RAS 3 /*seconds*/
#define UIP_ND6_MAX_RA_DELAY_TIME_MS 500 /*milli seconds*/
RFC 4861 Node constant
#define UIP_ND6_MAX_MULTICAST_SOLICIT 3
#define UIP_ND6_MAX_UNICAST_SOLICIT 3
#define UIP_ND6_REACHABLE_TIME 60000
#define UIP_ND6_RETRANS_TIMER 1000
#define UIP_ND6_DELAY_FIRST_PROBE_TIME 5
#define UIP_ND6_MIN_RANDOM_FACTOR(x) (x / 2)
#define UIP_ND6_MAX_RANDOM_FACTOR(x) ((x) + (x) / 2)
RFC 6106 RA DNS Options Constants
#define UIP_ND6_RA_RDNSS 0
#define UIP_ND6_RA_DNSSL 0
ND6 option types
#define UIP_ND6_OPT_SLLAO 1
#define UIP_ND6_OPT_TLLAO 2
#define UIP_ND6_OPT_PREFIX_INFO 3
#define UIP_ND6_OPT_REDIRECTED_HDR 4
#define UIP_ND6_OPT_MTU 5
#define UIP_ND6_OPT_RDNSS 25
#define UIP_ND6_OPT_DNSSL 31
#define UIP_ND6_OPT_TYPE_OFFSET 0
#define UIP_ND6_OPT_LEN_OFFSET 1
#define UIP_ND6_OPT_DATA_OFFSET 2
ND6 message length (excluding options)
#define UIP_ND6_NA_LEN 20
#define UIP_ND6_NS_LEN 20
#define UIP_ND6_RA_LEN 12
#define UIP_ND6_RS_LEN 4
ND6 option length in bytes
#define UIP_ND6_OPT_HDR_LEN 2
#define UIP_ND6_OPT_PREFIX_INFO_LEN 32
#define UIP_ND6_OPT_MTU_LEN 8
#define UIP_ND6_OPT_RDNSS_LEN 1
#define UIP_ND6_OPT_DNSSL_LEN 1
#define UIP_ND6_OPT_LLAO_LEN 8
length of a ND6 LLAO option for default L2 type (e.g.
Neighbor Advertisement flags masks
#define UIP_ND6_NA_FLAG_ROUTER 0x80
#define UIP_ND6_NA_FLAG_SOLICITED 0x40
#define UIP_ND6_NA_FLAG_OVERRIDE 0x20
#define UIP_ND6_RA_FLAG_ONLINK 0x80
#define UIP_ND6_RA_FLAG_AUTONOMOUS 0x40
ND message structures
typedef struct uip_nd6_ns uip_nd6_ns
A neighbor solicitation constant part.
typedef struct uip_nd6_na uip_nd6_na
A neighbor advertisement constant part.
typedef struct uip_nd6_rs uip_nd6_rs
A router solicitation constant part.
typedef struct uip_nd6_ra uip_nd6_ra
A router advertisement constant part.
typedef struct uip_nd6_redirect uip_nd6_redirect
A redirect message constant part.
ND Option structures
typedef struct uip_nd6_opt_hdr uip_nd6_opt_hdr
ND option header.
typedef struct uip_nd6_opt_prefix_info uip_nd6_opt_prefix_info
ND option prefix information.
typedef struct uip_nd6_opt_mtu uip_nd6_opt_mtu
ND option MTU.
typedef struct uip_nd6_opt_dns uip_nd6_opt_dns
ND option RDNSS.
typedef struct uip_nd6_opt_redirected_hdr uip_nd6_opt_redirected_hdr
ND Messages Processing and Generation
void uip_nd6_ns_output (uip_ipaddr_t *src, uip_ipaddr_t *dest, uip_ipaddr_t *tgt)
Send a neighbor solicitation, send a Neighbor Advertisement.
void uip_nd6_rs_output (void)
Send a Router Solicitation.
void uip_nd6_init (void)
Initialise the uIP ND core.
Layer 2 variables
uip_lladdr_t uip_lladdr = {{0x00,0x06,0x98,0x00,0x02,0x32}}
Host L2 address.
Layer 3 variables
uint8_t * uip_next_hdr
Type of the next header in IPv6 header or extension headers.
uint8_t uip_ext_bitmap = 0
bitmap we use to record which IPv6 headers we have already seen
uint8_t uip_ext_len = 0
length of the extension headers read.
uint8_t uip_ext_opt_offset = 0
length of the header options read
Buffer defines
#define FBUF ((struct uip_tcpip_hdr *)&uip_reassbuf[0])
#define UIP_IP_BUF ((struct uip_ip_hdr *)&uip_buf[UIP_LLH_LEN])
#define UIP_ICMP_BUF ((struct uip_icmp_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_UDP_BUF ((struct uip_udp_hdr *)&uip_buf[UIP_LLH_LEN + UIP_IPH_LEN])
#define UIP_TCP_BUF ((struct uip_tcp_hdr *)&uip_buf[UIP_LLH_LEN + UIP_IPH_LEN])
#define UIP_EXT_BUF ((struct uip_ext_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_ROUTING_BUF ((struct uip_routing_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_FRAG_BUF ((struct uip_frag_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_HBHO_BUF ((struct uip_hbho_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_DESTO_BUF ((struct uip_desto_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_EXT_HDR_OPT_BUF ((struct uip_ext_hdr_opt *)&uip_buf[uip_l2_l3_hdr_len + uip_ext_opt_offset])
#define UIP_EXT_HDR_OPT_PADN_BUF ((struct uip_ext_hdr_opt_padn *)&uip_buf[uip_l2_l3_hdr_len + uip_ext_opt_offset])
#define UIP_EXT_HDR_OPT_RPL_BUF ((struct uip_ext_hdr_opt_rpl *)&uip_buf[uip_l2_l3_hdr_len + uip_ext_opt_offset])
#define UIP_ICMP6_ERROR_BUF ((struct uip_icmp6_error *)&uip_buf[uip_l2_l3_icmp_hdr_len])
Buffer variables
uip_buf_t uip_aligned_buf
Packet buffer for incoming and outgoing packets.
void * uip_appdata
Pointer to the application data in the packet buffer.
void * uip_sappdata
uint16_t uip_len
The length of the packet in the uip_buf buffer.
uint16_t uip_slen
General variables
uint8_t uip_flags
struct uip_conn * uip_conn
Pointer to the current TCP connection.
static uint16_t lastport
TCP defines
#define TCP_FIN 0x01
#define TCP_SYN 0x02
#define TCP_RST 0x04
#define TCP_PSH 0x08
#define TCP_ACK 0x10
#define TCP_URG 0x20
#define TCP_CTL 0x3f
#define TCP_OPT_END 0 /* End of TCP options list */
#define TCP_OPT_NOOP 1 /* "No-operation" TCP option */
#define TCP_OPT_MSS 2 /* Maximum segment size TCP option */
#define TCP_OPT_MSS_LEN 4 /* Length of TCP MSS option. */
TCP variables
struct uip_conn uip_conns [UIP_TCP_CONNS]
uint16_t uip_listenports [UIP_LISTENPORTS]
static uint8_t iss [4]
uint8_t uip_acc32 [4]
4-byte array used for the 32-bit sequence number calculations.
UDP variables
struct uip_udp_conn * uip_udp_conn
The current UDP connection.
struct uip_udp_conn uip_udp_conns [UIP_UDP_CONNS]
ICMPv6 variables
struct uip_icmp6_conn uip_icmp6_conns
single possible icmpv6 "connection"
Detailed Description
Macro Definition Documentation
uip_create_linklocal_rplnodes_mcast
#define uip_create_linklocal_rplnodes_mcast (addr) uip_ip6addr((addr), 0xff02, 0, 0, 0, 0, 0, 0, 0x001a)
Set IP address addr to the link-local, all-rpl-nodes multicast address.
Definition at line 53 of file rpl-types.h.
UIP_DS6_DEFRT_NBS
#define UIP_DS6_DEFRT_NBS 0
Configuration.
For all tables (Neighbor cache, Prefix List, Routing Table, Default Router List, Unicast address list, multicast address list, anycast address list), we define:
the number of elements requested by the user in contiki configuration (name suffixed by _NBU)
the number of elements assigned by the system (name suffixed by _NBS)
the total number of elements is the sum (name suffixed by _NB) The routing table definitions can be found in uip-ds6-route.h The Neighbor cache definitions can be found in nbr-table.h
Definition at line 64 of file uip-ds6.h.
UIP_DS6_PERIOD
#define UIP_DS6_PERIOD (CLOCK_SECOND/10)
General DS6 definitions.
Period for uip-ds6 periodic task
Definition at line 168 of file uip-ds6.h.
UIP_ND6_OPT_LLAO_LEN
#define UIP_ND6_OPT_LLAO_LEN 8
length of a ND6 LLAO option for default L2 type (e.g.
Ethernet)
Definition at line 243 of file uip-nd6.h.
UIP_ND6_RS_BUF
#define UIP_ND6_RS_BUF ((uip_nd6_rs *)&uip_buf[uip_l2_l3_icmp_hdr_len])
Pointers to messages just after icmp header
Definition at line 99 of file uip-nd6.c.
Typedef Documentation
uip_ds6_addr_t
typedef struct uip_ds6_addr uip_ds6_addr_t
Unicast address structure.
uip_nd6_na
typedef struct uip_nd6_na uip_nd6_na
A neighbor advertisement constant part.
Possible option is: TLLAO
uip_nd6_ns
typedef struct uip_nd6_ns uip_nd6_ns
A neighbor solicitation constant part.
Possible option is: SLLAO
uip_nd6_ra
typedef struct uip_nd6_ra uip_nd6_ra
A router advertisement constant part.
Possible options are: SLLAO, MTU, Prefix Information
uip_nd6_redirect
typedef struct uip_nd6_redirect uip_nd6_redirect
A redirect message constant part.
Possible options are: TLLAO, redirected header
uip_nd6_rs
typedef struct uip_nd6_rs uip_nd6_rs
A router solicitation constant part.
Possible option is: SLLAO
Function Documentation
rpl_dag_init_root()
void rpl_dag_init_root (uint8_t instance_id, uip_ipaddr_t * dag_id, uip_ipaddr_t * prefix, unsigned prefix_len, uint8_t flags)
Initializes DAG internal structure for a root node.
Parameters
instance_id The instance ID
dag_id The DAG ID
prefix The prefix
prefix_len The prefix length
flags The prefix flags (from DIO)
Definition at line 659 of file rpl-dag.c.
rpl_dag_leave()
void rpl_dag_leave (void)
Leaves the current DAG.
Definition at line 84 of file rpl-dag.c.
rpl_dag_periodic()
void rpl_dag_periodic (unsigned seconds)
A function called periodically.
Used to age the DAG (decrease lifetime and expire DAG accordingly)
Parameters
seconds The number of seconds elapsted since last call
Definition at line 123 of file rpl-dag.c.
rpl_dag_poison_and_leave()
void rpl_dag_poison_and_leave (void)
Start poisoning and leave the DAG after a delay.
Definition at line 116 of file rpl-dag.c.
rpl_dag_ready_to_advertise()
int rpl_dag_ready_to_advertise (void)
Tells whether RPL is ready to advertise the DAG.
Returns
1 is ready, 0 otherwise
Definition at line 222 of file rpl-dag.c.
Referenced by rpl_timers_dio_reset().
rpl_dag_root_init()
void rpl_dag_root_init (uip_ipaddr_t * prefix, uip_ipaddr_t * iid)
Initialize dag-root module and sets a prefix in case the node is later set as dag root.
Parameters
prefix The prefix. If NULL, UIP_DS6_DEFAULT_PREFIX is used instead
iid The IID. If NULL, it will be built from uip_ds6_set_addr_iid.
Definition at line 179 of file rpl-dag-root.c.
Referenced by rpl_dag_root_init_dag_delay().
rpl_dag_root_init_dag_delay()
void rpl_dag_root_init_dag_delay (void)
Initializes the node as DAG root after a delay.
Until the delay, the node gets a chance to hear another DAG and join it instead.
Definition at line 247 of file rpl-dag-root.c.
References rpl_dag_root_init().
rpl_dag_root_init_dag_immediately()
int rpl_dag_root_init_dag_immediately (void)
Initializes the node as DAG root immediatly.
Returns
0 in case of success, -1 otherwise
Definition at line 194 of file rpl-dag-root.c.
rpl_dag_root_is_root()
int rpl_dag_root_is_root (void)
Tells whether we are DAG root or not.
Returns
1 if we are dag root, 0 otherwise
Definition at line 259 of file rpl-dag-root.c.
References rpl_get_default_instance().
Referenced by rpl_global_repair(), and rpl_neighbor_select_best().
rpl_dag_state_to_str()
const char * rpl_dag_state_to_str (enum rpl_dag_state state)
Returns a textual description of the current DAG state.
Parameters
state The DAG state
Returns
The description string
Definition at line 67 of file rpl-dag.c.
rpl_ext_header_hbh_update()
int rpl_ext_header_hbh_update (int uip_ext_opt_offset)
Process and update the RPL extension headers of the current uIP packet.
Parameters
uip_ext_opt_offset The offset within the uIP packet where extension headers start
Returns
1 in case the packet is valid and to be processed further, 0 in case the packet must be dropped.
Definition at line 72 of file rpl-ext-header.c.
rpl_ext_header_srh_get_next_hop()
int rpl_ext_header_srh_get_next_hop (uip_ipaddr_t * ipaddr)
Look for next hop from SRH of current uIP packet.
Parameters
ipaddr A pointer to the address where to store the next hop.
Returns
1 if a next hop was found, 0 otherwise
Definition at line 69 of file rpl-ext-header.c.
References uip_ext_len, UIP_IP_BUF, and uip_next_hdr.
rpl_ext_header_srh_update()
int rpl_ext_header_srh_update (void)
Process and update SRH in-place, i.e.
internal address swapping as per RFC6554
Returns
1 if SRH found, 0 otherwise
Definition at line 124 of file rpl-ext-header.c.
References uip_ext_len, UIP_IP_BUF, and uip_next_hdr.
rpl_ext_header_update()
int rpl_ext_header_update (void)
Adds/updates RPL extension headers to current uIP packet.
Returns
1 in case of success, 0 otherwise
Definition at line 636 of file rpl-ext-header.c.
rpl_get_any_dag()
rpl_dag_t * rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
Returns
A pointer to the only supported DAG
Definition at line 1036 of file rpl-dag.c.
rpl_get_default_instance()
rpl_instance_t * rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
Returns
A pointer to the only supported instance
Definition at line 619 of file rpl-dag.c.
Referenced by rpl_dag_root_is_root().
rpl_get_global_address()
const uip_ipaddr_t * rpl_get_global_address (void)
Get one of the node's global addresses.
Returns
A (constant) pointer to the global IPv6 address found. The pointer directs to the internals of DS6, should only be used in the current function's local scope
Definition at line 71 of file rpl.c.
rpl_get_mode()
enum rpl_mode rpl_get_mode (void)
Get the RPL mode.
Return values
The RPL mode
Definition at line 66 of file rpl.c.
rpl_has_downward_route()
int rpl_has_downward_route (void)
Get the RPL's best guess on if we have downward route or not.
Return values
1 if we have a downward route from RPL Root, 0 if not.
Definition at line 1005 of file rpl-dag.c.
rpl_icmp6_dao_ack_output()
void rpl_icmp6_dao_ack_output (uip_ipaddr_t * dest, uint8_t sequence, uint8_t status)
Creates an ICMPv6 DAO-ACK packet and sends it to the originator of the ACK.
Parameters
dest The DAO-ACK destination (was source of the DAO)
sequence The sequence number of the DAO being ACKed
status The status of the DAO-ACK (see RPL_DAO_ACK_* defines)
rpl_icmp6_dao_output()
void rpl_icmp6_dao_output (uint8_t lifetime)
Creates an ICMPv6 DAO packet and sends it to the root, advertising the current preferred parent, and with our global address as prefix.
Parameters
lifetime The DAO lifetime. Use 0 to send a No-path DAO
Definition at line 549 of file rpl-icmp6.c.
rpl_icmp6_dio_output()
void rpl_icmp6_dio_output (uip_ipaddr_t * uc_addr)
Creates an ICMPv6 DIO packet and sends it.
Can be unicast or multicast
Parameters
uc_addr The link-local address of the target host, if any. Else, a multicast DIO will be sent.
Definition at line 338 of file rpl-icmp6.c.
rpl_icmp6_dis_output()
void rpl_icmp6_dis_output (uip_ipaddr_t * addr)
Creates an ICMPv6 DIS packet and sends it.
Can be unicast or multicast.
Parameters
addr The link-local address of the target host, if any. Else, a multicast DIS will be sent.
Definition at line 156 of file rpl-icmp6.c.
rpl_icmp6_update_nbr_table()
uip_ds6_nbr_t * rpl_icmp6_update_nbr_table (uip_ipaddr_t * from, nbr_table_reason_t reason, void * data)
Updates IPv6 neighbor cache on incoming link-local RPL ICMPv6 messages.
Parameters
from The source link-local IPv6 address
reason What triggered the update (maps to RPL packet types)
data Generic pointer, used for instance to store parsed DIO data
Returns
A pointer to the new neighbor cache entry, NULL if there was no space left.
Definition at line 188 of file rpl-icmp6.c.
Referenced by rpl_process_dis().
rpl_is_addr_in_our_dag()
int rpl_is_addr_in_our_dag (const uip_ipaddr_t * addr)
Tells whether a given global IPv6 address is in our current DAG.
Parameters
addr The global IPv6 address to be tested
Returns
1 if addr is in our current DAG, 0 otherwise
Definition at line 143 of file rpl-dag.c.
rpl_is_reachable()
int rpl_is_reachable (void)
Get the RPL's best guess on if we are reachable via have downward route or not.
Returns
1 if we are reachable, 0 otherwise.
Definition at line 105 of file rpl.c.
rpl_link_callback()
void rpl_link_callback (const linkaddr_t * addr, int status, int numtx)
Called by lower layers after every packet transmission.
Parameters
addr The link-layer addrress of the packet destination
status The transmission status (see os/net/mac/mac.h)
numtx The total number of transmission attempts
Definition at line 253 of file rpl.c.
rpl_local_repair()
void rpl_local_repair (const char * str)
Triggers a RPL local repair.
Parameters
str A textual description of the cause for triggering a repair
Definition at line 206 of file rpl-dag.c.
rpl_lollipop_greater_than()
int rpl_lollipop_greater_than (int a, int b)
Greater-than function for a lollipop counter.
Parameters
a The first counter
b The second counter
Returns
1 is a>b else 0
Definition at line 57 of file rpl.c.
rpl_neighbor_count()
int rpl_neighbor_count (void)
Returns the number of nodes in the RPL neighbor table.
Returns
the neighbor count
Definition at line 127 of file rpl-neighbor.c.
rpl_neighbor_get_from_ipaddr()
rpl_nbr_t * rpl_neighbor_get_from_ipaddr (uip_ipaddr_t * addr)
Returns a neighbor from its link-local IPv6 address.
Parameters
addr The link-local IPv6 address
Returns
The neighbor if found, NULL otherwise
Definition at line 299 of file rpl-neighbor.c.
rpl_neighbor_get_from_lladdr()
rpl_nbr_t * rpl_neighbor_get_from_lladdr (uip_lladdr_t * addr)
Returns a neighbor from its link-layer address.
Parameters
addr The link-layer address
Returns
The neighbor if found, NULL otherwise
Definition at line 169 of file rpl-neighbor.c.
rpl_neighbor_get_ipaddr()
uip_ipaddr_t * rpl_neighbor_get_ipaddr (rpl_nbr_t * nbr)
Returns a neighbor's (link-local) IPv6 address.
Parameters
nbr The neighbor
Returns
The link-local IPv6 address if any, NULL otherwise
Definition at line 208 of file rpl-neighbor.c.
References rpl_neighbor_get_lladdr().
rpl_neighbor_get_link_metric()
uint16_t rpl_neighbor_get_link_metric (rpl_nbr_t * nbr)
Returns a neighbor's link metric.
Parameters
nbr The neighbor
Returns
The link metric if any, 0xffff otherwise
Definition at line 184 of file rpl-neighbor.c.
rpl_neighbor_get_link_stats()
const struct link_stats * rpl_neighbor_get_link_stats (rpl_nbr_t * nbr)
Returns a neighbor's link statistics.
Parameters
nbr The neighbor
Returns
The link_stats structure address if any, NULL otherwise
Definition at line 215 of file rpl-neighbor.c.
References rpl_neighbor_get_lladdr().
Referenced by rpl_neighbor_is_fresh().
rpl_neighbor_get_lladdr()
const linkaddr_t * rpl_neighbor_get_lladdr (rpl_nbr_t * nbr)
Returns a neighbors's link-layer address.
Parameters
nbr The neighbor
Returns
The link-layer address if any, NULL otherwise
Definition at line 202 of file rpl-neighbor.c.
Referenced by rpl_neighbor_get_ipaddr(), and rpl_neighbor_get_link_stats().
rpl_neighbor_is_acceptable_parent()
int rpl_neighbor_is_acceptable_parent (rpl_nbr_t * nbr)
Tells whether a nbr is acceptable as per the OF's definition.
Parameters
nbr The neighbor
Returns
1 if acceptable, 0 otherwise
Definition at line 175 of file rpl-neighbor.c.
rpl_neighbor_is_fresh()
int rpl_neighbor_is_fresh (rpl_nbr_t * nbr)
Tells wether we have fresh link information towards a given neighbor.
Parameters
nbr The neighbor
Returns
1 if we have fresh link information, 0 otherwise
Definition at line 222 of file rpl-neighbor.c.
References rpl_neighbor_get_link_stats().
rpl_neighbor_is_parent()
int rpl_neighbor_is_parent (rpl_nbr_t * nbr)
Tells whether a neighbor is in the parent set.
Parameters
nbr The neighbor to be tested
Returns
1 if nbr is in the parent set, 0 otherwise
Definition at line 246 of file rpl-neighbor.c.
rpl_neighbor_is_reachable()
int rpl_neighbor_is_reachable (rpl_nbr_t * nbr)
Tells wether we a given neighbor is reachable.
Parameters
nbr The neighbor
Returns
1 if the parent is reachable, 0 otherwise
Definition at line 229 of file rpl-neighbor.c.
rpl_neighbor_print_list()
void rpl_neighbor_print_list (const char * str)
Prints a summary of all RPL neighbors and their properties.
Parameters
str A descriptive text on the caller
Definition at line 79 of file rpl-neighbor.c.
rpl_neighbor_rank_via_nbr()
rpl_rank_t rpl_neighbor_rank_via_nbr (rpl_nbr_t * nbr)
Returns our rank if selecting a given parent as preferred parent.
Parameters
nbr The neighbor
Returns
The resulting rank if any, RPL_INFINITE_RANK otherwise
Definition at line 193 of file rpl-neighbor.c.
rpl_neighbor_select_best()
rpl_nbr_t * rpl_neighbor_select_best (void)
Returns the best candidate for preferred parent.
Returns
The best candidate, NULL if no usable parent is found
Definition at line 347 of file rpl-neighbor.c.
References rpl_dag_root_is_root().
rpl_neighbor_set_preferred_parent()
void rpl_neighbor_set_preferred_parent (rpl_nbr_t * nbr)
Set current RPL preferred parent and update DS6 default route accordingly.
Parameters
nbr The new preferred parent
Definition at line 252 of file rpl-neighbor.c.
rpl_ns_expire_parent()
void rpl_ns_expire_parent (const uip_ipaddr_t * child, const uip_ipaddr_t * parent)
Expires a given child-parent link.
Parameters
child The IPv6 address of the child
parent The IPv6 address of the parent
Definition at line 99 of file rpl-ns.c.
References rpl_ns_get_node().
rpl_ns_get_node()
rpl_ns_node_t* rpl_ns_get_node (const uip_ipaddr_t * addr)
Looks up for a RPL NS node from its IPv6 global address.
Parameters
addr The target address
Returns
A pointer to the node
Definition at line 73 of file rpl-ns.c.
References list_head().
Referenced by rpl_ns_expire_parent(), and rpl_ns_update_node().
rpl_ns_get_node_global_addr()
int rpl_ns_get_node_global_addr (uip_ipaddr_t * addr, rpl_ns_node_t * node)
Finds the global address of a given node.
Parameters
addr A pointer to the address to be written
node The target node
Returns
1 if success, 0 otherwise
Definition at line 191 of file rpl-ns.c.
rpl_ns_is_addr_reachable()
int rpl_ns_is_addr_reachable (const uip_ipaddr_t * addr)
Telle whether an address is reachable, i.e.
if there exists a path from the root to the node in the current RPL NS graph
Parameters
addr The target IPv6 global address
Returns
1 if the node is reachable, 0 otherwise
Definition at line 86 of file rpl-ns.c.
rpl_ns_node_head()
rpl_ns_node_t* rpl_ns_node_head (void)
Returns the head of the non-storing node list.
Returns
The head of the list
Definition at line 179 of file rpl-ns.c.
References list_head().
rpl_ns_node_next()
rpl_ns_node_t* rpl_ns_node_next (rpl_ns_node_t * item)
Returns the next element of the non-storing node list.
Parameters
item The current element in the list
Returns
The next element of the list
Definition at line 185 of file rpl-ns.c.
References list_item_next().
rpl_ns_num_nodes()
int rpl_ns_num_nodes (void)
Tells how many nodes are currently stored in the graph.
Returns
The number of nodes
Definition at line 58 of file rpl-ns.c.
rpl_ns_periodic()
void rpl_ns_periodic (unsigned seconds)
A function called periodically.
Used to age the links (decrease lifetime and expire links accordingly)
Parameters
seconds The number of seconds elapsted since last call
Definition at line 203 of file rpl-ns.c.
References list_head().
rpl_ns_update_node()
rpl_ns_node_t* rpl_ns_update_node (const uip_ipaddr_t * child, const uip_ipaddr_t * parent, uint32_t lifetime)
Updates a child-parent link.
Parameters
child The IPv6 address of the child
parent The IPv6 address of the parent
lifetime The link lifetime in seconds
Definition at line 109 of file rpl-ns.c.
References rpl_ns_get_node().
rpl_process_dao()
void rpl_process_dao (uip_ipaddr_t * from, rpl_dao_t * dao)
Processes incoming DAO.
Parameters
from The IPv6 address of the originator
dao A pointer to a parsed DAO
Definition at line 581 of file rpl-dag.c.
rpl_process_dao_ack()
void rpl_process_dao_ack (uint8_t sequence, uint8_t status)
Processes incoming DAO-ACK.
Parameters
sequence The DAO-ACK sequence number
status The DAO-ACK status (see RPL_DAO_ACK_* defines)
rpl_process_dio()
void rpl_process_dio (uip_ipaddr_t * from, rpl_dio_t * dio)
Processes incoming DIO.
Parameters
from The IPv6 address of the originator
dio A pointer to a parsed DIO
Definition at line 1437 of file rpl-dag.c.
rpl_process_dis()
void rpl_process_dis (uip_ipaddr_t * from, int is_multicast)
Processes incoming DIS.
Parameters
from The IPv6 address of the originator
is_multicast Set to 1 for multicast DIS, 0 for unicast DIS
Definition at line 567 of file rpl-dag.c.
References rpl_icmp6_update_nbr_table(), and rpl_timers_dio_reset().
rpl_process_hbh()
int rpl_process_hbh (rpl_nbr_t * sender, uint16_t sender_rank, int loop_detected, int rank_error_signaled)
Processes Hop-by-Hop (HBH) Extension Header of a packet currently being forwrded.
Parameters
sender The IPv6 address of the originator
sender_rank The rank advertised by the sender in the HBH header
loop_detected 1 if we could detect a loop while forwarding, 0 otherwise
rank_error_signaled 1 if the HBH header advertises a rank error, 0 otherwise
Returns
1 if the packet is to be forwarded, 0 if it is to be dropped
Definition at line 626 of file rpl-dag.c.
References rpl_timers_dio_reset().
rpl_reset_prefix()
void rpl_reset_prefix (rpl_prefix_t * last_prefix)
Removes current prefx.
Parameters
last_prefix The last prefix (which is to be removed)
Definition at line 119 of file rpl.c.
References ipaddr.
rpl_set_mode()
enum rpl_mode rpl_set_mode (enum rpl_mode mode)
Set the RPL mode.
Parameters
mode The new RPL mode
Return values
The previous RPL mode
Definition at line 72 of file rpl.c.
rpl_set_prefix()
int rpl_set_prefix (rpl_prefix_t * prefix)
Set prefix from an prefix data structure (from DIO)
Parameters
prefix The prefix
Returns
1 if success, 0 otherwise
Definition at line 163 of file rpl.c.
rpl_set_prefix_from_addr()
int rpl_set_prefix_from_addr (uip_ipaddr_t * addr, unsigned len, uint8_t flags)
Set prefix from an IPv6 address.
Parameters
addr The prefix
len The prefix length
flags The DIO prefix flags
Returns
1 if success, 0 otherwise
Definition at line 135 of file rpl.c.
rpl_timers_dio_reset()
void rpl_timers_dio_reset (const char * str)
Reset DIO Trickle timer.
Parameters
str A textual description of caused the DIO timer reset
Definition at line 150 of file rpl-timers.c.
References rpl_dag_ready_to_advertise().
Referenced by rpl_process_dis(), and rpl_process_hbh().
rpl_timers_schedule_state_update()
void rpl_timers_schedule_state_update (void)
Schedule a state update ASAP.
Useful to force an update from a context where updating directly would be unsafe.
Definition at line 551 of file rpl-timers.c.
uip_add32()
void uip_add32 (uint8_t * op32, uint16_t op16)
Carry out a 32-bit addition.
Because not all architectures for which uIP is intended has native 32-bit arithmetic, uIP uses an external C function for doing the required 32-bit additions in the TCP protocol processing. This function should add the two arguments and place the result in the global variable uip_acc32.
Note
The 32-bit integer pointed to by the op32 parameter and the result in the uip_acc32 variable are in network byte order (big endian).
Parameters
op32 A pointer to a 4-byte array representing a 32-bit integer in network byte order (big endian).
op16 A 16-bit integer in host byte order.
Definition at line 279 of file uip6.c.
References uip_acc32.
uip_chksum()
uint16_t uip_chksum (uint16_t * data, uint16_t len)
Calculate the Internet checksum over a buffer.
The Internet checksum is the one's complement of the one's complement sum of all 16-bit words in the buffer.
See RFC1071.
Note
This function is not called in the current version of uIP, but future versions might make use of it.
Parameters
data A pointer to the buffer over which the checksum is to be computed.
len The length of the buffer over which the checksum is to be computed.
Returns
The Internet checksum of the buffer.
Definition at line 340 of file uip6.c.
uip_ds6_get_least_lifetime_neighbor()
uip_ds6_nbr_t* uip_ds6_get_least_lifetime_neighbor (void)
This searches inside the neighbor table for the neighbor that is about to expire the next.
Returns
A reference to the neighbor about to expire the next or NULL if table is empty.
uip_htons()
uint16_t uip_htons (uint16_t val)
Convert a 16-bit quantity from host byte order to network byte order.
This function is primarily used for converting variables from host byte order to network byte order. For converting constants to network byte order, use the UIP_HTONS() macro instead.
Definition at line 2307 of file uip6.c.
uip_icmp6_echo_reply_callback_add()
void uip_icmp6_echo_reply_callback_add (struct uip_icmp6_echo_reply_notification * n, uip_icmp6_echo_reply_callback_t c)
Add a callback function for ping replies.
Parameters
n A struct uip_icmp6_echo_reply_notification that must have been allocated by the caller
c A pointer to the callback function to be called
        This function adds a callback function to the list of
        callback functions that are called when an ICMP echo
        reply (ping reply) is received. This is used when
        implementing a ping protocol: attach a callback
        function to the ping reply, then send out a ping packet
        with uip_icmp6_send().
        The caller must have statically allocated a struct
        uip_icmp6_echo_reply_notification to hold the internal
        state of the callback function.
        When a ping reply packet is received, all registered
        callback functions are called. The callback functions
        must not modify the contents of the uIP buffer.
Definition at line 352 of file uip-icmp6.c.
Referenced by shell_commands_init().
uip_icmp6_echo_reply_callback_rm()
void uip_icmp6_echo_reply_callback_rm (struct uip_icmp6_echo_reply_notification * n)
Remove a callback function for ping replies.
Parameters
n A struct uip_icmp6_echo_reply_notification that must have been previously added with uip_icmp6_echo_reply_callback_add()
        This function removes a callback function from the list of
        callback functions that are called when an ICMP echo
        reply (ping reply) is received.
Definition at line 362 of file uip-icmp6.c.
References list_remove().
uip_icmp6_error_output()
void uip_icmp6_error_output (uint8_t type, uint8_t code, uint32_t param)
Send an icmpv6 error message.
Parameters
type type of the error message
code of the error message
param 32 bit parameter of the error message, semantic depends on error
Definition at line 182 of file uip-icmp6.c.
References uip_ext_len.
uip_icmp6_input()
uint8_t uip_icmp6_input (uint8_t type, uint8_t icode)
Handle an incoming ICMPv6 message.
Parameters
type The ICMPv6 message type
icode The ICMPv6 message code
Returns
Success: UIP_ICMP6_INPUT_SUCCESS, Error: UIP_ICMP6_INPUT_ERROR
Generic handler for unknown ICMPv6 types. It will lookup for a registered function capable of handing this message type. The function must have first been registered with uip_icmp6_register_input_handler. The function is in charge of setting uip_len to 0, otherwise the uIPv6 core will attempt to send whatever remains in the UIP_IP_BUF.
A return value of UIP_ICMP6_INPUT_ERROR means that a handler could not be invoked. This is most likely because the ICMPv6 type does not have a valid handler associated with it.
UIP_ICMP6_INPUT_SUCCESS signifies that a handler was found for this ICMPv6 type and that it was invoked. It does NOT provide any indication whatsoever regarding whether the handler itself succeeded.
Definition at line 97 of file uip-icmp6.c.
uip_icmp6_register_input_handler()
void uip_icmp6_register_input_handler (uip_icmp6_input_handler_t * handler)
Register a handler which can handle a specific ICMPv6 message type.
Parameters
handler A pointer to the handler
Definition at line 114 of file uip-icmp6.c.
References list_add().
Referenced by rpl_icmp6_init(), uip_icmp6_init(), and uip_nd6_init().
uip_icmp6_send()
void uip_icmp6_send (const uip_ipaddr_t * dest, int type, int code, int payload_len)
Send an icmpv6 message.
Parameters
dest destination address of the message
type type of the message
code of the message
payload_len length of the payload
Definition at line 269 of file uip-icmp6.c.
uip_icmp6chksum()
uint16_t uip_icmp6chksum (void)
Calculate the ICMP checksum of the packet in uip_buf.
Returns
The ICMP checksum of the ICMP packet in uip_buf
Definition at line 391 of file uip6.c.
uip_init()
void uip_init (void)
uIP initialization function.
This function should be called at boot up to initilize the uIP TCP/IP stack.
Definition at line 415 of file uip6.c.
uip_ipchksum()
uint16_t uip_ipchksum (void)
Calculate the IP header checksum of the packet header in uip_buf.
The IP header checksum is the Internet checksum of the 20 bytes of the IP header.
Returns
The IP header checksum of the IP header in the uip_buf buffer.
Definition at line 347 of file uip6.c.
uip_listen()
void uip_listen (uint16_t port)
Start listening to the specified port.
Note
Since this function expects the port number in network byte order, a conversion using UIP_HTONS() or uip_htons() is necessary.
uip_listen(UIP_HTONS(80));
Parameters
port A 16-bit port number in network byte order.
Definition at line 603 of file uip6.c.
uip_nameserver_get()
uip_ipaddr_t * uip_nameserver_get (uint8_t num)
Get a Nameserver ip address given in RA.
Parameters
num The number of the nameserver to obtain, starting at 0 and going up to the pool size.
Definition at line 164 of file uip-nameserver.c.
uip_nameserver_next_expiration()
uint32_t uip_nameserver_next_expiration (void)
Get next expiration time.
The least expiration time is returned
Definition at line 191 of file uip-nameserver.c.
uip_nameserver_update()
void uip_nameserver_update (const uip_ipaddr_t * nameserver, uint32_t lifetime)
Initialize the module variables.
Insert or update a nameserver into/from the pool.
The list is kept according to the RFC6106, which indicates that new entries will replace old ones (with lower lifetime) and existing entries will update their lifetimes.
Parameters
nameserver Pointer to the nameserver ip address
lifetime Life time of the given address. Minimum is 0, which is considered to remove an entry. Maximum is 0xFFFFFFFF which is considered infinite.
Definition at line 95 of file uip-nameserver.c.
uip_nd6_ns_output()
void uip_nd6_ns_output (uip_ipaddr_t * src, uip_ipaddr_t * dest, uip_ipaddr_t * tgt)
Send a neighbor solicitation, send a Neighbor Advertisement.
Parameters
src pointer to the src of the NS if known
dest pointer to ip address to send the NS, for DAD or ADDR Resol, MUST be NULL, for NUD, must be correct unicast dest
tgt pointer to ip address to fill the target address field, must not be NULL
RFC 4861, 7.2.2 : "If the source address of the packet prompting the solicitation is the same as one of the addresses assigned to the outgoing interface, that address SHOULD be placed in the IP Source Address of the outgoing solicitation. Otherwise, any one of the addresses assigned to the interface should be used." This is why we have a src ip address as argument. If NULL, we will do src address selection, otherwise we use the argument.
we check if it is a NS for Address resolution or NUD, if yes we include a SLLAO option, otherwise no.
Referenced by uip_ds6_dad().
uip_nd6_rs_output()
void uip_nd6_rs_output (void)
Send a Router Solicitation.
src is chosen through the uip_netif_select_src function. If src is unspecified (i.e. we do not have a preferred address yet), then we do not put a SLLAO option (MUST NOT in RFC 4861). Otherwise we do.
RS message format, possible option is SLLAO, MUST NOT be included if source = unspecified SHOULD be included otherwise
Send a Router Solicitation.
The NS can be received in 3 cases (procedures):
sender is performing DAD (ip src = unspecified, no SLLAO option)
sender is performing NUD (ip dst = unicast)
sender is performing address resolution (ip dest = solicited node mcast address)
We do:
if the tgt belongs to me, reply, otherwise ignore
if i was performing DAD for the same address, two cases: – I already sent a NS, hence I win – I did not send a NS yet, hence I lose
If we need to send a NA in response (i.e. the NS was done for NUD, or address resolution, or DAD and there is a conflict), we do it in this function: set src, dst, tgt address in the three cases, then for all cases set the rest, including SLLAO
Definition at line 815 of file uip-nd6.c.
References UIP_IP_BUF.
uip_process()
void uip_process (uint8_t flag)
process the options within a hop by hop or destination option header
Return values
0 nothing to send,
1 drop pkt
2 ICMP error message to send
Definition at line 928 of file uip6.c.
uip_reass_over()
void uip_reass_over (void)
Abandon the reassembly of the current packet.
Note
We don't have a complete packet to put in the error message. We could include the first fragment but since its not mandated by any RFC, we decided not to include it as it reduces the size of the packet.
Definition at line 799 of file uip6.c.
uip_send()
void uip_send (const void * data, int len)
Send data on the current connection.
This function is used to send out a single segment of TCP data. Only applications that have been invoked by uIP for event processing can send data.
The amount of data that actually is sent out after a call to this function is determined by the maximum amount of data TCP allows. uIP will automatically crop the data so that only the appropriate amount of data is sent. The function uip_mss() can be used to query uIP for the amount of data that actually will be sent.
Note
This function does not guarantee that the sent data will arrive at the destination. If the data is lost in the network, the application will be invoked with the uip_rexmit() event being set. The application will then have to resend the data using this function.
Parameters
data A pointer to the data which is to be sent.
len The maximum amount of data bytes to be sent.
Definition at line 2319 of file uip6.c.
uip_tcpchksum()
uint16_t uip_tcpchksum (void)
Calculate the TCP checksum of the packet in uip_buf and uip_appdata.
The TCP checksum is the Internet checksum of data contents of the TCP segment, and a pseudo-header as defined in RFC793.
Returns
The TCP checksum of the TCP segment in uip_buf and pointed to by uip_appdata.
Definition at line 399 of file uip6.c.
uip_udp_new()
struct uip_udp_conn* uip_udp_new (const uip_ipaddr_t * ripaddr, uint16_t rport)
Set up a new UDP connection.
This function sets up a new UDP connection. The function will automatically allocate an unused local port for the new connection. However, another port can be chosen by using the uip_udp_bind() call, after the uip_udp_new() function has been called.
Example:
uip_ipaddr_t addr;
struct uip_udp_conn *c;
uip_ipaddr(&addr, 192,168,2,1);
c = uip_udp_new(&addr, UIP_HTONS(12345));
if(c != NULL) {
uip_udp_bind(c, UIP_HTONS(12344));
}
Parameters
ripaddr The IP address of the remote host.
rport The remote port number in network byte order.
Returns
The uip_udp_conn structure for the new connection, or NULL if no connection could be allocated.
Definition at line 545 of file uip6.c.
uip_unlisten()
void uip_unlisten (uint16_t port)
Stop listening to the specified port.
Note
Since this function expects the port number in network byte order, a conversion using UIP_HTONS() or uip_htons() is necessary.
uip_unlisten(UIP_HTONS(80));
Parameters
port A 16-bit port number in network byte order.
Definition at line 591 of file uip6.c.
Variable Documentation
uip_appdata
void* uip_appdata
Pointer to the application data in the packet buffer.
This pointer points to the application data when the application is called. If the application wishes to send data, the application may use this space to write the data into before calling uip_send().
Definition at line 175 of file uip6.c.
uip_conn
struct uip_conn* uip_conn
Pointer to the current TCP connection.
The uip_conn pointer can be used to access the current TCP connection.
Definition at line 201 of file uip6.c.
uip_ext_len
uint8_t uip_ext_len = 0
length of the extension headers read.
The length of the extension headers.
updated each time we process a header
Definition at line 136 of file uip6.c.
Referenced by rpl_ext_header_remove(), rpl_ext_header_srh_get_next_hop(), rpl_ext_header_srh_update(), and uip_icmp6_error_output().
uip_len
uint16_t uip_len
The length of the packet in the uip_buf buffer.
The global variable uip_len holds the length of the packet in the uip_buf buffer.
When the network device driver calls the uIP input function, uip_len should be set to the length of the packet in the uip_buf buffer.
When sending packets, the device driver should use the contents of the uip_len variable to determine the length of the outgoing packet.
Definition at line 186 of file uip6.c.
uip_next_hdr
uint8_t* uip_next_hdr
Type of the next header in IPv6 header or extension headers.
Can be the next header field in the IPv6 header or in an extension header. When doing fragment reassembly, we must change the value of the next header field in the header before the fragmentation header, hence we need a pointer to this field.
Definition at line 129 of file uip6.c.
Referenced by rpl_ext_header_remove(), rpl_ext_header_srh_get_next_hop(), and rpl_ext_header_srh_update().