Contiki-NG: cc2538 Clock
cc2538 Clock
The TI cc2538 System-on-Chip
Implementation of the clock module for the cc2538.
Files
file clock.c
Clock driver implementation for the TI cc2538.
Functions
void clock_init (void)
Arch-specific implementation of clock_init for the cc2538.
CCIF clock_time_t clock_time (void)
Get the current clock time.
void clock_set_seconds (unsigned long sec)
Set the value of the platform seconds.
CCIF unsigned long clock_seconds (void)
Get the current value of the platform seconds.
void clock_wait (clock_time_t i)
Wait for a given number of ticks.
void clock_delay_usec (uint16_t dt)
Delay a given number of microseconds.
void clock_delay (unsigned int i)
Obsolete delay function but we implement it here since some code still uses it.
static void update_ticks (void)
Update the software clock ticks and seconds.
void clock_adjust (void)
Adjust the clock following missed SysTick ISRs.
void clock_isr (void)
The clock Interrupt Service Routine.
Detailed Description
Implementation of the clock module for the cc2538.
To implement the clock functionality, we use the SysTick peripheral on the cortex-M3. We run the system clock at a configurable speed and set the SysTick to give us 128 interrupts / sec. However, the Sleep Timer counter value is used for the number of elapsed ticks in order to avoid a significant time drift caused by PM1/2. Contrary to the Sleep Timer, the SysTick peripheral is indeed frozen during PM1/2, so adjusting upon wake-up a tick counter based on this peripheral would hardly be accurate.
Function Documentation
void clock_adjust (void)
Adjust the clock following missed SysTick ISRs.
This function is useful when coming out of PM1/2, during which the system clock is stopped. We adjust the clock counters like after any SysTick ISR.
Note
This function is only meant to be used by lpm_exit(). Applications should really avoid calling this
Definition at line 224 of file clock.c.
References SysTick, SysTick_CTRL_ENABLE_Msk, and update_ticks().
void clock_delay_usec (uint16_t dt)
Delay a given number of microseconds.
Parameters
dt How many microseconds to delay.
Note
Interrupts could increase the delay by a variable amount.
Definition at line 150 of file clock.c.
Referenced by clock_delay(), i2c_init(), i2c_master_command(), mp3_wtv020sd_gpio_next(), mp3_wtv020sd_reset(), pm_get_voltage(), pm_reset_system(), and rtcc_set_autocalibration().
void clock_init (void)
Arch-specific implementation of clock_init for the cc2538.
Initialize the clock library.
We initialise the SysTick to fire 128 interrupts per second, giving us a value of 128 for CLOCK_SECOND
We also initialise GPT0:Timer A, which is used by clock_delay_usec(). We use 16-bit range (individual), count-down, one-shot, no interrupts. The prescaler is computed according to the system clock in order to get 1 tick per usec.
Definition at line 93 of file clock.c.
Referenced by platform_init_stage_one(), and soc_init().
void clock_isr (void)
The clock Interrupt Service Routine.
It polls the etimer process if an etimer has expired. It also updates the software clock tick and seconds counter.
Definition at line 242 of file clock.c.
References update_ticks().
CCIF unsigned long clock_seconds (void)
Get the current value of the platform seconds.
This could be the number of seconds since startup, or since a standard epoch.
Returns
The value.
Definition at line 130 of file clock.c.
Referenced by newdata(), platform_idle(), resolv_lookup(), resolv_query(), stimer_elapsed(), stimer_expired(), stimer_remaining(), stimer_restart(), stimer_set(), and uip_nameserver_update().
void clock_set_seconds (unsigned long sec)
Set the value of the platform seconds.
Parameters
sec The value to set.
Definition at line 124 of file clock.c.
CCIF clock_time_t clock_time (void)
Get the current clock time.
This function returns the current system clock time.
Returns
The current clock time, measured in system ticks.
Definition at line 118 of file clock.c.
Referenced by button_press_handler(), clock_seconds(), clock_wait(), gpiote_event_handler(), mac_sequence_is_duplicate(), mac_sequence_register_seqno(), rpl_dag_update_state(), rpl_neighbor_print_list(), rtimer_arch_schedule(), timer_expired(), timer_remaining(), timer_restart(), and timer_set().
void clock_wait (clock_time_t t)
Wait for a given number of ticks.
Parameters
t How many ticks.
Definition at line 136 of file clock.c.
static void update_ticks (void) static
Update the software clock ticks and seconds.
This function is used to update the software tick counters whenever the system clock might have changed, which can occur upon a SysTick ISR or upon wake-up from PM1/2.
For the software clock ticks counter, the Sleep Timer counter value is used as the base tick value, and extended to a 64-bit value thanks to a detection of wraparounds.
For the seconds counter, the changes of the Sleep Timer counter value are added to the reference time, which is either the startup time or the value passed to clock_set_seconds().
This function polls the etimer process if an etimer has expired.
Definition at line 187 of file clock.c.
References etimer_pending(), etimer_request_poll(), and RTIMER_NOW.
Referenced by clock_adjust(), and clock_isr().