Contiki-NG: Threads and processes
Threads and processes
System functions
This module contains protothreads, multithreading and processes.
Modules
Contiki processes
A process in Contiki consists of a single protothread.
Contiki subprocesses
A Contiki subprocess is a "process-in-a-process".
Multi-threading library
The event driven Contiki kernel does not provide multi-threading by itself - instead, preemptive multi-threading is implemented as a library that optionally can be linked with applications.
Protothreads
Protothreads are a type of lightweight stackless threads designed for severly memory constrained systems such as deeply embedded systems or sensor network nodes.
Real-time task scheduling
The real-time module handles the scheduling and execution of real-time tasks (with predictable execution times).
Functions
void mt_init (void)
Initializes the multithreading library.
void mt_remove (void)
Uninstalls library and cleans up.
void mt_start (struct mt_thread *thread, void(*function)(void *), void *data)
Starts a multithreading thread.
void mt_exec (struct mt_thread *thread)
Execute parts of a thread.
void mt_yield (void)
Voluntarily give up the processor.
void mt_exit (void)
Exit a thread.
void mt_stop (struct mt_thread *thread)
Stop a thread.
Detailed Description
This module contains protothreads, multithreading and processes.
Function Documentation
void mt_exec (struct mt_thread * thread)
Execute parts of a thread.
This function is called by a Contiki process and runs a thread. The function does not return until the thread has yielded, or is preempted.
Note
The thread library must first be initialized with the mt_init() function.
Parameters
thread A pointer to a struct mt_thread block that must be allocated by the caller.
Definition at line 75 of file mt.c.
References mtarch_exec().
void mt_exit (void)
Exit a thread.
This function is called from within an executing thread in order to exit the thread. The function never returns.
Definition at line 97 of file mt.c.
References mtarch_yield().
Referenced by mtarch_start().
void mt_start (struct mt_thread * thread, void(*)(void *) function, void * data)
Starts a multithreading thread.
Parameters
thread Pointer to an mt_thread struct that must have been previously allocated by the caller.
function A pointer to the entry function of the thread that is to be set up.
data A pointer that will be passed to the entry function.
Definition at line 65 of file mt.c.
References mtarch_start().
void mt_stop (struct mt_thread * thread)
Stop a thread.
This function is called by a Contiki process in order to clean up a thread. The struct mt_thread block may then be discarded by the caller.
Parameters
thread A pointer to a struct mt_thread block that must be allocated by the caller.
Definition at line 105 of file mt.c.
References mtarch_stop().
void mt_yield (void)
Voluntarily give up the processor.
This function is called by a running thread in order to give up control of the CPU.
Definition at line 86 of file mt.c.
References mtarch_yield().