Contiki-NG: RPL-lite
RPL-lite
IoT networking » Network layer
RPL-lite is a lightweight implementation of RPL tailored for reliability.
Files
file rpl-conf.h
Public configuration and API declarations for ContikiRPL.
file rpl-const.h
Constants for RPL.
file rpl-dag-root.c
DAG root utility functions for RPL.
file rpl-dag-root.h
DAG root utility functions for RPL.
file rpl-dag.c
Logic for Directed Acyclic Graphs in RPL.
file rpl-dag.h
Header file for rpl-dag module.
file rpl-ext-header.c
Management of extension headers for ContikiRPL.
file rpl-ext-header.h
Header file for rpl-ext-header.
file rpl-icmp6.c
ICMP6 I/O for RPL control messages.
file rpl-icmp6.h
Header file for rpl-ext-header.
file rpl-mrhof.c
The Minimum Rank with Hysteresis Objective Function (MRHOF), RFC6719.
file rpl-nbr-policy.c
Default RPL NBR policy decides when to add a new discovered node to the nbr table from RPL.
file rpl-neighbor.c
Logic for DAG neighbors in RPL.
file rpl-neighbor.h
Header file for rpl-neighbor module.
file rpl-of0.c
An implementation of RPL's objective function 0, RFC6552.
file rpl-timers.c
RPL timer management.
file rpl-timers.h
Header file for rpl-timers module.
file rpl-types.h
RPL types and macros.
file rpl.c
ContikiRPL, an implementation of RPL: IPv6 Routing Protocol for Low-Power and Lossy Networks (IETF RFC 6550)
Data Structures
struct rpl_metric_object_energy
Structure for RPL energy metric.
struct rpl_metric_container
Logical representation of a DAG Metric Container.
struct rpl_prefix
RPL prefix information.
struct rpl_nbr
All information related to a RPL neighbor.
struct rpl_of
API for RPL objective functions (OF)
struct rpl_dag
RPL DAG structure.
struct rpl_instance
RPL instance structure.
Macros
#define uip_create_linklocal_rplnodes_mcast(addr) uip_ip6addr((addr), 0xff02, 0, 0, 0, 0, 0, 0, 0x001a)
Set IP address addr to the link-local, all-rpl-nodes multicast address.
#define uip_is_addr_linklocal_rplnodes_mcast(addr)
Is IPv6 address addr the link-local, all-RPL-nodes multicast address?
#define RPL_LIFETIME(lifetime)
Compute lifetime, accounting for the lifetime unit.
#define ROOT_RANK curr_instance.min_hoprankinc
Rank of a root node.
#define DAG_RANK(fixpt_rank) ((fixpt_rank) / curr_instance.min_hoprankinc)
Return DAG RANK as per RFC 6550 (rank divided by min_hoprankinc)
Enumerations
Functions
void rpl_dag_root_set_prefix (uip_ipaddr_t *prefix, uip_ipaddr_t *iid)
Set a prefix in case the node is later set as dag root.
int rpl_dag_root_start (void)
Set the node as root and start a DAG.
int rpl_dag_root_is_root (void)
Tells whether we are DAG root or not.
const char * rpl_dag_state_to_str (enum rpl_dag_state state)
Returns a textual description of the current DAG state.
int rpl_dag_get_root_ipaddr (uip_ipaddr_t *ipaddr)
Returns the IPv6 address of the RPL DAG root, if any.
void rpl_dag_leave (void)
Leaves the current DAG.
void rpl_dag_poison_and_leave (void)
Start poisoning and leave the DAG after a delay.
void rpl_dag_periodic (unsigned seconds)
A function called periodically.
int rpl_is_addr_in_our_dag (const uip_ipaddr_t *addr)
Tells whether a given global IPv6 address is in our current DAG.
rpl_instance_t * rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
rpl_dag_t * rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
void rpl_refresh_routes (const char *str)
Triggers a route fresh via DTSN increment.
void rpl_global_repair (const char *str)
Triggers a RPL global repair.
void rpl_local_repair (const char *str)
Triggers a RPL local repair.
int rpl_dag_ready_to_advertise (void)
Tells whether RPL is ready to advertise the DAG.
void rpl_dag_update_state (void)
Updates RPL internal state: selects preferred parent, updates rank & metreic container, triggers control traffic accordingly and updates uIP6 internal state.
void rpl_process_dio (uip_ipaddr_t *from, rpl_dio_t *dio)
Processes incoming DIO.
void rpl_process_dis (uip_ipaddr_t *from, int is_multicast)
Processes incoming DIS.
void rpl_process_dao (uip_ipaddr_t *from, rpl_dao_t *dao)
Processes incoming DAO.
int rpl_process_hbh (rpl_nbr_t *sender, uint16_t sender_rank, int loop_detected, int rank_error_signaled)
Processes Hop-by-Hop (HBH) Extension Header of a packet currently being forwrded.
void rpl_dag_init_root (uint8_t instance_id, uip_ipaddr_t *dag_id, uip_ipaddr_t *prefix, unsigned prefix_len, uint8_t flags)
Initializes DAG internal structure for a root node.
void rpl_dag_init (void)
Initializes rpl-dag module.
void rpl_process_dao_ack (uint8_t sequence, uint8_t status)
Processes incoming DAO-ACK.
int rpl_ext_header_srh_get_next_hop (uip_ipaddr_t *ipaddr)
Look for next hop from SRH of current uIP packet.
int rpl_ext_header_srh_update (void)
Process and update SRH in-place, i.e.
int rpl_ext_header_hbh_update (int uip_ext_opt_offset)
Process and update the RPL hop-by-hop extension headers of the current uIP packet.
int rpl_ext_header_update (void)
Adds/updates all RPL extension headers to current uIP packet.
void rpl_ext_header_remove (void)
Removes all RPL extension headers.
uip_ds6_nbr_t * rpl_icmp6_update_nbr_table (uip_ipaddr_t *from, nbr_table_reason_t reason, void *data)
Updates IPv6 neighbor cache on incoming link-local RPL ICMPv6 messages.
void rpl_icmp6_dis_output (uip_ipaddr_t *addr)
Creates an ICMPv6 DIS packet and sends it.
void rpl_icmp6_dio_output (uip_ipaddr_t *uc_addr)
Creates an ICMPv6 DIO packet and sends it.
void rpl_icmp6_dao_output (uint8_t lifetime)
Creates an ICMPv6 DAO packet and sends it to the root, advertising the current preferred parent, and with our global address as prefix.
void rpl_icmp6_init (void)
Initializes rpl-icmp6 module, registers ICMPv6 handlers for all RPL ICMPv6 messages: DIO, DIS, DAO and DAO-ACK.
void rpl_icmp6_dao_ack_output (uip_ipaddr_t *dest, uint8_t sequence, uint8_t status)
Creates an ICMPv6 DAO-ACK packet and sends it to the originator of the ACK.
void rpl_neighbor_print_list (const char *str)
Prints a summary of all RPL neighbors and their properties.
int rpl_neighbor_count (void)
Returns the number of nodes in the RPL neighbor table.
rpl_nbr_t * rpl_neighbor_get_from_lladdr (uip_lladdr_t *addr)
Returns a neighbor from its link-layer address.
int rpl_neighbor_is_acceptable_parent (rpl_nbr_t *nbr)
Tells whether a nbr is acceptable as per the OF's definition.
uint16_t rpl_neighbor_get_link_metric (rpl_nbr_t *nbr)
Returns a neighbor's link metric.
rpl_rank_t rpl_neighbor_rank_via_nbr (rpl_nbr_t *nbr)
Returns our rank if selecting a given parent as preferred parent.
const linkaddr_t * rpl_neighbor_get_lladdr (rpl_nbr_t *nbr)
Returns a neighbors's link-layer address.
uip_ipaddr_t * rpl_neighbor_get_ipaddr (rpl_nbr_t *nbr)
Returns a neighbor's (link-local) IPv6 address.
const struct link_stats * rpl_neighbor_get_link_stats (rpl_nbr_t *nbr)
Returns a neighbor's link statistics.
int rpl_neighbor_is_fresh (rpl_nbr_t *nbr)
Tells wether we have fresh link information towards a given neighbor.
int rpl_neighbor_is_reachable (rpl_nbr_t *nbr)
Tells wether we a given neighbor is reachable.
int rpl_neighbor_is_parent (rpl_nbr_t *nbr)
Tells whether a neighbor is in the parent set.
void rpl_neighbor_set_preferred_parent (rpl_nbr_t *nbr)
Set current RPL preferred parent and update DS6 default route accordingly.
void rpl_neighbor_remove_all (void)
Empty the RPL neighbor table.
rpl_nbr_t * rpl_neighbor_get_from_ipaddr (uip_ipaddr_t *addr)
Returns a neighbor from its link-local IPv6 address.
rpl_nbr_t * rpl_neighbor_select_best (void)
Returns the best candidate for preferred parent.
void rpl_neighbor_init (void)
Initialize rpl-dag-neighbor module.
void rpl_timers_schedule_periodic_dis (void)
Schedule periodic DIS with a random delay based on RPL_DIS_INTERVAL, until we join a DAG.
void rpl_timers_dio_reset (const char *str)
Reset DIO Trickle timer.
void rpl_timers_schedule_unicast_dio (rpl_nbr_t *target)
Schedule unicast DIO with no delay.
void rpl_timers_schedule_dao (void)
Schedule a DAO with random delay based on RPL_DAO_DELAY.
void rpl_timers_unschedule_leaving (void)
Cancel scheduled leaving if any.
void rpl_timers_schedule_leaving (void)
Schedule leaving after RPL_DELAY_BEFORE_LEAVING.
void rpl_timers_init (void)
Initialize rpl-timers module.
void rpl_timers_stop_dag_timers (void)
Stop all timers related to the DAG.
void rpl_timers_unschedule_state_update (void)
Cancelled any scheduled state update.
void rpl_timers_schedule_state_update (void)
Schedule a state update ASAP.
void rpl_timers_schedule_dao_ack (uip_ipaddr_t *target, uint16_t sequence)
Schedule a DAO-ACK with no delay.
void rpl_schedule_probing (void)
Schedule probing with delay RPL_PROBING_DELAY_FUNC()
int rpl_lollipop_greater_than (int a, int b)
Greater-than function for a lollipop counter.
const uip_ipaddr_t * rpl_get_global_address (void)
Get one of the node's global addresses.
void rpl_link_callback (const linkaddr_t *addr, int status, int numtx)
Called by lower layers after every packet transmission.
int rpl_has_joined (void)
Tells whether the node has joined a network or not.
int rpl_is_reachable (void)
Get the RPL's best guess on if we are reachable via have downward route or not.
void rpl_reset_prefix (rpl_prefix_t *last_prefix)
Removes current prefx.
int rpl_set_prefix_from_addr (uip_ipaddr_t *addr, unsigned len, uint8_t flags)
Set prefix from an IPv6 address.
int rpl_set_prefix (rpl_prefix_t *prefix)
Set prefix from an prefix data structure (from DIO)
Detailed Description
RPL-lite is a lightweight implementation of RPL tailored for reliability.
Supports only non-storing mode, one instance and one DAG.
Macro Definition Documentation
#define ROOT_RANK curr_instance.min_hoprankinc
Rank of a root node.
Definition at line 78 of file rpl-types.h.
Referenced by rpl_dag_init(), rpl_dag_init_root(), rpl_dag_root_is_root(), rpl_dag_update_state(), rpl_ext_header_update(), rpl_get_default_instance(), rpl_icmp6_update_nbr_table(), rpl_neighbor_print_list(), rpl_process_dio(), and rpl_set_mode().
#define uip_create_linklocal_rplnodes_mcast (addr) uip_ip6addr((addr), 0xff02, 0, 0, 0, 0, 0, 0, 0x001a)
Set IP address addr to the link-local, all-rpl-nodes multicast address.
Definition at line 54 of file rpl-types.h.
Referenced by rpl_icmp6_update_nbr_table(), rpl_link_callback(), and rpl_set_prefix().
Function Documentation
int rpl_dag_get_root_ipaddr (uip_ipaddr_t * ipaddr)
Returns the IPv6 address of the RPL DAG root, if any.
Parameters
ipaddr A pointer where to copy the IP address of the DAG root
Returns
1 if the root address was copied, 0 otherwise
Definition at line 83 of file rpl-dag.c.
References uip_ipaddr_copy.
Referenced by rpl_set_prefix().
void rpl_dag_init_root (uint8_t instance_id, uip_ipaddr_t * dag_id, uip_ipaddr_t * prefix, unsigned prefix_len, uint8_t flags)
Initializes DAG internal structure for a root node.
Parameters
instance_id The instance ID
dag_id The DAG ID
prefix The prefix
prefix_len The prefix length
flags The prefix flags (from DIO)
Definition at line 692 of file rpl-dag.c.
References ROOT_RANK, rpl_dag_leave(), RPL_LIFETIME, and rpl_timers_dio_reset().
Referenced by rpl_dag_root_start().
void rpl_dag_leave (void)
Leaves the current DAG.
Definition at line 93 of file rpl-dag.c.
References rpl_dag_root_is_root(), rpl_icmp6_dao_output(), rpl_neighbor_remove_all(), rpl_reset_prefix(), rpl_timers_stop_dag_timers(), and uip_sr_free_all().
Referenced by rpl_dag_init_root(), and rpl_timers_schedule_dao().
void rpl_dag_periodic (unsigned seconds)
A function called periodically.
Used to age the DAG (decrease lifetime and expire DAG accordingly)
Parameters
seconds The number of seconds elapsted since last call
Definition at line 132 of file rpl-dag.c.
References rpl_icmp6_dis_output(), RPL_LIFETIME, rpl_neighbor_get_ipaddr(), and rpl_timers_schedule_state_update().
Referenced by rpl_timers_init().
void rpl_dag_poison_and_leave (void)
Start poisoning and leave the DAG after a delay.
Definition at line 125 of file rpl-dag.c.
References rpl_timers_schedule_state_update().
Referenced by rpl_set_prefix().
int rpl_dag_ready_to_advertise (void)
Tells whether RPL is ready to advertise the DAG.
Returns
1 is ready, 0 otherwise
Definition at line 247 of file rpl-dag.c.
Referenced by rpl_timers_dio_reset().
int rpl_dag_root_is_root (void)
Tells whether we are DAG root or not.
Returns
1 if we are dag root, 0 otherwise
Definition at line 131 of file rpl-dag-root.c.
References ROOT_RANK, and rpl_get_default_instance().
Referenced by rpl_dag_leave(), rpl_dag_update_state(), rpl_ext_header_update(), rpl_global_repair(), rpl_has_downward_route(), rpl_link_callback(), rpl_local_repair(), rpl_neighbor_select_best(), rpl_process_dio(), rpl_refresh_routes(), rpl_set_prefix(), rpl_timers_dio_reset(), and rpl_timers_schedule_periodic_dis().
void rpl_dag_root_set_prefix (uip_ipaddr_t * prefix, uip_ipaddr_t * iid)
Set a prefix in case the node is later set as dag root.
Parameters
prefix The prefix. If NULL, UIP_DS6_DEFAULT_PREFIX is used instead
iid The IID. If NULL, it will be built from uip_ds6_set_addr_iid.
Definition at line 86 of file rpl-dag-root.c.
Referenced by rpl_dag_root_start(), rpl_link_callback(), and rpl_set_prefix().
int rpl_dag_root_start (void)
Set the node as root and start a DAG.
Returns
0 in case of success, -1 otherwise
Definition at line 97 of file rpl-dag-root.c.
References ipaddr, rpl_dag_init_root(), rpl_dag_root_set_prefix(), rpl_dag_update_state(), rpl_get_any_dag(), rpl_get_global_address(), uip_ds6_if, uip_ip6addr, and uip_is_addr_linklocal.
Referenced by rpl_link_callback(), and rpl_set_prefix().
const char * rpl_dag_state_to_str (enum rpl_dag_state state)
Returns a textual description of the current DAG state.
Parameters
state The DAG state
Returns
The description string
Definition at line 66 of file rpl-dag.c.
Referenced by rpl_neighbor_print_list().
int rpl_ext_header_hbh_update (int uip_ext_opt_offset)
Process and update the RPL hop-by-hop extension headers of the current uIP packet.
Parameters
uip_ext_opt_offset The offset within the uIP packet where extension headers start
Returns
1 in case the packet is valid and to be processed further, 0 in case the packet must be dropped.
Definition at line 362 of file rpl-ext-header.c.
References rpl_process_hbh(), UIP_BUFSIZE, uip_ext_len, uip_ext_opt_offset, UIP_HTONS, UIP_IP_BUF, uip_len, UIP_LLH_LEN, and UIP_PROTO_HBHO.
int rpl_ext_header_srh_get_next_hop (uip_ipaddr_t * ipaddr)
Look for next hop from SRH of current uIP packet.
Parameters
ipaddr A pointer to the address where to store the next hop.
Returns
1 if a next hop was found, 0 otherwise
Definition at line 69 of file rpl-ext-header.c.
References rpl_is_addr_in_our_dag(), uip_ext_len, UIP_IP_BUF, uip_ipaddr_copy, uip_next_hdr, UIP_PROTO_HBHO, and uip_sr_get_node().
int rpl_ext_header_srh_update (void)
Process and update SRH in-place, i.e.
internal address swapping as per RFC6554
Returns
1 if SRH found, 0 otherwise
Definition at line 124 of file rpl-ext-header.c.
References routing_driver::get_sr_node_ipaddr, rpl_is_addr_in_our_dag(), uip_buf, UIP_BUFSIZE, uip_ext_len, uip_ext_opt_offset, UIP_HTONS, UIP_IP_BUF, uip_ipaddr_copy, uip_l2_l3_hdr_len, uip_len, UIP_LLH_LEN, uip_next_hdr, UIP_PROTO_HBHO, uip_sr_get_node(), and uip_sr_is_addr_reachable().
int rpl_ext_header_update (void)
Adds/updates all RPL extension headers to current uIP packet.
Returns
1 in case of success, 0 otherwise
Definition at line 504 of file rpl-ext-header.c.
References ROOT_RANK, rpl_dag_root_is_root(), rpl_ext_header_remove(), uip_ds6_if, UIP_IP_BUF, uip_is_addr_linklocal, and uip_is_addr_mcast.
rpl_dag_t* rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
Returns
A pointer to the only supported DAG
Definition at line 165 of file rpl-dag.c.
References ctimer_stop(), DAG_RANK, rpl_icmp6_update_nbr_table(), and rpl_local_repair().
rpl_instance_t* rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
Returns
A pointer to the only supported instance
Definition at line 159 of file rpl-dag.c.
References ctimer_stop(), nbr, ROOT_RANK, and rpl_schedule_probing().
const uip_ipaddr_t* rpl_get_global_address (void)
Get one of the node's global addresses.
Returns
A (constant) pointer to the global IPv6 address found. The pointer directs to the internals of DS6, should only be used in the current function's local scope
Definition at line 70 of file rpl.c.
References ipaddr, uip_ds6_if, and uip_is_addr_linklocal.
Referenced by rpl_dag_root_start(), rpl_icmp6_dao_output(), and rpl_neighbor_print_list().
void rpl_global_repair (const char * str)
Triggers a RPL global repair.
Parameters
str A textual description of the cause for triggering a repair
Definition at line 198 of file rpl-dag.c.
References rpl_dag_root_is_root(), rpl_local_repair(), rpl_neighbor_print_list(), and rpl_timers_stop_dag_timers().
Referenced by rpl_dag_update_state(), and rpl_set_prefix().
int rpl_has_joined (void)
Tells whether the node has joined a network or not.
Return values
1 if we have joined a network, 0 if not.
Definition at line 112 of file rpl.c.
References rpl_get_any_dag().
Referenced by rpl_link_callback(), and rpl_set_prefix().
void rpl_icmp6_dao_ack_output (uip_ipaddr_t * dest, uint8_t sequence, uint8_t status)
Creates an ICMPv6 DAO-ACK packet and sends it to the originator of the ACK.
Parameters
dest The DAO-ACK destination (was source of the DAO)
sequence The sequence number of the DAO being ACKed
status The status of the DAO-ACK (see RPL_DAO_ACK_* defines)
Referenced by rpl_icmp6_dao_output(), and rpl_timers_schedule_dao().
void rpl_icmp6_dao_output (uint8_t lifetime)
Creates an ICMPv6 DAO packet and sends it to the root, advertising the current preferred parent, and with our global address as prefix.
Parameters
lifetime The DAO lifetime. Use 0 to send a No-path DAO
Definition at line 547 of file rpl-icmp6.c.
References ICMP6_RPL, rpl_dag_update_state(), rpl_get_global_address(), rpl_icmp6_dao_ack_output(), rpl_neighbor_get_ipaddr(), rpl_process_dao_ack(), uip_icmp6_send(), and UIP_IP_BUF.
Referenced by rpl_dag_leave(), and rpl_timers_schedule_dao().
void rpl_icmp6_dio_output (uip_ipaddr_t * uc_addr)
Creates an ICMPv6 DIO packet and sends it.
Can be unicast or multicast
Parameters
uc_addr The link-local address of the target host, if any. Else, a multicast DIO will be sent.
Definition at line 336 of file rpl-icmp6.c.
References addr, ICMP6_RPL, rpl_dag_update_state(), rpl_process_dao(), uip_icmp6_send(), UIP_IP_BUF, uip_ipaddr_copy, and uip_len.
Referenced by rpl_process_dis(), rpl_timers_dio_reset(), and rpl_timers_schedule_unicast_dio().
void rpl_icmp6_dis_output (uip_ipaddr_t * addr)
Creates an ICMPv6 DIS packet and sends it.
Can be unicast or multicast.
Parameters
addr The link-local address of the target host, if any. Else, a multicast DIS will be sent.
Definition at line 154 of file rpl-icmp6.c.
References ICMP6_RPL, rpl_dag_update_state(), rpl_process_dio(), uip_icmp6_send(), UIP_IP_BUF, uip_ipaddr_copy, uip_is_addr_mcast, and uip_len.
Referenced by rpl_dag_periodic(), and rpl_timers_schedule_periodic_dis().
uip_ds6_nbr_t* rpl_icmp6_update_nbr_table (uip_ipaddr_t * from, nbr_table_reason_t reason, void * data)
Updates IPv6 neighbor cache on incoming link-local RPL ICMPv6 messages.
Parameters
from The source link-local IPv6 address
reason What triggered the update (maps to RPL packet types)
data Generic pointer, used for instance to store parsed DIO data
Returns
A pointer to the new neighbor cache entry, NULL if there was no space left.
Definition at line 116 of file rpl-icmp6.c.
References addr, ctimer_set(), ctimer_stop(), uip_mcast6_route::dag, DAG_RANK, ICMP6_RPL, uip_mcast6_route::lifetime, nbr, random_rand(), ROOT_RANK, rpl_get_mode(), rpl_icmp6_update_nbr_table(), RPL_LIFETIME, rpl_local_repair(), rpl_process_dio(), rpl_process_dis(), uip_create_linklocal_rplnodes_mcast, uip_ds6_nbr_add(), uip_icmp6_register_input_handler(), uip_icmp6_send(), UIP_IP_BUF, uip_ipaddr_copy, uip_is_addr_mcast, uip_is_addr_mcast_global, uip_len, uip_mcast6_route_add(), uip_sr_expire_parent(), and uip_sr_update_node().
int rpl_is_addr_in_our_dag (const uip_ipaddr_t * addr)
Tells whether a given global IPv6 address is in our current DAG.
Parameters
addr The global IPv6 address to be tested
Returns
1 if addr is in our current DAG, 0 otherwise
Definition at line 152 of file rpl-dag.c.
Referenced by rpl_ext_header_srh_get_next_hop(), and rpl_ext_header_srh_update().
int rpl_is_reachable (void)
Get the RPL's best guess on if we are reachable via have downward route or not.
Returns
1 if we are reachable, 0 otherwise.
Definition at line 118 of file rpl.c.
References ipaddr, uip_ds6_set_addr_iid(), and uip_lladdr.
Referenced by rpl_set_prefix().
void rpl_link_callback (const linkaddr_t * addr, int status, int numtx)
Called by lower layers after every packet transmission.
Parameters
addr The link-layer addrress of the packet destination
status The transmission status (see os/net/mac/mac.h)
numtx The total number of transmission attempts
Definition at line 96 of file rpl.c.
References addr, routing_driver::drop_route, routing_driver::get_root_ipaddr, routing_driver::get_sr_node_ipaddr, routing_driver::global_repair, routing_driver::init, ipaddr, routing_driver::leave_network, routing_driver::local_repair, nbr, rpl_dag_init(), rpl_dag_root_is_root(), rpl_dag_root_set_prefix(), rpl_dag_root_start(), rpl_ext_header_hbh_update(), rpl_ext_header_remove(), rpl_ext_header_srh_get_next_hop(), rpl_ext_header_srh_update(), rpl_ext_header_update(), rpl_get_any_dag(), rpl_has_downward_route(), rpl_has_joined(), rpl_link_callback(), rpl_local_repair(), rpl_neighbor_get_from_lladdr(), rpl_neighbor_get_link_metric(), rpl_timers_schedule_state_update(), uip_create_linklocal_rplnodes_mcast, uip_ds6_set_addr_iid(), uip_ip6addr, uip_ipaddr_copy, and uip_sr_init().
void rpl_local_repair (const char * str)
Triggers a RPL local repair.
Parameters
str A textual description of the cause for triggering a repair
Definition at line 232 of file rpl-dag.c.
References rpl_dag_root_is_root(), rpl_neighbor_remove_all(), rpl_timers_dio_reset(), and rpl_timers_schedule_state_update().
Referenced by rpl_get_any_dag(), rpl_global_repair(), rpl_icmp6_update_nbr_table(), rpl_link_callback(), rpl_set_prefix(), and rpl_timers_schedule_dao().
int rpl_lollipop_greater_than (int a, int b)
Greater-than function for a lollipop counter.
Parameters
a The first counter
b The second counter
Returns
1 is a>b else 0
Definition at line 56 of file rpl.c.
Referenced by rpl_dag_update_state(), rpl_process_dao(), and rpl_timers_schedule_dao().
int rpl_neighbor_count (void)
Returns the number of nodes in the RPL neighbor table.
Returns
the neighbor count
Definition at line 137 of file rpl-neighbor.c.
References nbr, rpl_neighbor_get_lladdr(), and rpl_timers_schedule_state_update().
Referenced by rpl_neighbor_print_list().
rpl_nbr_t * rpl_neighbor_get_from_ipaddr (uip_ipaddr_t * addr)
Returns a neighbor from its link-local IPv6 address.
Parameters
addr The link-local IPv6 address
Returns
The neighbor if found, NULL otherwise
Definition at line 309 of file rpl-neighbor.c.
References nbr, and rpl_neighbor_is_fresh().
Referenced by rpl_dag_update_state().
rpl_nbr_t * rpl_neighbor_get_from_lladdr (uip_lladdr_t * addr)
Returns a neighbor from its link-layer address.
Parameters
addr The link-layer address
Returns
The neighbor if found, NULL otherwise
Definition at line 179 of file rpl-neighbor.c.
Referenced by rpl_link_callback().
uip_ipaddr_t * rpl_neighbor_get_ipaddr (rpl_nbr_t * nbr)
Returns a neighbor's (link-local) IPv6 address.
Parameters
nbr The neighbor
Returns
The link-local IPv6 address if any, NULL otherwise
Definition at line 218 of file rpl-neighbor.c.
References rpl_neighbor_get_lladdr().
Referenced by rpl_dag_periodic(), rpl_dag_update_state(), rpl_icmp6_dao_output(), rpl_neighbor_print_list(), rpl_neighbor_select_best(), rpl_neighbor_set_preferred_parent(), rpl_timers_schedule_dao(), and rpl_timers_schedule_unicast_dio().
uint16_t rpl_neighbor_get_link_metric (rpl_nbr_t * nbr)
Returns a neighbor's link metric.
Parameters
nbr The neighbor
Returns
The link metric if any, 0xffff otherwise
Definition at line 194 of file rpl-neighbor.c.
Referenced by rpl_link_callback(), and rpl_neighbor_print_list().
const struct link_stats * rpl_neighbor_get_link_stats (rpl_nbr_t * nbr)
Returns a neighbor's link statistics.
Parameters
nbr The neighbor
Returns
The link_stats structure address if any, NULL otherwise
Definition at line 225 of file rpl-neighbor.c.
References rpl_neighbor_get_lladdr().
Referenced by rpl_neighbor_is_fresh(), rpl_neighbor_print_list(), and rpl_timers_schedule_dao().
const linkaddr_t * rpl_neighbor_get_lladdr (rpl_nbr_t * nbr)
Returns a neighbors's link-layer address.
Parameters
nbr The neighbor
Returns
The link-layer address if any, NULL otherwise
Definition at line 212 of file rpl-neighbor.c.
Referenced by rpl_neighbor_count(), rpl_neighbor_get_ipaddr(), and rpl_neighbor_get_link_stats().
int rpl_neighbor_is_acceptable_parent (rpl_nbr_t * nbr)
Tells whether a nbr is acceptable as per the OF's definition.
Parameters
nbr The neighbor
Returns
1 if acceptable, 0 otherwise
Definition at line 185 of file rpl-neighbor.c.
Referenced by rpl_neighbor_print_list().
int rpl_neighbor_is_fresh (rpl_nbr_t * nbr)
Tells wether we have fresh link information towards a given neighbor.
Parameters
nbr The neighbor
Returns
1 if we have fresh link information, 0 otherwise
Definition at line 232 of file rpl-neighbor.c.
References rpl_neighbor_get_link_stats().
Referenced by rpl_neighbor_get_from_ipaddr(), rpl_neighbor_is_reachable(), rpl_neighbor_select_best(), and rpl_timers_schedule_dao().
int rpl_neighbor_is_parent (rpl_nbr_t * nbr)
Tells whether a neighbor is in the parent set.
Parameters
nbr The neighbor to be tested
Returns
1 if nbr is in the parent set, 0 otherwise
Definition at line 256 of file rpl-neighbor.c.
int rpl_neighbor_is_reachable (rpl_nbr_t * nbr)
Tells wether we a given neighbor is reachable.
Parameters
nbr The neighbor
Returns
1 if the parent is reachable, 0 otherwise
Definition at line 239 of file rpl-neighbor.c.
References rpl_neighbor_is_fresh().
void rpl_neighbor_print_list (const char * str)
Prints a summary of all RPL neighbors and their properties.
Parameters
str A descriptive text on the caller
Definition at line 89 of file rpl-neighbor.c.
References CLOCK_SECOND, clock_time(), nbr, ROOT_RANK, rpl_dag_state_to_str(), rpl_get_global_address(), rpl_neighbor_count(), rpl_neighbor_get_ipaddr(), rpl_neighbor_get_link_metric(), rpl_neighbor_get_link_stats(), rpl_neighbor_is_acceptable_parent(), and rpl_neighbor_rank_via_nbr().
Referenced by rpl_dag_update_state(), rpl_global_repair(), rpl_refresh_routes(), and rpl_timers_init().
rpl_rank_t rpl_neighbor_rank_via_nbr (rpl_nbr_t * nbr)
Returns our rank if selecting a given parent as preferred parent.
Parameters
nbr The neighbor
Returns
The resulting rank if any, RPL_INFINITE_RANK otherwise
Definition at line 203 of file rpl-neighbor.c.
Referenced by rpl_dag_update_state(), rpl_neighbor_print_list(), and rpl_timers_schedule_dao().
rpl_nbr_t * rpl_neighbor_select_best (void)
Returns the best candidate for preferred parent.
Returns
The best candidate, NULL if no usable parent is found
Definition at line 357 of file rpl-neighbor.c.
References rpl_dag_root_is_root(), rpl_neighbor_get_ipaddr(), rpl_neighbor_is_fresh(), and rpl_schedule_probing().
Referenced by rpl_dag_update_state().
void rpl_neighbor_set_preferred_parent (rpl_nbr_t * nbr)
Set current RPL preferred parent and update DS6 default route accordingly.
Parameters
nbr The new preferred parent
Definition at line 262 of file rpl-neighbor.c.
References nbr, and rpl_neighbor_get_ipaddr().
Referenced by rpl_dag_update_state().
void rpl_process_dao (uip_ipaddr_t * from, rpl_dao_t * dao)
Processes incoming DAO.
Parameters
from The IPv6 address of the originator
dao A pointer to a parsed DAO
Definition at line 614 of file rpl-dag.c.
References RPL_LIFETIME, rpl_lollipop_greater_than(), rpl_process_dao_ack(), rpl_timers_dio_reset(), rpl_timers_schedule_dao_ack(), uip_sr_expire_parent(), and uip_sr_update_node().
Referenced by rpl_icmp6_dio_output().
void rpl_process_dao_ack (uint8_t sequence, uint8_t status)
Processes incoming DAO-ACK.
Parameters
sequence The DAO-ACK sequence number
status The DAO-ACK status (see RPL_DAO_ACK_* defines)
Referenced by rpl_icmp6_dao_output(), and rpl_process_dao().
void rpl_process_dio (uip_ipaddr_t * from, rpl_dio_t * dio)
Processes incoming DIO.
Parameters
from The IPv6 address of the originator
dio A pointer to a parsed DIO
Definition at line 581 of file rpl-dag.c.
References ROOT_RANK, rpl_dag_root_is_root(), rpl_dag_update_state(), and RPL_LIFETIME.
void rpl_process_dis (uip_ipaddr_t * from, int is_multicast)
Processes incoming DIS.
Parameters
from The IPv6 address of the originator
is_multicast Set to 1 for multicast DIS, 0 for unicast DIS
Definition at line 600 of file rpl-dag.c.
References rpl_icmp6_dio_output(), rpl_icmp6_update_nbr_table(), and rpl_timers_dio_reset().
Referenced by rpl_icmp6_update_nbr_table().
int rpl_process_hbh (rpl_nbr_t * sender, uint16_t sender_rank, int loop_detected, int rank_error_signaled)
Processes Hop-by-Hop (HBH) Extension Header of a packet currently being forwrded.
Parameters
sender The IPv6 address of the originator
sender_rank The rank advertised by the sender in the HBH header
loop_detected 1 if we could detect a loop while forwarding, 0 otherwise
rank_error_signaled 1 if the HBH header advertises a rank error, 0 otherwise
Returns
1 if the packet is to be forwarded, 0 if it is to be dropped
Definition at line 659 of file rpl-dag.c.
References rpl_dag_update_state(), rpl_timers_dio_reset(), and rpl_timers_schedule_unicast_dio().
Referenced by rpl_ext_header_hbh_update().
void rpl_refresh_routes (const char * str)
Triggers a route fresh via DTSN increment.
Parameters
str a textual description of the cause for refresh
Definition at line 183 of file rpl-dag.c.
References rpl_dag_root_is_root(), and rpl_neighbor_print_list().
void rpl_reset_prefix (rpl_prefix_t * last_prefix)
Removes current prefx.
Parameters
last_prefix The last prefix (which is to be removed)
Definition at line 132 of file rpl.c.
References ipaddr.
Referenced by rpl_dag_leave().
int rpl_set_prefix (rpl_prefix_t * prefix)
Set prefix from an prefix data structure (from DIO)
Parameters
prefix The prefix
Returns
1 if success, 0 otherwise
Definition at line 176 of file rpl.c.
References addr, routing_driver::drop_route, routing_driver::get_sr_node_ipaddr, routing_driver::init, nbr, routing_driver::neighbor_state_changed, rpl_dag_get_root_ipaddr(), rpl_dag_init(), rpl_dag_poison_and_leave(), rpl_dag_root_is_root(), rpl_dag_root_set_prefix(), rpl_dag_root_start(), rpl_ext_header_hbh_update(), rpl_ext_header_remove(), rpl_ext_header_srh_get_next_hop(), rpl_ext_header_srh_update(), rpl_ext_header_update(), rpl_global_repair(), rpl_has_joined(), rpl_icmp6_init(), rpl_is_reachable(), rpl_link_callback(), rpl_local_repair(), rpl_neighbor_init(), rpl_set_prefix_from_addr(), rpl_timers_init(), uip_create_linklocal_rplnodes_mcast, and uip_sr_init().
int rpl_set_prefix_from_addr (uip_ipaddr_t * addr, unsigned len, uint8_t flags)
Set prefix from an IPv6 address.
Parameters
addr The prefix
len The prefix length
flags The DIO prefix flags
Returns
1 if success, 0 otherwise
Definition at line 148 of file rpl.c.
References ipaddr, and uip_ds6_addr_add().
Referenced by rpl_dag_update_state(), and rpl_set_prefix().
void rpl_timers_dio_reset (const char * str)
Reset DIO Trickle timer.
Parameters
str A textual description of caused the DIO timer reset
Definition at line 149 of file rpl-timers.c.
References ctimer_set(), rpl_dag_ready_to_advertise(), rpl_dag_root_is_root(), and rpl_icmp6_dio_output().
Referenced by rpl_dag_init_root(), rpl_dag_update_state(), rpl_local_repair(), rpl_process_dao(), rpl_process_dis(), rpl_process_hbh(), and rpl_timers_schedule_dao().
void rpl_timers_schedule_state_update (void)
Schedule a state update ASAP.
Useful to force an update from a context where updating directly would be unsafe.
Definition at line 552 of file rpl-timers.c.
References ctimer_set(), and rpl_dag_update_state().
Referenced by rpl_dag_periodic(), rpl_dag_poison_and_leave(), rpl_link_callback(), rpl_local_repair(), and rpl_neighbor_count().