Contiki-NG: UART driver
UART driver
Device drivers
Files
file uart0.c
Contiki compatible UART driver.
file uart0.h
A header file for Contiki compatible UART driver.
Functions
void uart0_init (unsigned long ubr)
Initialize the RS232 port.
Detailed Description
Function Documentation
void uart0_init (unsigned long ubr)
Initialize the RS232 port.
Initalize the RS232 port.
Definition at line 100 of file uart0.c.
References ringbuf_init(), and transmitting().
Referenced by platform_init_stage_two().