Contiki-NG: CC13xx/CC26xx Low-Power management
CC13xx/CC26xx Low-Power management
The TI CC26xx and CC13xx CPUs
CC13xx/CC26xx low-power operation.
Files
file lpm.c
Driver for CC13xx/CC26xx low-power operation.
file lpm.h
Header file for the management of CC13xx/CC26xx low-power operation.
Macros
#define LPM_MODULE(n, m, s, w, l)
Declare a variable to be used in order to get notifications from LPM.
Functions
void lpm_shutdown (uint32_t wakeup_pin, uint32_t io_pull, uint32_t wake_on)
Put the chip in shutdown power mode.
void lpm_sleep (void)
Enter sleep mode.
void lpm_drop (void)
Drop the cortex to sleep / deep sleep and shut down peripherals.
void lpm_register_module (lpm_registered_module_t *module)
Register a module for LPM notifications.
void lpm_unregister_module (lpm_registered_module_t *module)
Unregister a module from LPM notifications.
void lpm_init (void)
Initialise the low-power mode management module.
void lpm_pin_set_default_state (uint32_t ioid)
Sets an IOID to a default state.
Detailed Description
CC13xx/CC26xx low-power operation.
Implementation of CC13xx/CC26xx low-power operation functionality.
Macro Definition Documentation
#define LPM_MODULE (n, m, s, w, l)
Value:
static lpm_registered_module_t n = \
  { NULL, m, s, w, l }
Declare a variable to be used in order to get notifications from LPM.
Parameters
n the variable name to be declared
m A pointer to a function which will tell the LPM module the max PM this module is willing to handle. This function will return LPM_MODE_SLEEP, LPM_MODE_DEEP_SLEEP etc. The LPM module will ask all registered modules and will trigger the highest LPM permitted
s A pointer to a function which will receive a notification just before entering the low power mode. The callee can prepare for the imminent LPM state. The argument to this function will be the upcoming low power mode. This function can e.g. turn off a peripheral before the LPM module shuts down the power domain.
w A pointer to a function which will be called just after we have woken up. This can be used to e.g. turn a peripheral back on. This function is in charge of turning power domains back on. This function will normally be called within an interrupt context.
l Power domain locks, if any are required. The module can request that the SERIAL or PERIPH PD be kept powered up at the transition to deep sleep. This field can be a bitwise OR of LPM_DOMAIN_x, so if required multiple domains can be kept powered.
Definition at line 92 of file lpm.h.
Function Documentation
void lpm_drop (void)
Drop the cortex to sleep / deep sleep and shut down peripherals.
Whether the cortex will drop to sleep or deep sleep is configurable. The exact peripherals which will be shut down is also configurable
Definition at line 539 of file lpm.c.
References lpm_sleep().
Referenced by main().
void lpm_pin_set_default_state (uint32_t ioid)
Sets an IOID to a default state.
Parameters
ioid IOID_0...
This will set ioid to sw control, input, no pull. Input buffer and output driver will both be disabled
The function will do nothing if ioid == IOID_UNUSED, so the caller does not have to check board configuration before calling this.
Definition at line 580 of file lpm.c.
void lpm_register_module (lpm_registered_module_t * module)
Register a module for LPM notifications.
Parameters
module A pointer to the data structure with the module definition
When the LPM module is about to drop to some low power mode, it will first notify all modules about this.
This function must not be called before the module has been initialised with lpm_init(). The code does not perform checks: This is the caller's responsibility.
Definition at line 559 of file lpm.c.
References list_add().
Referenced by board_init(), buzzer_start(), cc26xx_uart_init(), and soc_trng_rand_asynchronous().
void lpm_shutdown (uint32_t wakeup_pin, uint32_t io_pull, uint32_t wake_on)
Put the chip in shutdown power mode.
Parameters
wakeup_pin The GPIO pin which will wake us up. Must be IOID_0 etc...
io_pull Pull configuration for the shutdown pin: IOC_NO_IOPULL, IOC_IOPULL_UP or IOC_IOPULL_DOWN
wake_on High or Low (IOC_WAKE_ON_LOW or IOC_WAKE_ON_HIGH)
Definition at line 92 of file lpm.c.
References aux_ctrl_power_down(), aux_ctrl_register_consumer(), list_head(), oscillators_select_lf_rcosc(), oscillators_switch_to_hf_rc(), and watchdog_periodic().
Referenced by button_press_handler().
void lpm_unregister_module (lpm_registered_module_t * module)
Unregister a module from LPM notifications.
Parameters
module A pointer to the data structure with the module definition
When a previously registered module is no longer interested in LPM notifications, this function can be used to unregister it.
Definition at line 565 of file lpm.c.
References list_remove().
Referenced by buzzer_stop().