Contiki-NG: Zolertia Zoul core module
Zolertia Zoul core module
Platforms
The Zoul comprises the CC2538SF53 and CC1200 in a single module format, which allows a fast reuse of its core components in different formats and form-factors.
Modules
RE-Mote Antenna switch
Driver for the RE-Mote RF antenna switch, to enable either the internal ceramic antenna or an external one connected to the uFL connector.
RE-Mote FatFs
Default port of FatFs on RE-Mote.
RE-Mote Real Time Clock Calendar
Driver for the RE-Mote on-board ultra-low power RTCC (Real Time Clock Calendar)
RE-Mote revision B arch LED
LED driver implementation for the RE-Mote revision B.
SD/MMC architecture-specific definitions
SD/MMC device driver architecture-specific definitions.
Zoul CC1200 arch
CC1200 Zoul arch specifics.
Zoul LED driver
LED driver implementation for the Zoul-based platforms.
Zoul Sensors
Generic module controlling sensors on the Zoul platform.
Zoul-bme280-sensor
Files
file platform.c
Main module for the Zolertia Zoul core and based platforms.
Functions
void board_init (void)
Board specific iniatialisation.
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
void platform_init_stage_two ()
Stage 2 of platform driver initialisation.
void platform_init_stage_three ()
Final stage of platform driver initialisation.
void platform_idle ()
The platform's idle/sleep function.
Detailed Description
The Zoul comprises the CC2538SF53 and CC1200 in a single module format, which allows a fast reuse of its core components in different formats and form-factors.
Function Documentation
void platform_idle (void)
The platform's idle/sleep function.
This function will be called as part of the main loop after all events have been serviced. This is where you will normally put the device in a low-power state. Waking up from this state and tidying up the hardware is the port's responsibility.
It is the port developer's responsibility to implement this function.
Definition at line 251 of file platform.c.
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
This function will get called early on in the Contiki-NG boot sequence.
In this function, the platform should initialise all core device drivers. For example, this is where you will normally want to initialise hardware timers/clocks, GPIO, LEDS. Normally this function will also enable the MCU's global interrupt.
The Contiki-NG process scheduler, software clocks and timers will not be running yet, so any platform drivers that rely on it should not be initialised here. Instead, they should be initialised in platform_init_stage_two() or in platform_init_stage_three()
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_two()
platform_init_stage_three()
Definition at line 179 of file platform.c.
References LEDS_RED, LEDS_YELLOW, and soc_init().
void platform_init_stage_three (void)
Final stage of platform driver initialisation.
Initialisation of platform-specific drivers that require networking to be running. This is also a good place to initialise sensor drivers.
When this function returns, the main routine will assume that the hardware is fully initialised.
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_one()
platform_init_stage_two()
Definition at line 231 of file platform.c.
References adc_init(), board_init(), LEDS_GREEN, LEDS_ORANGE, process_start(), and soc_print_info().
void platform_init_stage_two (void)
Stage 2 of platform driver initialisation.
This function will be called by the Contiki-NG boot sequence after parts of the core have been initialised. More specifically, when this function gets called, the following modules will be running:
Software clock
Process scheduler
Event timer (etimer)
Callback timer (ctimer)
rtimer
Energest (if enabled)
Therefore, any platform driver that relies on any of the above modules should be initialised here or in platform_init_stage_three(), but not in platform_init_stage_one()
The Contiki-NG network stack will not be running yet, so any platform drivers that rely on networking should not be initialised here.
When this function returns, the main routine will assume that the platform has enabled character I/O and can print to console. When this function returns, main() will attempt to initialise the network stack. For this to work properly, this function should also populate linkaddr_node_addr.
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_one()
platform_init_stage_three()
Definition at line 188 of file platform.c.
References button_sensor_init(), crypto_disable(), crypto_init(), INTERRUPTS_ENABLE, LEDS_GREEN, random_init(), SERIAL_LINE_CONF_UART, serial_line_input_byte(), uart_init(), uart_set_input(), udma_init(), usb_serial_init(), and usb_serial_set_input().