Contiki-NG: 6TiSCH Operation Sublayer (6top)
6TiSCH Operation Sublayer (6top)
Link layer
Files
file sixp-nbr.c
    Neighbor Management for 6top Protocol (6P)
file sixp-nbr.h
    Neighbor Management APIs for 6top Protocol (6P)
file sixp-pkt.c
    6top Protocol (6P) Packet Manipulation
file sixp-pkt.h
    6top Protocol (6P) Packet Manipulation APIs
file sixp-trans.c
    Transaction Management for 6top Protocol (6P)
file sixp-trans.h
    Transaction Management APIs for 6top Protocol (6P)
file sixp.c
    6top Protocol (6P)
file sixp.h
    6top Protocol (6P) APIs
file sixtop-conf.h
    6top Configuration
file sixtop.c
    6TiSCH Operation Sublayer (6top)
file sixtop.h
    6TiSCH Operation Sublayer (6top) APIs
Data Structures
union sixp_pkt_code_t
6P Codes integrating Command IDs and Return Codes
struct sixp_pkt_t
6top IE Structure
struct sixtop_sf_t
/brief Scheduling Function Driver
Macros
#define SIXP_INITIAL_SEQUENCE_NUMBER 0
The initial sequence number used for 6P request.
#define SIXTOP_MAX_SCHEDULING_FUNCTIONS 1
The maximum number of Scheduling Functions in the system.
#define SIXTOP_MAX_TRANSACTIONS 1
The maximum number of transactions which the sixtop module can handle at the same time.
Typedefs
typedef struct sixp_nbr sixp_nbr_t
6P Neighbor Data Structure (for internal use)
typedef struct sixp_trans sixp_trans_t
6P Transaction Data Structure (for internal use)
typedef void(* sixp_sent_callback_t)(void *arg, uint16_t arg_len, const linkaddr_t *dest_addr, sixp_output_status_t status)
6P Packet Sent Handler
typedef void(* sixtop_sf_input)(sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t *body, uint16_t body_len, const linkaddr_t *src_addr)
Input Handler of Scheduling Function.
typedef void(* sixtop_sf_timeout)(sixp_pkt_cmd_t cmd, const linkaddr_t *peer_addr)
Timeout Handler of Scheduling Function.
Enumerations
enum sixp_pkt_type_t { SIXP_PKT_TYPE_REQUEST = 0x00, SIXP_PKT_TYPE_RESPONSE = 0x01, SIXP_PKT_TYPE_CONFIRMATION = 0x02, SIXP_PKT_TYPE_RESERVED = 0x03 }
6P Message Types
enum sixp_pkt_cmd_t {
SIXP_PKT_CMD_ADD = 0x01, SIXP_PKT_CMD_DELETE = 0x02, SIXP_PKT_CMD_RELOCATE = 0x03, SIXP_PKT_CMD_COUNT = 0x04,
SIXP_PKT_CMD_LIST = 0x05, SIXP_PKT_CMD_CLEAR = 0x06, SIXP_PKT_CMD_UNAVAILABLE = 0xff
}
6P Command Identifiers
enum sixp_pkt_rc_t {
SIXP_PKT_RC_SUCCESS = 0x00, SIXP_PKT_RC_ERROR = 0x01, SIXP_PKT_RC_EOL = 0x02, SIXP_PKT_RC_RESET = 0x03,
SIXP_PKT_RC_VERSION = 0x04, SIXP_PKT_RC_SFID = 0x05, SIXP_PKT_RC_GEN = 0x06, SIXP_PKT_RC_BUSY = 0x07,
SIXP_PKT_RC_NORES = 0x08, SIXP_PKT_RC_CELLLIST = 0x09
}
6P Return Codes
enum sixp_pkt_cell_option_t { SIXP_PKT_CELL_OPTION_TX = 0x01, SIXP_PKT_CELL_OPTION_RX = 0x02, SIXP_PKT_CELL_OPTION_SHARED = 0x04 }
6P Cell Options
enum sixp_trans_state_t
6P Transaction States (for internal use)
enum sixp_trans_mode_t
6P Transaction Modes (for internal use)
enum sixp_output_status_t { SIXP_OUTPUT_STATUS_SUCCESS, SIXP_OUTPUT_STATUS_FAILURE }
6P Send Status, which represents sixp_output() result.
Functions
sixp_nbr_t * sixp_nbr_find (const linkaddr_t *addr)
Find a neighbor.
sixp_nbr_t * sixp_nbr_alloc (const linkaddr_t *addr)
Allocate a neighbor.
void sixp_nbr_free (sixp_nbr_t *nbr)
Free a neighbor.
int16_t sixp_nbr_get_gen (sixp_nbr_t *nbr)
Return GEN (Generation Number) of a neighbor.
int sixp_nbr_advance_gen (sixp_nbr_t *nbr)
Advance GTX of a neighbor.
int sixp_nbr_get_next_seqno (sixp_nbr_t *nbr)
Get the next sequence number of a neighbor.
int sixp_nbr_increment_next_seqno (sixp_nbr_t *nbr)
Increment the next sequence number of a neighbor.
int sixp_nbr_init (void)
Initialize 6p Neighbor Table.
int sixp_pkt_set_metadata (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_metadata_t metadata, uint8_t *body, uint16_t body_len)
Write Metadata into "Other Fields" of 6P packet.
int sixp_pkt_get_metadata (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_metadata_t *metadata, const uint8_t *body, uint16_t body_len)
Read Metadata stored in "Other Fields" of 6P packet.
int sixp_pkt_set_cell_options (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_cell_options_t cell_options, uint8_t *body, uint16_t body_len)
Write CellOptions in "Other Fields" of 6P packet.
int sixp_pkt_get_cell_options (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_cell_options_t *cell_options, const uint8_t *body, uint16_t body_len)
Read CellOptions in "Other Fields" of 6P packet.
int sixp_pkt_set_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_num_cells_t num_cells, uint8_t *body, uint16_t body_len)
Write NumCells in "Other Fields" of 6P packet.
int sixp_pkt_get_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_num_cells_t *num_cells, const uint8_t *body, uint16_t body_len)
Read NumCells in "Other Fields" of 6P packet.
int sixp_pkt_set_reserved (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_reserved_t reserved, uint8_t *body, uint16_t body_len)
Write Reserved in "Other Fields" of 6P packet.
int sixp_pkt_get_reserved (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_reserved_t *reserved, const uint8_t *body, uint16_t body_len)
Read Reserved in "Other Fields" of 6P packet.
int sixp_pkt_set_offset (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_offset_t offset, uint8_t *body, uint16_t body_len)
Write Offset in "Other Fields" of 6P packet.
int sixp_pkt_get_offset (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_offset_t *offset, const uint8_t *body, uint16_t body_len)
Read Offset in "Other Fields" of 6P packet.
int sixp_pkt_set_max_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_max_num_cells_t max_num_cells, uint8_t *body, uint16_t body_len)
Write MaxNumCells in "Other Fields" of 6P packet.
int sixp_pkt_get_max_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_max_num_cells_t *max_num_cells, const uint8_t *body, uint16_t body_len)
Read MaxNumCells in "Other Fields" of 6P packet.
int sixp_pkt_set_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t *cell_list, uint16_t cell_list_len, uint16_t offset, uint8_t *body, uint16_t body_len)
Write CellList in "Other Fields" of 6P packet.
int sixp_pkt_get_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t **cell_list, sixp_pkt_offset_t *cell_list_len, const uint8_t *body, uint16_t body_len)
Read CellList in "Other Fields" of 6P packet.
int sixp_pkt_set_rel_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t *rel_cell_list, uint16_t rel_cell_list_len, uint16_t offset, uint8_t *body, uint16_t body_len)
Write RelCellList in "Other Fields" of 6P packet.
int sixp_pkt_get_rel_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t **rel_cell_list, sixp_pkt_offset_t *rel_cell_list_len, const uint8_t *body, uint16_t body_len)
Read RelCellList in "Other Fields" of 6P packet.
int sixp_pkt_set_cand_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t *cand_cell_list, uint16_t cand_cell_list_len, uint16_t offset, uint8_t *body, uint16_t body_len)
Write CandCellList in "Other Fields" of 6P packet.
int sixp_pkt_get_cand_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t **cand_cell_list, sixp_pkt_offset_t *cand_cell_list_len, const uint8_t *body, uint16_t body_len)
Read CandCellList in "Other Fields" of 6P packet.
int sixp_pkt_set_total_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_total_num_cells_t total_num_cells, uint8_t *body, uint16_t body_len)
Write TotalNumCells in "Other Fields" of 6P packet.
int sixp_pkt_get_total_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_total_num_cells_t *total_num_cells, const uint8_t *body, uint16_t body_len)
Read TotalNumCells in "Other Fields" of 6P packet.
int sixp_pkt_parse (const uint8_t *buf, uint16_t len, sixp_pkt_t *pkt)
Parse a 6P packet.
int sixp_pkt_create (sixp_pkt_type_t type, sixp_pkt_code_t code, uint8_t sfid, uint8_t seqno, uint8_t gen, const uint8_t *body, uint16_t body_len, sixp_pkt_t *pkt)
Create a 6P packet.
int sixp_trans_transit_state (sixp_trans_t *trans, sixp_trans_state_t new_state)
Change the state of a specified transaction.
sixp_pkt_cmd_t sixp_trans_get_cmd (sixp_trans_t *trans)
Return the command associated with a specified transaction.
sixp_trans_state_t sixp_trans_get_state (sixp_trans_t *trans)
Return the state of a specified transaction.
int16_t sixp_trans_get_seqno (sixp_trans_t *trans)
Return the sequence number associated with a specified transaction.
sixp_trans_mode_t sixp_trans_get_mode (sixp_trans_t *trans)
Return the mode, 2-step or 3-step, of a specified transaction.
void sixp_trans_invoke_callback (sixp_trans_t *trans, sixp_output_status_t status)
Invoke the output callback of a specified transaction.
void sixp_trans_set_callback (sixp_trans_t *trans, sixp_sent_callback_t func, void *arg, uint16_t arg_len)
Set an output callback to a specified transaction.
sixp_trans_t * sixp_trans_alloc (const sixp_pkt_t *pkt, const linkaddr_t *peer_addr)
Allocate a transaction.
sixp_trans_t * sixp_trans_find (const linkaddr_t *peer_addr)
Find a transaction.
int sixp_trans_init (void)
Initialize Memory and List for 6P transactions This function removes and frees existing transactions.
void sixp_input (const uint8_t *buf, uint16_t len, const linkaddr_t *src_addr)
Input a 6P packet.
int sixp_output (sixp_pkt_type_t type, sixp_pkt_code_t code, uint8_t sfid, const uint8_t *body, uint16_t body_len, const linkaddr_t *dest_addr, sixp_sent_callback_t func, void *arg, uint16_t arg_len)
Output a 6P packet.
void sixp_init (void)
Initialize 6P Module It invokes sixp_nbr_init() and sixp_trans_init().
const sixtop_sf_t * sixtop_find_sf (uint8_t sfid)
Find a SF which has been added by SFID.
int sixtop_add_sf (const sixtop_sf_t *sf)
Add a Scheduling Function (SF) to 6top Sublayer.
void sixtop_output (const linkaddr_t *dest_addr, mac_callback_t callback, void *arg)
Output a 6P packet which is supposestored in packetbuf.
void sixtop_input (void)
Input a packet stored in packetbuf.
void sixtop_init (void)
Initialize 6top module This initialization function removes all the SFs which has been installed into the 6top sub-layer.
void sixtop_init_sf (void)
Initialize installed SFs which has been added in the system This function is supposed to be invoked every time the node gets associated.
Variables
uint8_t sixtop_sf_t::sfid
SFID.
Detailed Description
Typedef Documentation
typedef struct sixp_nbr sixp_nbr_t
6P Neighbor Data Structure (for internal use)
XXX: for now, we have one nbr object per neighbor, which is shared with multiple SFs. It's unclear whether we should use a different generation counter for each SFs.
typedef void(* sixtop_sf_input)(sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t *body, uint16_t body_len, const linkaddr_t *src_addr)
Input Handler of Scheduling Function.
Parameters
type 6P Message Type of an input packet
code Code, 6P Command Identifier or Return Code, of an input packet
body Body, "Other Fields", of an input packet
body_len The length of body
body src_addr Source address of an input packet
Definition at line 63 of file sixtop.h.
typedef void(* sixtop_sf_timeout)(sixp_pkt_cmd_t cmd, const linkaddr_t *peer_addr)
Timeout Handler of Scheduling Function.
Parameters
cmd 6P Command (Identifier) in process under the transaction
peer_addr The peer address of the transaction
Definition at line 74 of file sixtop.h.
Enumeration Type Documentation
enum sixp_output_status_t
6P Send Status, which represents sixp_output() result.
Enumerator
SIXP_OUTPUT_STATUS_SUCCESS
SUCCESS.
SIXP_OUTPUT_STATUS_FAILURE
FAILURE.
Definition at line 65 of file sixp.h.
enum sixp_pkt_cell_option_t
6P Cell Options
Enumerator
SIXP_PKT_CELL_OPTION_TX
TX Cell.
SIXP_PKT_CELL_OPTION_RX
RX Cell.
SIXP_PKT_CELL_OPTION_SHARED
SHARED Cell.
Definition at line 109 of file sixp-pkt.h.
enum sixp_pkt_cmd_t
6P Command Identifiers
Enumerator
SIXP_PKT_CMD_ADD
CMD_ADD.
SIXP_PKT_CMD_DELETE
CMD_DELETE.
SIXP_PKT_CMD_RELOCATE
CMD_STATUS.
SIXP_PKT_CMD_COUNT
CMD_STATUS.
SIXP_PKT_CMD_LIST
CMD_LIST.
SIXP_PKT_CMD_CLEAR
CMD_CLEAR.
SIXP_PKT_CMD_UNAVAILABLE
for internal use
Definition at line 71 of file sixp-pkt.h.
enum sixp_pkt_rc_t
6P Return Codes
Enumerator
SIXP_PKT_RC_SUCCESS
RC_SUCCESS.
SIXP_PKT_RC_ERROR
RC_ERROR.
SIXP_PKT_RC_EOL
RC_EOL.
SIXP_PKT_RC_RESET
RC_RESET.
SIXP_PKT_RC_VERSION
RC_ERR_VER.
SIXP_PKT_RC_SFID
RC_ERR_SFID.
SIXP_PKT_RC_GEN
RC_ERR_GEN.
SIXP_PKT_RC_BUSY
RC_ERR_BUSY.
SIXP_PKT_RC_NORES
RC_ERR_NORES.
SIXP_PKT_RC_CELLLIST
RC_ERR_CELLLIST.
Definition at line 84 of file sixp-pkt.h.
enum sixp_pkt_type_t
6P Message Types
Enumerator
SIXP_PKT_TYPE_REQUEST
6P Request
SIXP_PKT_TYPE_RESPONSE
6P Response
SIXP_PKT_TYPE_CONFIRMATION
6P Confirmation
SIXP_PKT_TYPE_RESERVED
Reserved.
Definition at line 61 of file sixp-pkt.h.
Function Documentation
void sixp_input (const uint8_t * buf, uint16_t len, const linkaddr_t * src_addr)
Input a 6P packet.
Parameters
buf The pointer to a buffer pointing the head of 6top IE Content
len The lengh of 6top IE Content
src_addr The Source address of an incoming packet
Returns
0 if , -1 on failure
Definition at line 136 of file sixp.c.
References sixp_pkt_t::body, sixp_pkt_t::body_len, sixp_pkt_t::code, sixp_pkt_t::gen, sixtop_sf_t::input, nbr, sixp_pkt_t::seqno, sixp_pkt_t::sfid, sixp_nbr_find(), sixp_nbr_get_gen(), SIXP_PKT_CMD_CLEAR, sixp_pkt_parse(), SIXP_PKT_RC_BUSY, SIXP_PKT_RC_NORES, SIXP_PKT_RC_SFID, SIXP_PKT_TYPE_CONFIRMATION, SIXP_PKT_TYPE_REQUEST, SIXP_PKT_TYPE_RESPONSE, sixp_trans_alloc(), sixp_trans_find(), sixp_trans_get_seqno(), sixp_trans_transit_state(), sixtop_find_sf(), sixp_pkt_t::type, and sixp_pkt_code_t::value.
Referenced by sixtop_input().
int sixp_nbr_advance_gen (sixp_nbr_t * nbr)
Advance GTX of a neighbor.
Parameters
nbr The pointer to a neighbor
Returns
0 on success, -1 on failure
Definition at line 134 of file sixp-nbr.c.
sixp_nbr_t * sixp_nbr_alloc (const linkaddr_t * addr)
Allocate a neighbor.
Parameters
addr The MAC address of a neighbor
Returns
The pointer to a allocated neighbor, NULL on failure
Definition at line 81 of file sixp-nbr.c.
References linkaddr_copy(), nbr, SIXP_INITIAL_SEQUENCE_NUMBER, and sixp_nbr_find().
Referenced by sixp_output().
sixp_nbr_t * sixp_nbr_find (const linkaddr_t * addr)
Find a neighbor.
Parameters
addr The MAC address of a neighbor
Returns
The pointer to a neighbor, NULL on failure
Definition at line 71 of file sixp-nbr.c.
Referenced by sixp_input(), sixp_nbr_alloc(), and sixp_output().
void sixp_nbr_free (sixp_nbr_t * nbr)
Free a neighbor.
Parameters
nbr The pointer to a neighbor to free
Definition at line 114 of file sixp-nbr.c.
Referenced by sixp_nbr_init().
int16_t sixp_nbr_get_gen (sixp_nbr_t * nbr)
Return GEN (Generation Number) of a neighbor.
Parameters
nbr The pointer to a neighbor
Returns
A value of GEN, -1 on failure
Definition at line 123 of file sixp-nbr.c.
Referenced by sixp_input(), and sixp_output().
int16_t sixp_nbr_get_next_seqno (sixp_nbr_t * nbr)
Get the next sequence number of a neighbor.
Parameters
nbr The pointer to a neighbor
Returns
A sequence number to use for a next request, -1 on failure
Definition at line 156 of file sixp-nbr.c.
Referenced by sixp_output().
int sixp_nbr_increment_next_seqno (sixp_nbr_t * nbr)
Increment the next sequence number of a neighbor.
Parameters
nbr The pointer to a neighbor
Returns
0 on success, -1 on failure
Definition at line 167 of file sixp-nbr.c.
Referenced by sixp_output().
int sixp_output (sixp_pkt_type_t type, sixp_pkt_code_t code, uint8_t sfid, const uint8_t * body, uint16_t body_len, const linkaddr_t * dest_addr, sixp_sent_callback_t func, void * arg, uint16_t arg_len)
Output a 6P packet.
Parameters
type Message Type
code Message Code; Command ID or Return Code
sfid Scheduling Function Identifier
body 6top IE Content
body_len The length of 6top IE Content
dest_addr The destination Address
func callback function invoked after the transmission process
arg The pointer to an argument to be passed with the callback
arg_len The length of the argument
Returns
0 on success, -1 on failure
Definition at line 285 of file sixp.c.
References nbr, sixp_nbr_alloc(), sixp_nbr_find(), sixp_nbr_get_gen(), sixp_nbr_get_next_seqno(), sixp_nbr_increment_next_seqno(), SIXP_PKT_CMD_ADD, SIXP_PKT_CMD_DELETE, sixp_pkt_create(), SIXP_PKT_RC_SUCCESS, SIXP_PKT_TYPE_CONFIRMATION, SIXP_PKT_TYPE_REQUEST, SIXP_PKT_TYPE_RESPONSE, sixp_trans_alloc(), sixp_trans_find(), sixp_trans_get_cmd(), sixp_trans_get_seqno(), sixp_trans_get_state(), sixp_trans_set_callback(), sixtop_output(), and sixp_pkt_code_t::value.
int sixp_pkt_create (sixp_pkt_type_t type, sixp_pkt_code_t code, uint8_t sfid, uint8_t seqno, uint8_t gen, const uint8_t * body, uint16_t body_len, sixp_pkt_t * pkt)
Create a 6P packet.
Parameters
type 6P Message Type
code 6P Message Code, Command Identifier or Return Code
sfid Scheduling Function Identifier
seqno Sequence Number
gen GEN
body The pointer to "Other Fields" in a buffer
body_len The length of body, typically "Other Fields" length
pkt The pointer to a sixp_pkt_t structure to store packet info (option)
Returns
0 on success, -1 on failure
Definition at line 1000 of file sixp-pkt.c.
References sixp_pkt_t::body, sixp_pkt_t::body_len, sixp_pkt_t::code, sixp_pkt_t::gen, packetbuf_clear(), packetbuf_dataptr(), packetbuf_hdralloc(), packetbuf_hdrptr(), packetbuf_set_datalen(), PACKETBUF_SIZE, packetbuf_totlen(), sixp_pkt_t::seqno, sixp_pkt_t::sfid, sixp_pkt_t::type, and sixp_pkt_code_t::value.
Referenced by sixp_output().
int sixp_pkt_get_cand_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t ** cand_cell_list, sixp_pkt_offset_t * cand_cell_list_len, const uint8_t * body, uint16_t body_len)
Read CandCellList in "Other Fields" of 6P packet.
Note
If you want only the length of CandCellList, you can set null to cell_list.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
cand_cell_list The double pointer to store the starting address of CandCellList
cand_cell_list_len Pointer to store the length of CandCellList
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 760 of file sixp-pkt.c.
References sixp_pkt_get_num_cells(), and sixp_pkt_code_t::value.
int sixp_pkt_get_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t ** cell_list, sixp_pkt_offset_t * cell_list_len, const uint8_t * body, uint16_t body_len)
Read CellList in "Other Fields" of 6P packet.
Note
If you want only the length of CellList, you can set null to cell_list.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
cell_list The double pointer to store the starting address of CellList
cell_list_len Pointer to store the length of CellList
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 592 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_get_cell_options (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_cell_options_t * cell_options, const uint8_t * body, uint16_t body_len)
Read CellOptions in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
cell_options The pointer to buffer to store CellOptions in
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 278 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_get_max_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_max_num_cells_t * max_num_cells, const uint8_t * body, uint16_t body_len)
Read MaxNumCells in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
max_num_cells The pointer to buffer to store MaxNumCells in
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 521 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_get_metadata (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_metadata_t * metadata, const uint8_t * body, uint16_t body_len)
Read Metadata stored in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
metadata The pointer to a buffer to store Metadata in
body The pointer to the buffer having "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 213 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_get_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_num_cells_t * num_cells, const uint8_t * body, uint16_t body_len)
Read NumCells in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
num_cells The pointer to buffer to store NumCells in
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 333 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
Referenced by sixp_pkt_get_cand_cell_list(), sixp_pkt_get_rel_cell_list(), sixp_pkt_set_cand_cell_list(), and sixp_pkt_set_rel_cell_list().
int sixp_pkt_get_offset (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_offset_t * offset, const uint8_t * body, uint16_t body_len)
Read Offset in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
offset The pointer to buffer to store Offset in
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 452 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_get_rel_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t ** rel_cell_list, sixp_pkt_offset_t * rel_cell_list_len, const uint8_t * body, uint16_t body_len)
Read RelCellList in "Other Fields" of 6P packet.
Note
If you want only the length of RelCellList, you can set null to rel_cell_list.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
rel_cell_list The double pointer to store the starting address of RelCellList
rel_cell_list_len Pointer to store the length of a returned RelCellList
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 675 of file sixp-pkt.c.
References sixp_pkt_get_num_cells(), and sixp_pkt_code_t::value.
int sixp_pkt_get_reserved (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_reserved_t * reserved, const uint8_t * body, uint16_t body_len)
Read Reserved in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
reserved The pointer to buffer to store Reserved in
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 393 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_get_total_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_total_num_cells_t * total_num_cells, const uint8_t * body, uint16_t body_len)
Read TotalNumCells in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
total_num_cells The pointer to buffer to store TotalNumCells in
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 833 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_parse (const uint8_t * buf, uint16_t len, sixp_pkt_t * pkt)
Parse a 6P packet.
Parameters
buf The pointer to a buffer pointing 6top IE Content
len The length of the buffer
pkt The pointer to a sixp_pkt_t structure to store packet info
Returns
0 on success, -1 on failure
Definition at line 864 of file sixp-pkt.c.
References sixp_pkt_t::body, sixp_pkt_t::body_len, sixp_pkt_code_t::cmd, sixp_pkt_t::code, sixp_pkt_t::gen, sixp_pkt_code_t::rc, sixp_pkt_t::seqno, sixp_pkt_t::sfid, SIXP_PKT_CMD_ADD, SIXP_PKT_CMD_CLEAR, SIXP_PKT_CMD_COUNT, SIXP_PKT_CMD_DELETE, SIXP_PKT_CMD_LIST, SIXP_PKT_CMD_RELOCATE, SIXP_PKT_RC_BUSY, SIXP_PKT_RC_CELLLIST, SIXP_PKT_RC_EOL, SIXP_PKT_RC_ERROR, SIXP_PKT_RC_GEN, SIXP_PKT_RC_NORES, SIXP_PKT_RC_RESET, SIXP_PKT_RC_SFID, SIXP_PKT_RC_SUCCESS, SIXP_PKT_RC_VERSION, SIXP_PKT_TYPE_CONFIRMATION, SIXP_PKT_TYPE_REQUEST, SIXP_PKT_TYPE_RESPONSE, sixp_pkt_t::type, and sixp_pkt_code_t::value.
Referenced by sixp_input().
int sixp_pkt_set_cand_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t * cand_cell_list, uint16_t cand_cell_list_len, uint16_t offset, uint8_t * body, uint16_t body_len)
Write CandCellList in "Other Fields" of 6P packet.
Note
"offset" is specified by index in CandCellList
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
cand_cell_list The pointer to "CandCellList" to write
cand_cell_list_len Length to write
offset Offset in the "CandCellList" field to start writing
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 718 of file sixp-pkt.c.
References sixp_pkt_get_num_cells(), and sixp_pkt_code_t::value.
int sixp_pkt_set_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t * cell_list, uint16_t cell_list_len, uint16_t offset, uint8_t * body, uint16_t body_len)
Write CellList in "Other Fields" of 6P packet.
Note
"offset" is specified by index in CellList
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
cell_list The pointer to "CellList" to write
cell_list_len Length to write
offset Offset in the "CellList" field to start writing
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 556 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_cell_options (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_cell_options_t cell_options, uint8_t * body, uint16_t body_len)
Write CellOptions in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
cell_options "CellOptions" to write
body The pointer to buffer having "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 247 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_max_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_max_num_cells_t max_num_cells, uint8_t * body, uint16_t body_len)
Write MaxNumCells in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
max_num_cells "MaxNumCells" to write
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 487 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_metadata (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_metadata_t metadata, uint8_t * body, uint16_t body_len)
Write Metadata into "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
metadata Metadata to write
body The pointer to "Other Fields" in a buffer
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 180 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_num_cells_t num_cells, uint8_t * body, uint16_t body_len)
Write NumCells in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
num_cells "NumCells" to write
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 309 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_offset (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_offset_t offset, uint8_t * body, uint16_t body_len)
Write Offset in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
offset "Offset" to write
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 418 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_rel_cell_list (sixp_pkt_type_t type, sixp_pkt_code_t code, const uint8_t * rel_cell_list, uint16_t rel_cell_list_len, uint16_t offset, uint8_t * body, uint16_t body_len)
Write RelCellList in "Other Fields" of 6P packet.
Note
"offset" is specified by index in RelCellList
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
rel_cell_list The pointer to "RelCellList" to write
rel_cell_list_len Length to write
offset Offset in the "RelCellList" field to start writing
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 629 of file sixp-pkt.c.
References sixp_pkt_get_num_cells(), and sixp_pkt_code_t::value.
int sixp_pkt_set_reserved (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_reserved_t reserved, uint8_t * body, uint16_t body_len)
Write Reserved in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
reserved "Reserved" to write
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 363 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
int sixp_pkt_set_total_num_cells (sixp_pkt_type_t type, sixp_pkt_code_t code, sixp_pkt_total_num_cells_t total_num_cells, uint8_t * body, uint16_t body_len)
Write TotalNumCells in "Other Fields" of 6P packet.
Parameters
type 6P Message Type
code 6P Command Identifier or Return Code
total_num_cells "TotalNumCells" to write
body The pointer to buffer pointing to "Other Fields"
body_len The length of body, typically "Other Fields" length
Returns
0 on success, -1 on failure
Definition at line 805 of file sixp-pkt.c.
References sixp_pkt_code_t::value.
sixp_trans_t * sixp_trans_alloc (const sixp_pkt_t * pkt, const linkaddr_t * peer_addr)
Allocate a transaction.
Parameters
pkt The pointer to a packet which triggers the allocation
peer_addr The peer address which will be associated
Returns
A pointer to an newly allocated transaction, NULL on failure
Definition at line 310 of file sixp-trans.c.
References sixp_pkt_t::code, list_add(), memb_alloc(), sixp_pkt_t::seqno, sixp_pkt_t::sfid, sixp_trans_find(), sixtop_find_sf(), and sixp_pkt_code_t::value.
Referenced by sixp_input(), and sixp_output().
sixp_trans_t * sixp_trans_find (const linkaddr_t * peer_addr)
Find a transaction.
Parameters
peer_addr The peer address
Returns
The pointer to a transaction; NULL on failure
Definition at line 353 of file sixp-trans.c.
References list_head().
Referenced by sixp_input(), sixp_output(), and sixp_trans_alloc().
sixp_pkt_cmd_t sixp_trans_get_cmd (sixp_trans_t * trans)
Return the command associated with a specified transaction.
Parameters
trans The pointer to a transaction
Returns
Command identifier; SIXP_PKT_CMD_UNAVAILABLE on failure
Definition at line 243 of file sixp-trans.c.
References SIXP_PKT_CMD_UNAVAILABLE.
Referenced by sixp_output().
sixp_trans_mode_t sixp_trans_get_mode (sixp_trans_t * trans)
Return the mode, 2-step or 3-step, of a specified transaction.
Parameters
trans The pointer to a transaction
Returns
The mode of the transaction, SIXP_TRANS_MODE_UNAVAILABLE on failure
Definition at line 274 of file sixp-trans.c.
int16_t sixp_trans_get_seqno (sixp_trans_t * trans)
Return the sequence number associated with a specified transaction.
Parameters
trans The pointer of a transaction
Returns
0 or larger than 0 on success, -1 on failure
Definition at line 263 of file sixp-trans.c.
Referenced by sixp_input(), and sixp_output().
sixp_trans_state_t sixp_trans_get_state (sixp_trans_t * trans)
Return the state of a specified transaction.
Parameters
trans The pointer to a transaction
Returns
a state of the transaction; SIXP_TRANS_STATE_UNAVAILABLE if the transaction is not found in the system.
Definition at line 253 of file sixp-trans.c.
Referenced by sixp_output().
void sixp_trans_invoke_callback (sixp_trans_t * trans, sixp_output_status_t status)
Invoke the output callback of a specified transaction.
Parameters
trans The pointer to a transaction
status An output result value
Definition at line 285 of file sixp-trans.c.
void sixp_trans_set_callback (sixp_trans_t * trans, sixp_sent_callback_t func, void * arg, uint16_t arg_len)
Set an output callback to a specified transaction.
Parameters
trans The pointer to a transaction
func The pointer to a callback function
arg The pointer to an argument which will be passed to func
arg_len The length of the argument
Definition at line 297 of file sixp-trans.c.
Referenced by sixp_output().
int sixp_trans_transit_state (sixp_trans_t * trans, sixp_trans_state_t new_state)
Change the state of a specified transaction.
Parameters
trans The pointer to a transaction
new_state New state to move the transaction to
Returns
0 on success, -1 on failure
Definition at line 205 of file sixp-trans.c.
Referenced by sixp_input().
int sixtop_add_sf (const sixtop_sf_t * sf)
Add a Scheduling Function (SF) to 6top Sublayer.
Parameters
sf The pointer to a Scheduling Function Driver
Returns
0 on success, -1 on failure
If there is a SF whose SF is identical to one of a SF specified to this API, the addition will fail and -1 will be returned. If there is no room to another SF, -1 will be returned as well. You can specify how many SFs can be added with SIXTOP_CONF_MAX_SCHEDULING_FUNCTIONS.
Definition at line 74 of file sixtop.c.
References sixtop_sf_t::init, sixtop_sf_t::sfid, sixtop_find_sf(), and SIXTOP_MAX_SCHEDULING_FUNCTIONS.
const sixtop_sf_t * sixtop_find_sf (uint8_t sfid)
Find a SF which has been added by SFID.
Parameters
sfid Scheduling Function Identifier of a SF
Returns
The pointer to a SF driver having the specified SFID on success, NULL on failure (not found)
Definition at line 110 of file sixtop.c.
References SIXTOP_MAX_SCHEDULING_FUNCTIONS.
Referenced by sixp_input(), sixp_trans_alloc(), and sixtop_add_sf().
void sixtop_init (void)
Initialize 6top module This initialization function removes all the SFs which has been installed into the 6top sub-layer.
In addition, it invokes sixp_init().
Definition at line 260 of file sixtop.c.
References sixp_init(), sixtop_init_sf(), and SIXTOP_MAX_SCHEDULING_FUNCTIONS.
void sixtop_output (const linkaddr_t * dest_addr, mac_callback_t callback, void * arg)
Output a 6P packet which is supposestored in packetbuf.
Parameters
dest_addr Destination address of the outgoing packet
callback MAC callback function to get a TX result
arg The pointer to an argument which is returned with the MAC callback
Definition at line 125 of file sixtop.c.
References linkaddr_node_addr, packetbuf_datalen(), packetbuf_dataptr(), packetbuf_hdralloc(), packetbuf_hdrptr(), packetbuf_set_datalen(), PACKETBUF_SIZE, packetbuf_totlen(), and mac_driver::send.
Referenced by sixp_output().
Variable Documentation
sixtop_sf_t::sfid
SFID.
managed: 0x00-0xfe unmanaged: 0xf0-0xfe reserved: 0xff
Definition at line 80 of file sixtop.h.
Referenced by sixtop_add_sf().