Contiki-NG: Bluetooth Low Energy drivers
Bluetooth Low Energy drivers
nrf52832 SoC
Files
file ble-core.c
Basic BLE functions.
file ble-core.h
Basic BLE functions.
file ble-mac.c
A MAC protocol implementation that uses nRF52 IPSP implementation as a link layer.
file ble-mac.h
A MAC protocol implementation that uses nRF52 IPSP implementation as a link layer.
Macros
#define APP_ADV_TIMEOUT 0
Time for which the device must be advertising in non-connectable mode (in seconds).
#define APP_ADV_ADV_INTERVAL MSEC_TO_UNITS(333, UNIT_0_625_MS)
The advertising interval.
#define BLE_MAC_MAX_INTERFACE_NUM 1
Maximum number of interfaces, i.e., connection to master devices.
Functions
static void ble_evt_dispatch (ble_evt_t *p_ble_evt)
SoftDevice BLE event callback.
void ble_stack_init (void)
Initialize and enable the BLE stack.
void ble_get_mac (uint8_t addr[8])
Return device EUI64 MAC address.
void ble_advertising_init (const char *name)
Initialize BLE advertising data.
void ble_advertising_start (void)
Start BLE advertising.
void ble_gap_addr_print (const ble_gap_addr_t *addr)
Print GAP address.
static void on_ble_evt (ble_evt_t *p_ble_evt)
Function for handling the Application's BLE Stack events.
static ble_mac_interface_t * ble_mac_interface_lookup (ble_ipsp_handle_t *handle)
Lookup interface by IPSP connection.
static ble_mac_interface_t * ble_mac_interface_add (eui64_t *peer, ble_ipsp_handle_t *handle)
Add IPSP connection to the interface table.
static void ble_mac_interface_delete (ble_mac_interface_t *interface)
Remove interface from the interface table.
static uint32_t ble_mac_ipsp_evt_handler_irq (ble_ipsp_handle_t *p_handle, ble_ipsp_evt_t *p_evt)
Callback registered with IPSP to receive asynchronous events from the module.
static ble_ipsp_handle_t * find_handle (const linkaddr_t *addr)
Lookup IPSP handle by peer address.
static int send_to_peer (ble_ipsp_handle_t *handle)
Send packet on a given IPSP handle.
Variables
static ble_gap_adv_params_t m_adv_params
Parameters to be passed to the stack when starting advertising.
process_event_t ble_event_interface_added
This event is broadcast when BLE connection is established.
process_event_t ble_event_interface_deleted
This event is broadcast when BLE connection is destroyed.
static volatile int busy_tx
Flag is set to 1 when the driver is busy transmitting a packet.
static volatile int busy_rx
Flag is set to 1 when there is a received packet pending.
const struct mac_driver ble_ipsp_mac_driver
BLE over IPSP MAC driver structure.
const struct mac_driver ble_ipsp_mac_driver
BLE over IPSP MAC driver structure.
process_event_t ble_event_interface_added
This event is broadcast when a new IPSP connection is established.
process_event_t ble_event_interface_deleted
This event is broadcast when a IPSP connection is deleted.
Detailed Description
Macro Definition Documentation
#define APP_ADV_ADV_INTERVAL MSEC_TO_UNITS(333, UNIT_0_625_MS)
The advertising interval.
This value can vary between 100ms to 10.24s).
Definition at line 70 of file ble-core.c.
Referenced by ble_advertising_init().
#define APP_ADV_TIMEOUT 0
Time for which the device must be advertising in non-connectable mode (in seconds).
0 disables timeout.
Definition at line 69 of file ble-core.c.
Referenced by ble_advertising_init().
Function Documentation
void ble_advertising_init (const char * name)
Initialize BLE advertising data.
Parameters
name Human readable device name that will be advertised
Definition at line 132 of file ble-core.c.
References APP_ADV_ADV_INTERVAL, APP_ADV_TIMEOUT, and m_adv_params.
Referenced by platform_init_stage_two().
static void ble_evt_dispatch (ble_evt_t * p_ble_evt) static
SoftDevice BLE event callback.
Parameters
[in] p_ble_evt Bluetooth stack event.
Definition at line 228 of file ble-core.c.
References on_ble_evt().
Referenced by ble_stack_init().
void ble_gap_addr_print (const ble_gap_addr_t * addr)
Print GAP address.
Parameters
addr a pointer to address
Definition at line 187 of file ble-core.c.
Referenced by on_ble_evt().
void ble_get_mac (uint8_t addr[8])
Return device EUI64 MAC address.
Parameters
addr pointer to a buffer to store the address
Definition at line 116 of file ble-core.c.
Referenced by platform_init_stage_three().
static ble_mac_interface_t* ble_mac_interface_add (eui64_t * peer, ble_ipsp_handle_t * handle) static
Add IPSP connection to the interface table.
This function binds IPSP connection with peer address.
Parameters
peer a pointer to eui64 address
handle a pointer to IPSP handle
Return values
a pointer to an interface structure on success
NULL if interface table is full
Definition at line 133 of file ble-mac.c.
References ble_event_interface_added, BLE_MAC_MAX_INTERFACE_NUM, and process_post().
Referenced by ble_mac_ipsp_evt_handler_irq().
static void ble_mac_interface_delete (ble_mac_interface_t * interface) static
Remove interface from the interface table.
Parameters
interface a pointer to interface
Definition at line 152 of file ble-mac.c.
References ble_event_interface_deleted, and process_post().
Referenced by ble_mac_ipsp_evt_handler_irq().
static ble_mac_interface_t* ble_mac_interface_lookup (ble_ipsp_handle_t * handle) static
Lookup interface by IPSP connection.
Parameters
handle a pointer to IPSP handle.
Return values
a pointer to interface structure
NULL if no interface has been found for a given handle
Definition at line 109 of file ble-mac.c.
References BLE_MAC_MAX_INTERFACE_NUM.
Referenced by ble_mac_ipsp_evt_handler_irq().
static uint32_t ble_mac_ipsp_evt_handler_irq (ble_ipsp_handle_t * p_handle, ble_ipsp_evt_t * p_evt) static
Callback registered with IPSP to receive asynchronous events from the module.
Note
This function is called from SoftDevice interrupt context.
Parameters
[in] p_handle Pointer to IPSP handle.
[in] p_evt Pointer to specific event, generated by IPSP module.
Returns
NRF_SUCCESS on success, otherwise NRF_ERROR_NO_MEM error.
Definition at line 169 of file ble-mac.c.
References ble_mac_interface_add(), ble_mac_interface_delete(), ble_mac_interface_lookup(), busy_rx, busy_tx, PACKETBUF_SIZE, and process_poll().
static ble_ipsp_handle_t* find_handle (const linkaddr_t * addr) static
Lookup IPSP handle by peer address.
Parameters
addr a pointer to eui64 address.
Return values
a pointer to IPSP handle on success
NULL if an IPSP handle for given address haven't been found
Definition at line 276 of file ble-mac.c.
References BLE_MAC_MAX_INTERFACE_NUM, and linkaddr_cmp().
static void on_ble_evt (ble_evt_t * p_ble_evt) static
Function for handling the Application's BLE Stack events.
Parameters
[in] p_ble_evt Bluetooth stack event.
Definition at line 202 of file ble-core.c.
References ble_advertising_start(), and ble_gap_addr_print().
Referenced by ble_evt_dispatch().
static int send_to_peer (ble_ipsp_handle_t * handle) static
Send packet on a given IPSP handle.
Parameters
handle a pointer to IPSP handle.
Returns
1 on success, 0 otherwise
Definition at line 294 of file ble-mac.c.
References packetbuf_datalen(), and packetbuf_dataptr().
Variable Documentation
process_event_t ble_event_interface_added
This event is broadcast when a new IPSP connection is established.
This event is broadcast when a new IPSP connection is established.
Definition at line 70 of file ble-mac.c.
Referenced by ble_mac_interface_add().
process_event_t ble_event_interface_added
This event is broadcast when BLE connection is established.
This event is broadcast when a new IPSP connection is established.
Definition at line 70 of file ble-mac.c.
Referenced by ble_mac_interface_add().
process_event_t ble_event_interface_deleted
This event is broadcast when a IPSP connection is deleted.
This event is broadcast when a IPSP connection is deleted.
Definition at line 71 of file ble-mac.c.
Referenced by ble_mac_interface_delete().
process_event_t ble_event_interface_deleted
This event is broadcast when BLE connection is destroyed.
This event is broadcast when a IPSP connection is deleted.
Definition at line 71 of file ble-mac.c.
Referenced by ble_mac_interface_delete().
volatile int busy_rx static
Flag is set to 1 when there is a received packet pending.
Definition at line 88 of file ble-mac.c.
Referenced by ble_mac_ipsp_evt_handler_irq().
volatile int busy_tx static
Flag is set to 1 when the driver is busy transmitting a packet.
Definition at line 87 of file ble-mac.c.
Referenced by ble_mac_ipsp_evt_handler_irq().
ble_gap_adv_params_t m_adv_params static
Parameters to be passed to the stack when starting advertising.
Definition at line 72 of file ble-core.c.
Referenced by ble_advertising_init(), and ble_advertising_start().