Contiki-NG: The Contiki/uIP interface
The Contiki/uIP interface
IoT networking » Network layer » uIP: the IPv6 stack
TCP/IP support in Contiki is implemented using the uIP TCP/IP stack.
Macros
#define UIP_APPCALL tcpip_uipcall
The name of the application function that uIP should call in response to TCP/IP events.
Variables
process_event_t tcpip_event
The uIP event.
TCP functions
void tcp_attach (struct uip_conn *conn, void *appstate)
Attach a TCP connection to the current process.
void tcp_listen (uint16_t port)
Open a TCP port.
void tcp_unlisten (uint16_t port)
Close a listening TCP port.
struct uip_conn * tcp_connect (const uip_ipaddr_t *ripaddr, uint16_t port, void *appstate)
Open a TCP connection to the specified IP address and port.
void tcpip_poll_tcp (struct uip_conn *conn)
Cause a specified TCP connection to be polled.
#define tcp_markconn(conn, appstate) tcp_attach(conn, appstate)
UDP functions
void udp_attach (struct uip_udp_conn *conn, void *appstate)
Attach the current process to a UDP connection.
struct uip_udp_conn * udp_new (const uip_ipaddr_t *ripaddr, uint16_t port, void *appstate)
Create a new UDP connection.
struct uip_udp_conn * udp_broadcast_new (uint16_t port, void *appstate)
Create a new UDP broadcast connection.
void tcpip_poll_udp (struct uip_udp_conn *conn)
Cause a specified UDP connection to be polled.
#define udp_markconn(conn, appstate) udp_attach(conn, appstate)
#define udp_bind(conn, port) uip_udp_bind(conn, port)
Bind a UDP connection to a local port.
ICMPv6 functions
process_event_t tcpip_icmp6_event
The ICMP6 event.
uint8_t icmp6_new (void *appstate)
register an ICMPv6 callback
void tcpip_icmp6_call (uint8_t type)
This function is called at reception of an ICMPv6 packet If an application registered as an ICMPv6 listener (with icmp6_new), it will be called through a process_post_synch()
TCP/IP packet processing
unsigned char tcpip_do_forwarding
Is forwarding generally enabled?
unsigned char tcpip_is_forwarding
void tcpip_input (void)
Deliver an incoming packet to the TCP/IP stack.
uint8_t tcpip_output (const uip_lladdr_t *)
Output packet to layer 2 The eventual parameter is the MAC address of the destination.
void tcpip_ipv6_output (void)
This function does address resolution and then calls tcpip_output.
#define tcpip_set_forwarding(forwarding) tcpip_do_forwarding = (forwarding)
Detailed Description
TCP/IP support in Contiki is implemented using the uIP TCP/IP stack.
For sending and receiving data, Contiki uses the functions provided by the uIP module, but Contiki adds a set of functions for connection management. The connection management functions make sure that the uIP TCP/IP connections are connected to the correct process.
Contiki also includes an optional protosocket library that provides an API similar to the BSD socket API.
See also
The uIP TCP/IP stack
Protosockets library
Macro Definition Documentation
#define udp_bind (conn, port) uip_udp_bind(conn, port)
Bind a UDP connection to a local port.
This function binds a UDP connection to a specified local port.
When a connection is created with udp_new(), it gets a local port number assigned automatically. If the application needs to bind the connection to a specified local port, this function should be used.
Note
The port number must be provided in network byte order so a conversion with UIP_HTONS() usually is necessary.
Parameters
conn A pointer to the UDP connection that is to be bound.
port The port number in network byte order to which to bind the connection.
Definition at line 261 of file tcpip.h.
Referenced by coap_sendto(), simple_udp_register(), and udp_broadcast_new().
Function Documentation
uint8_t icmp6_new (void * appstate)
register an ICMPv6 callback
Returns
0 if success, 1 if failure (one application already registered)
This function just registers a process to be polled when an ICMPv6 message is received. If no application registers, some ICMPv6 packets will be processed by the "kernel" as usual (NS, NA, RS, RA, Echo request), others will be dropped. If an application registers here, it will be polled with a process_post_synch every time an ICMPv6 packet is received.
Definition at line 296 of file tcpip.c.
References uip_icmp6_conns.
void tcp_attach (struct uip_conn * conn, void * appstate)
Attach a TCP connection to the current process.
This function attaches the current process to a TCP connection. Each TCP connection must be attached to a process in order for the process to be able to receive and send data. Additionally, this function can add a pointer with connection state to the connection.
Parameters
conn A pointer to the TCP connection.
appstate An opaque pointer that will be passed to the process whenever an event occurs on the connection.
Definition at line 251 of file tcpip.c.
struct uip_conn* tcp_connect (const uip_ipaddr_t * ripaddr, uint16_t port, void * appstate)
Open a TCP connection to the specified IP address and port.
This function opens a TCP connection to the specified port at the host specified with an IP address. Additionally, an opaque pointer can be attached to the connection. This pointer will be sent together with uIP events to the process.
Note
The port number must be provided in network byte order so a conversion with UIP_HTONS() usually is necessary.
This function will only create the connection. The connection is not opened directly. uIP will try to open the connection the next time the uIP stack is scheduled by Contiki.
Parameters
ripaddr Pointer to the IP address of the remote host.
port Port number in network byte order.
appstate Pointer to application defined data.
Returns
A pointer to the newly created connection, or NULL if memory could not be allocated for the connection.
Referenced by tcpip_output().
void tcp_listen (uint16_t port)
Open a TCP port.
This function opens a TCP port for listening. When a TCP connection request occurs for the port, the process will be sent a tcpip_event with the new connection request.
Note
Port numbers must always be given in network byte order. The functions UIP_HTONS() and uip_htons() can be used to convert port numbers from host byte order to network byte order.
Parameters
port The port number in network byte order.
Definition at line 233 of file tcpip.c.
References PROCESS_CURRENT, uip_listen(), and UIP_LISTENPORTS.
void tcp_unlisten (uint16_t port)
Close a listening TCP port.
This function closes a listening TCP port.
Note
Port numbers must always be given in network byte order. The functions UIP_HTONS() and uip_htons() can be used to convert port numbers from host byte order to network byte order.
Parameters
port The port number in network byte order.
Definition at line 215 of file tcpip.c.
References PROCESS_CURRENT, UIP_LISTENPORTS, and uip_unlisten().
void tcpip_input (void)
Deliver an incoming packet to the TCP/IP stack.
This function is called by network device drivers to deliver an incoming packet to the TCP/IP stack. The incoming packet must be present in the uip_buf buffer, and the length of the packet must be in the global uip_len variable.
Definition at line 449 of file tcpip.c.
References addr, routing_driver::drop_route, routing_driver::ext_header_srh_get_next_hop, ICMP6_DST_UNREACH, ICMP6_DST_UNREACH_ADDR, nbr, NBR_INCOMPLETE, process_post_synch(), stimer_set(), tcpip_ipv6_output(), tcpip_output(), uip_ds6_if, uip_ds6_nbr_add(), uip_ext_len, uip_icmp6_error_output(), UIP_IP_BUF, uip_len, and uip_nd6_ns_output().
Referenced by input(), and slip_send().
void tcpip_poll_tcp (struct uip_conn * conn)
Cause a specified TCP connection to be polled.
This function causes uIP to poll the specified TCP connection. The function is used when the application has data that is to be sent immediately and do not wish to wait for the periodic uIP polling mechanism.
Parameters
conn A pointer to the TCP connection that should be polled.
Definition at line 763 of file tcpip.c.
References uip_udp_conn::appstate, CLOCK_SECOND, etimer_set(), routing_driver::init, uip_conn::lport, process_alloc_event(), PROCESS_BEGIN, PROCESS_CURRENT, PROCESS_END, process_post(), process_post_synch(), PROCESS_THREAD(), PROCESS_YIELD, tcpip_event, tcpip_icmp6_event, uip_connected, uip_init(), and UIP_LISTENPORTS.
Referenced by tcpip_output().
void tcpip_poll_udp (struct uip_udp_conn * conn)
Cause a specified UDP connection to be polled.
This function causes uIP to poll the specified UDP connection. The function is used when the application has data that is to be sent immediately and do not wish to wait for the periodic uIP polling mechanism.
Parameters
conn A pointer to the UDP connection that should be polled.
Definition at line 755 of file tcpip.c.
References process_post().
Referenced by resolv_get_hostname().
void udp_attach (struct uip_udp_conn * conn, void * appstate)
Attach the current process to a UDP connection.
This function attaches the current process to a UDP connection. Each UDP connection must have a process attached to it in order for the process to be able to receive and send data over the connection. Additionally, this function can add a pointer with connection state to the connection.
Parameters
conn A pointer to the UDP connection.
appstate An opaque pointer that will be passed to the process whenever an event occurs on the connection.
Definition at line 259 of file tcpip.c.
References uip_udp_conn::appstate.
struct uip_udp_conn* udp_broadcast_new (uint16_t port, void * appstate)
Create a new UDP broadcast connection.
This function creates a new (link-local) broadcast UDP connection to a specified port.
Parameters
port Port number in network byte order.
appstate Pointer to application defined data.
Returns
A pointer to the newly created connection, or NULL if memory could not be allocated for the connection.
Definition at line 279 of file tcpip.c.
References addr, udp_bind, udp_new(), and uip_create_linklocal_allnodes_mcast.
struct uip_udp_conn* udp_new (const uip_ipaddr_t * ripaddr, uint16_t port, void * appstate)
Create a new UDP connection.
This function creates a new UDP connection with the specified remote endpoint.
Note
The port number must be provided in network byte order so a conversion with UIP_HTONS() usually is necessary.
See also
udp_bind()
Parameters
ripaddr Pointer to the IP address of the remote host.
port Port number in network byte order.
appstate Pointer to application defined data.
Returns
A pointer to the newly created connection, or NULL if memory could not be allocated for the connection.
Definition at line 265 of file tcpip.c.
References uip_udp_conn::appstate, and uip_udp_new().
Referenced by coap_sendto(), resolv_get_hostname(), simple_udp_register(), and udp_broadcast_new().
Variable Documentation
process_event_t tcpip_event
The uIP event.
This event is posted to a process whenever a uIP event has occurred.
Definition at line 66 of file tcpip.c.
Referenced by coap_sendto(), resolv_get_hostname(), simple_udp_register(), and tcpip_poll_tcp().
process_event_t tcpip_icmp6_event
The ICMP6 event.
This event is posted to a process whenever a uIP ICMP event has occurred.
Definition at line 68 of file tcpip.c.
Referenced by tcpip_icmp6_call(), and tcpip_poll_tcp().