Contiki-NG: Device Drivers
Device Drivers
Hardware support
Modules
Button HAL
Hardware abstraction layer for user buttons.
Disk device drivers
Documentation for all the disk device drivers.
EEPROM API
The EEPROM API defines a common interface for EEPROM access on Contiki platforms.
GPIO Hardware Abstraction Layer
The GPIO HAL provides a set of common functions that can be used in a platform-independent fashion.
Generic RGB LED driver
This is a driver for a tri-color RGB LED part, such as for example the Broadcom (ex Avago Technologies) PLCC-4 Tricolor Black Surface LED present on all Zolertia Zoul-based boards.
LED Hardware Abstraction Layer
The LED HAL provides a set of functions that can manipulate LEDS.
Radio API
The radio API module defines a set of functions that a radio device driver must implement.
SPI Hardware Abstraction Layer
The SPI HAL provides a set of common functions that can be used in a platform-independent fashion.
Files
file leds.h
Header file for the LED HAL.
Data Structures
struct leds_s
A LED logical representation.
typedef uint8_t leds_num_t
The LED number.
typedef uint8_t leds_mask_t
An OR mask datatype to represents multiple LEDs.
typedef struct leds_s leds_t
A LED logical representation.
void leds_init (void)
Initialise the LED HAL.
void leds_single_on (leds_num_t led)
Turn a single LED on.
void leds_single_off (leds_num_t led)
Turn a single LED off.
void leds_single_toggle (leds_num_t led)
Toggle a single LED.
void leds_on (leds_mask_t leds)
Turn on multiple LEDs.
void leds_off (leds_mask_t leds)
Turn off multiple LEDs.
void leds_toggle (leds_mask_t leds)
Toggle multiple LEDs.
void leds_set (leds_mask_t leds)
Set all LEDs to a specific state.
leds_mask_t leds_get (void)
Get the status of LEDs.
#define LEDS_COLOUR_NONE 0x00
A default LED colour for non-existing LEDs.
#define LEDS_COUNT 0
The number of LEDs present on a device.
#define LEDS_ALL ((1 << LEDS_COUNT) - 1)
The OR mask representation of all device LEDs.
#define LEDS_LED1 0x00
Convenience macro to refer to the 1st LED (LED 1)
#define LEDS_LED2 0x01
Convenience macro to refer to the 2nd LED (LED 2)
#define LEDS_LED3 0x02
Convenience macro to refer to the 3rd LED (LED 3)
#define LEDS_LED4 0x03
Convenience macro to refer to the 4th LED (LED 4)
#define LEDS_LED5 0x04
Convenience macro to refer to the 5th LED (LED 5)
#define LEDS_NUM_TO_MASK(l) (1 << (l))
Convert a LED number to a mask representation.
Detailed Description
Macro Definition Documentation
#define LEDS_NUM_TO_MASK (l) (1 << (l))
Convert a LED number to a mask representation.
Parameters
l The pin number (normally a variable of type leds_num_t)
Returns
An OR mask of type leds_mask_t
Definition at line 223 of file leds.h.
Typedef Documentation
typedef struct leds_s leds_t
A LED logical representation.
pin corresponds to the GPIO pin a LED is driven by, using GPIO HAL pin representation.
negative_logic should be set to false if the LED is active low.
Function Documentation
leds_mask_t leds_get (void)
Get the status of LEDs.
Returns
A bitwise mask indicating whether each individual LED is on or off
The return value is a bitwise mask. If a bit is set then the corresponding LED is on.
Definition at line 207 of file leds.c.
References LEDS_COUNT.
void leds_init (void)
Initialise the LED HAL.
This function will set corresponding LED GPIO pins to output and will also set the initial state of all LEDs to off.
Definition at line 44 of file minileds.c.
References LEDS_ALL, LEDS_COUNT, and leds_off().
Referenced by platform_init_stage_one(), and platform_main_loop().
void leds_off (leds_mask_t leds)
Turn off multiple LEDs.
Parameters
leds The leds to be turned off as an OR mask
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will not change the state of other LEDs.
Definition at line 69 of file minileds.c.
References LEDS_ALL, and LEDS_COUNT.
Referenced by leds_init(), leds_set(), platform_init_stage_three(), platform_init_stage_two(), rgb_led_off(), and rgb_led_set().
void leds_on (leds_mask_t leds)
Turn on multiple LEDs.
Parameters
leds The leds to be turned on as an OR mask
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will not change the state of other LEDs.
Definition at line 63 of file minileds.c.
References LEDS_ALL, and LEDS_COUNT.
Referenced by leds_set(), platform_init_stage_one(), platform_init_stage_two(), and rgb_led_set().
void leds_set (leds_mask_t leds)
Set all LEDs to a specific state.
Parameters
leds The state of all LEDs afer this function returns
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will change the state of all LEDs. LEDs not set in the leds mask will be turned off.
Definition at line 200 of file leds.c.
References LEDS_ALL, leds_off(), and leds_on().
void leds_single_off (leds_num_t led)
Turn a single LED off.
Parameters
led The led
The led argument should be the LED's number, in other words one of the LED_Ln macros.
This function will not change the state of other LEDs.
Definition at line 132 of file leds.c.
References LEDS_COUNT.
void leds_single_on (leds_num_t led)
Turn a single LED on.
Parameters
led The led
The led argument should be the LED's number, in other words one of the LED_Ln macros.
This function will not change the state of other LEDs.
Definition at line 118 of file leds.c.
References LEDS_COUNT.
void leds_single_toggle (leds_num_t led)
Toggle a single LED.
Parameters
led The led
The led argument should be the LED's number, in other words one of the LED_Ln macros.
This function will not change the state of other LEDs.
Definition at line 146 of file leds.c.
References gpio_hal_arch_toggle_pin(), and LEDS_COUNT.
void leds_toggle (leds_mask_t leds)
Toggle multiple LEDs.
Parameters
leds The leds to be toggled as an OR mask
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will not change the state of other LEDs.
Definition at line 75 of file minileds.c.
References gpio_hal_arch_toggle_pin(), LEDS_ALL, and LEDS_COUNT.