Contiki-NG: NVIC Functions
NVIC Functions
Functions and Instructions Reference
Functions that manage interrupts and exceptions via the NVIC.
Functions
__STATIC_INLINE uint32_t NVIC_IsIRQEnabled (IRQn_Type IRQn)
Get External Interrupt Enable State.
__STATIC_INLINE void NVIC_EnableIRQ (IRQn_Type IRQn)
Enable External Interrupt.
__STATIC_INLINE void NVIC_DisableIRQ (IRQn_Type IRQn)
Disable External Interrupt.
__STATIC_INLINE uint32_t NVIC_GetPendingIRQ (IRQn_Type IRQn)
Get Pending Interrupt.
__STATIC_INLINE void NVIC_SetPendingIRQ (IRQn_Type IRQn)
Set Pending Interrupt.
__STATIC_INLINE void NVIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear Pending Interrupt.
__STATIC_INLINE void NVIC_SetPriority (IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
__STATIC_INLINE uint32_t NVIC_GetPriority (IRQn_Type IRQn)
Get Interrupt Priority.
__STATIC_INLINE void NVIC_SystemReset (void)
System Reset.
__STATIC_INLINE void NVIC_SetPriorityGrouping (uint32_t PriorityGroup)
Set Priority Grouping.
__STATIC_INLINE uint32_t NVIC_GetPriorityGrouping (void)
Get Priority Grouping.
__STATIC_INLINE uint32_t NVIC_GetActive (IRQn_Type IRQn)
Get Active Interrupt.
__STATIC_INLINE uint32_t NVIC_EncodePriority (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)
Encode Priority.
__STATIC_INLINE void NVIC_DecodePriority (uint32_t Priority, uint32_t PriorityGroup, uint32_t *const pPreemptPriority, uint32_t *const pSubPriority)
Decode Priority.
Detailed Description
Functions that manage interrupts and exceptions via the NVIC.
Function Documentation
__STATIC_INLINE void NVIC_ClearPendingIRQ (IRQn_Type IRQn)
Clear Pending Interrupt.
Clears the pending bit of an external interrupt.
Parameters
[in] IRQn External interrupt number. Value cannot be negative.
Definition at line 688 of file core_cm0.h.
References NVIC.
Referenced by aes_auth_crypt_start(), bignum_add_start(), bignum_cmp_start(), bignum_divide_start(), bignum_exp_mod_start(), bignum_inv_mod_start(), bignum_mod_start(), bignum_mul_start(), bignum_subtract_start(), crypto_isr(), ecc_add_start(), ecc_mul_gen_pt_start(), ecc_mul_start(), pka_isr(), and rtimer_isr().
__STATIC_INLINE void NVIC_DecodePriority (uint32_t Priority, uint32_t PriorityGroup, uint32_t *const pPreemptPriority, uint32_t *const pSubPriority)
Decode Priority.
Decodes an interrupt priority value with a given priority group to preemptive priority value and subpriority value. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS) the smallest possible priority group is set.
Parameters
[in] Priority Priority value, which can be retrieved with the function NVIC_GetPriority().
[in] PriorityGroup Used priority group.
[out] pPreemptPriority Preemptive priority value (starting from 0).
[out] pSubPriority Subpriority value (starting from 0).
Definition at line 1611 of file core_cm3.h.
References __NVIC_PRIO_BITS.
__STATIC_INLINE void NVIC_DisableIRQ (IRQn_Type IRQn)
Disable External Interrupt.
Disables a device-specific interrupt in the NVIC interrupt controller.
Parameters
[in] IRQn External interrupt number. Value cannot be negative.
Definition at line 653 of file core_cm0.h.
References NVIC.
Referenced by aes_auth_crypt_get_result(), bignum_add_get_result(), bignum_cmp_get_result(), bignum_divide_get_result(), bignum_exp_mod_get_result(), bignum_inv_mod_get_result(), bignum_mod_get_result(), bignum_mul_get_result(), bignum_subtract_get_result(), config_user(), crypto_isr(), ecc_add_get_result(), ecc_mul_gen_pt_get_result(), ecc_mul_get_result(), pka_isr(), and rtimer_isr().
__STATIC_INLINE void NVIC_EnableIRQ (IRQn_Type IRQn)
Enable External Interrupt.
Enables a device-specific interrupt in the NVIC interrupt controller.
Parameters
[in] IRQn External interrupt number. Value cannot be negative.
Definition at line 642 of file core_cm0.h.
References NVIC.
Referenced by aes_auth_crypt_start(), bignum_add_start(), bignum_cmp_start(), bignum_divide_start(), bignum_exp_mod_start(), bignum_inv_mod_start(), bignum_mod_start(), bignum_mul_start(), bignum_subtract_start(), config_down(), config_left(), config_right(), config_select(), config_up(), config_user(), ecc_add_start(), ecc_mul_gen_pt_start(), ecc_mul_start(), init(), rtcc_set_alarm_time_date(), rtimer_arch_schedule(), uart_init(), and udma_init().
__STATIC_INLINE uint32_t NVIC_EncodePriority (uint32_t PriorityGroup, uint32_t PreemptPriority, uint32_t SubPriority)
Encode Priority.
Encodes the priority for an interrupt with the given priority group, preemptive priority value, and subpriority value. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set.
Parameters
[in] PriorityGroup Used priority group.
[in] PreemptPriority Preemptive priority value (starting from 0).
[in] SubPriority Subpriority value (starting from 0).
Returns
Encoded priority. Value can be used in the function NVIC_SetPriority().
Definition at line 1584 of file core_cm3.h.
References __NVIC_PRIO_BITS.
__STATIC_INLINE uint32_t NVIC_GetActive (IRQn_Type IRQn)
Get Active Interrupt.
Reads the active register in NVIC and returns the active bit.
Parameters
[in] IRQn Interrupt number.
Returns
0 Interrupt status is not active.
1 Interrupt status is active.
Definition at line 1524 of file core_cm3.h.
References NVIC.
__STATIC_INLINE uint32_t NVIC_GetPendingIRQ (IRQn_Type IRQn)
Get Pending Interrupt.
Reads the pending register in the NVIC and returns the pending bit for the specified interrupt.
Parameters
[in] IRQn Interrupt number.
Returns
0 Interrupt status is not pending.
1 Interrupt status is pending.
Definition at line 666 of file core_cm0.h.
References NVIC.
__STATIC_INLINE uint32_t NVIC_GetPriority (IRQn_Type IRQn)
Get Interrupt Priority.
Reads the priority of an interrupt. The interrupt number can be positive to specify an external (device specific) interrupt, or negative to specify an internal (core) interrupt.
Parameters
[in] IRQn Interrupt number.
Returns
Interrupt Priority. Value is aligned automatically to the implemented priority bits of the microcontroller.
Definition at line 725 of file core_cm0.h.
References __NVIC_PRIO_BITS, NVIC, and SCB.
__STATIC_INLINE uint32_t NVIC_GetPriorityGrouping (void)
Get Priority Grouping.
Reads the priority grouping field from the NVIC Interrupt Controller.
Returns
Priority grouping field (SCB->AIRCR [10:8] PRIGROUP field).
Definition at line 1441 of file core_cm3.h.
References SCB, SCB_AIRCR_PRIGROUP_Msk, and SCB_AIRCR_PRIGROUP_Pos.
__STATIC_INLINE uint32_t NVIC_IsIRQEnabled (IRQn_Type IRQn)
Get External Interrupt Enable State.
Returns whether a device-specific interrupt is enabled in the NVIC interrupt controller.
Parameters
[in] IRQn External interrupt number. Value cannot be negative.
Returns
0 Interrupt is disabled.
1 Interrupt is enabled.
Definition at line 631 of file core_cm0.h.
References NVIC.
__STATIC_INLINE void NVIC_SetPendingIRQ (IRQn_Type IRQn)
Set Pending Interrupt.
Sets the pending bit of an external interrupt.
Parameters
[in] IRQn Interrupt number. Value cannot be negative.
Definition at line 677 of file core_cm0.h.
References NVIC.
__STATIC_INLINE void NVIC_SetPriority (IRQn_Type IRQn, uint32_t priority)
Set Interrupt Priority.
Sets the priority of an interrupt.
Note
The priority cannot be set for every core interrupt.
Parameters
[in] IRQn Interrupt number.
[in] priority Priority to set.
Definition at line 701 of file core_cm0.h.
References __NVIC_PRIO_BITS, NVIC, and SCB.
Referenced by mtarch_init(), and SysTick_Config().
__STATIC_INLINE void NVIC_SetPriorityGrouping (uint32_t PriorityGroup)
Set Priority Grouping.
Sets the priority grouping field using the required unlock sequence. The parameter PriorityGroup is assigned to the field SCB->AIRCR [10:8] PRIGROUP field. Only values from 0..7 are used. In case of a conflict between priority grouping and available priority bits (__NVIC_PRIO_BITS), the smallest possible priority group is set.
Parameters
[in] PriorityGroup Priority grouping field.
Definition at line 1422 of file core_cm3.h.
References SCB, SCB_AIRCR_PRIGROUP_Msk, SCB_AIRCR_VECTKEY_Msk, and SCB_AIRCR_VECTKEY_Pos.
__STATIC_INLINE void NVIC_SystemReset (void)
System Reset.
Initiates a system reset request to reset the MCU.
Definition at line 743 of file core_cm0.h.
References __DSB(), __NOP(), SCB, SCB_AIRCR_SYSRESETREQ_Msk, and SCB_AIRCR_VECTKEY_Pos.
Referenced by watchdog_reboot().