Contiki-NG: uIP initialization functions
uIP initialization functions
uIP: the IPv6 stack
The uIP initialization functions are used for booting uIP.
Functions
void uip_init (void)
uIP initialization function.
void uip_setipid (uint16_t id)
uIP initialization function.
Detailed Description
The uIP initialization functions are used for booting uIP.
Function Documentation
void uip_init (void)
uIP initialization function.
This function should be called at boot up to initilize the uIP TCP/IP stack.
Definition at line 415 of file uip6.c.
References uip_mcast6_driver::init, uip_udp_conn::lport, uip_conn::tcpstateflags, uip_ds6_init(), uip_icmp6_init(), UIP_LISTENPORTS, uip_nd6_init(), UIP_TCP_CONNS, and UIP_UDP_CONNS.
void uip_setipid (uint16_t id)
uIP initialization function.
This function may be used at boot time to set the initial ip_id.