Contiki-NG: Link-layer addresses
Link-layer addresses
Link layer
The linkaddr module handles link-layer addresses.
Functions
void linkaddr_copy (linkaddr_t *dest, const linkaddr_t *from)
Copy a link-layer address.
int linkaddr_cmp (const linkaddr_t *addr1, const linkaddr_t *addr2)
Compare two link-layer addresses.
void linkaddr_set_node_addr (linkaddr_t *addr)
Set the address of the current node.
Variables
linkaddr_t linkaddr_node_addr
The link-layer address of the node.
linkaddr_t linkaddr_node_addr
The link-layer address of the node.
const linkaddr_t linkaddr_null
The null link-layer address.
Detailed Description
The linkaddr module handles link-layer addresses.
Function Documentation
int linkaddr_cmp (const linkaddr_t * addr1, const linkaddr_t * addr2)
Compare two link-layer addresses.
Parameters
addr1 The first address
addr2 The second address
Returns
Non-zero if the addresses are the same, zero if they are different
        This function compares two link-layer addresses and returns
        the result of the comparison. The function acts like
        the '==' operator and returns non-zero if the addresses
        are the same, and zero if the addresses are different.
Definition at line 69 of file linkaddr.c.
Referenced by find_handle(), log_lladdr_compact(), mac_sequence_is_duplicate(), mac_sequence_register_seqno(), packet_sent(), and packetbuf_holds_broadcast().
void linkaddr_copy (linkaddr_t * dest, const linkaddr_t * from)
Copy a link-layer address.
Parameters
dest The destination
from The source
        This function copies a link-layer address from one location
        to another.
Definition at line 63 of file linkaddr.c.
Referenced by frame802154_parse(), linkaddr_set_node_addr(), mac_sequence_register_seqno(), output(), platform_init_stage_three(), and sixp_nbr_alloc().
void linkaddr_set_node_addr (linkaddr_t * addr)
Set the address of the current node.
Parameters
addr The address
        This function sets the link-layer address of the node.
Definition at line 75 of file linkaddr.c.
References linkaddr_copy(), and linkaddr_node_addr.
Referenced by platform_init_stage_three().
Variable Documentation
linkaddr_t linkaddr_node_addr
The link-layer address of the node.
This variable contains the link-layer address of the node. This variable should not be changed directly; rather, the linkaddr_set_node_addr() function should be used.
Definition at line 48 of file linkaddr.c.
Referenced by linkaddr_set_node_addr(), platform_init_stage_three(), platform_init_stage_two(), sixtop_output(), and tsch_security_secure_frame().
linkaddr_t linkaddr_node_addr
The link-layer address of the node.
This variable contains the link-layer address of the node. This variable should not be changed directly; rather, the linkaddr_set_node_addr() function should be used.
Definition at line 48 of file linkaddr.c.
Referenced by linkaddr_set_node_addr(), platform_init_stage_three(), platform_init_stage_two(), sixtop_output(), and tsch_security_secure_frame().
const linkaddr_t linkaddr_null
The null link-layer address.
This variable contains the null link-layer address. The null address is used in route tables to indicate that the table entry is unused. Nodes with no configured address has the null address. Nodes with their node address set to the null address will have problems communicating with other nodes.
Referenced by frame802154_parse(), log_lladdr_compact(), output(), packet_sent(), and packetbuf_holds_broadcast().