Contiki-NG: Linked list library
Linked list library
Data structures
The linked list library provides a set of functions for manipulating linked lists.
Macros
#define LIST(name)
Declare a linked list.
#define LIST_STRUCT(name)
Declare a linked list inside a structure declaraction.
#define LIST_STRUCT_INIT(struct_ptr, name)
Initialize a linked list that is part of a structure.
Typedefs
typedef void ** list_t
The linked list type.
Functions
void list_init (list_t list)
Initialize a list.
void * list_head (list_t list)
Get a pointer to the first element of a list.
void list_copy (list_t dest, list_t src)
Duplicate a list.
void * list_tail (list_t list)
Get the tail of a list.
void list_add (list_t list, void *item)
Add an item at the end of a list.
void list_push (list_t list, void *item)
Add an item to the start of the list.
void * list_chop (list_t list)
Remove the last object on the list.
void * list_pop (list_t list)
Remove the first object on a list.
void list_remove (list_t list, void *item)
Remove a specific element from a list.
int list_length (list_t list)
Get the length of a list.
void list_insert (list_t list, void *previtem, void *newitem)
Insert an item after a specified item on the list.
void * list_item_next (void *item)
Get the next item following this item.
Detailed Description
The linked list library provides a set of functions for manipulating linked lists.
A linked list is made up of elements where the first element must be a pointer. This pointer is used by the linked list library to form lists of the elements.
Lists are declared with the LIST() macro. The declaration specifies the name of the list that later is used with all list functions.
Lists can be manipulated by inserting or removing elements from either sides of the list (list_push(), list_add(), list_pop(), list_chop()). A specified element can also be removed from inside a list with list_remove(). The head and tail of a list can be extracted using list_head() and list_tail(), respectively.
Macro Definition Documentation
#define LIST (name)
Value:
static void *LIST_CONCAT(name,_list) = NULL; \
         static list_t name = (list_t)&LIST_CONCAT(name,_list)
Declare a linked list.
This macro declares a linked list with the specified type. The type must be a structure (struct) with its first element being a pointer. This pointer is used by the linked list library to form the linked lists.
The list variable is declared as static to make it easy to use in a single C module without unnecessarily exporting the name to other modules.
Parameters
name The name of the list.
Definition at line 86 of file list.h.
#define LIST_STRUCT (name)
Value:
void *LIST_CONCAT(name,_list); \
         list_t name
Declare a linked list inside a structure declaraction.
This macro declares a linked list with the specified type. The type must be a structure (struct) with its first element being a pointer. This pointer is used by the linked list library to form the linked lists.
Internally, the list is defined as two items: the list itself and a pointer to the list. The pointer has the name of the parameter to the macro and the name of the list is a concatenation of the name and the suffix "_list". The pointer must point to the list for the list to work. Thus the list must be initialized before using.
The list is initialized with the LIST_STRUCT_INIT() macro.
Parameters
name The name of the list.
Definition at line 108 of file list.h.
#define LIST_STRUCT_INIT (struct_ptr, name)
Value:
do {                                                                \
       (struct_ptr)->name = &((struct_ptr)->LIST_CONCAT(name,_list));   \
       (struct_ptr)->LIST_CONCAT(name,_list) = NULL;                    \
       list_init((struct_ptr)->name);                                   \
    } while(0)
Initialize a linked list that is part of a structure.
This macro sets up the internal pointers in a list that has been defined as part of a struct. This macro must be called before using the list.
Parameters
struct_ptr A pointer to the struct
name The name of the list.
Definition at line 122 of file list.h.
Function Documentation
void list_add (list_t list, void * item)
Add an item at the end of a list.
This function adds an item to the end of the list.
Parameters
list The list.
item A pointer to the item to be added.
See Also
list_push()
Definition at line 143 of file list.c.
References list_remove(), and list_tail().
Referenced by aux_ctrl_register_consumer(), ctimer_reset(), ctimer_restart(), ctimer_set_with_process(), lpm_register_module(), mqtt_register(), rest_activate_resource(), rpl_ns_update_node(), sixp_trans_alloc(), uip_icmp6_echo_reply_callback_add(), uip_icmp6_register_input_handler(), uip_mcast6_route_add(), and uip_nameserver_update().
void * list_chop (list_t list)
Remove the last object on the list.
This function removes the last object on the list and returns it.
Parameters
list The list
Returns
The removed object
Definition at line 186 of file list.c.
void list_copy (list_t dest, list_t src)
Duplicate a list.
This function duplicates a list by copying the list reference, but not the elements.
Note
This function does not copy the elements of the list, but merely duplicates the pointer to the first element of the list.
Parameters
dest The destination list.
src The source list.
Definition at line 101 of file list.c.
void * list_head (list_t list)
Get a pointer to the first element of a list.
This function returns a pointer to the first element of the list. The element will not be removed from the list.
Parameters
list The list.
Returns
A pointer to the first element on the list.
See Also
list_tail()
Definition at line 83 of file list.c.
Referenced by aux_ctrl_power_down(), aux_ctrl_power_up(), ctimer_expired(), lpm_shutdown(), rpl_ns_free_all(), rpl_ns_get_node(), rpl_ns_node_head(), rpl_ns_periodic(), sixp_trans_find(), sixp_trans_init(), uip_mcast6_route_list_head(), uip_mcast6_route_lookup(), uip_mcast6_route_rm(), uip_nameserver_get(), uip_nameserver_next_expiration(), and uip_nameserver_update().
void list_init (list_t list)
Initialize a list.
This function initalizes a list. The list will be empty after this function has been called.
Parameters
list The list to be initialized.
Definition at line 66 of file list.c.
Referenced by ctimer_init(), lpm_init(), rest_init_engine(), rpl_ns_init(), sixp_trans_init(), and uip_mcast6_route_init().
void list_insert (list_t list, void * previtem, void * newitem)
Insert an item after a specified item on the list.
Parameters
list The list
previtem The item after which the new item should be inserted
newitem The new item that is to be inserted
Author
Adam Dunkels
        This function inserts an item right after a specified
        item on the list. This function is useful when using
        the list module to ordered lists.
        If previtem is NULL, the new item is placed at the
        start of the list.
Definition at line 303 of file list.c.
References list_push().
void * list_item_next (void * item)
Get the next item following this item.
Parameters
item A list item
Returns
A next item on the list
        This function takes a list item and returns the next
        item on the list, or NULL if there are no more items on
        the list. This function is used when iterating through
        lists.
Definition at line 325 of file list.c.
Referenced by rpl_ns_free_all(), rpl_ns_get_node(), rpl_ns_node_next(), rpl_ns_periodic(), uip_mcast6_route_lookup(), uip_mcast6_route_rm(), uip_nameserver_get(), uip_nameserver_next_expiration(), and uip_nameserver_update().
int list_length (list_t list)
Get the length of a list.
This function counts the number of elements on a specified list.
Parameters
list The list.
Returns
The length of the list.
Definition at line 275 of file list.c.
Referenced by uip_mcast6_route_count(), uip_nameserver_count(), and uip_nameserver_next_expiration().
void * list_pop (list_t list)
Remove the first object on a list.
This function removes the first object on the list and returns a pointer to it.
Parameters
list The list.
Returns
Pointer to the removed element of list.
Definition at line 218 of file list.c.
void list_remove (list_t list, void * item)
Remove a specific element from a list.
This function removes a specified element from the list.
Parameters
list The list.
item The item that is to be removed from the list.
Definition at line 240 of file list.c.
Referenced by aux_ctrl_unregister_consumer(), ctimer_stop(), list_add(), list_push(), lpm_unregister_module(), rpl_ns_free_all(), rpl_ns_periodic(), uip_icmp6_echo_reply_callback_rm(), uip_mcast6_route_rm(), and uip_nameserver_update().
void * list_tail (list_t list)
Get the tail of a list.
This function returns a pointer to the elements following the first element of a list. No elements are removed by this function.
Parameters
list The list
Returns
A pointer to the element after the first element on the list.
See Also
list_head()
Definition at line 118 of file list.c.
Referenced by list_add().