Contiki-NG: cc2538 Random Number Generator
cc2538 Random Number Generator
The TI cc2538 System-on-Chip
Driver for the cc2538 Hardware Random Number Generator.
Files
file random.c
Random number generator routines exploiting the cc2538 hardware capabilities.
Functions
unsigned short random_rand (void)
Generates a new random number using the cc2538 RNG.
void random_init (unsigned short seed)
Seed the cc2538 random number generator.
Detailed Description
Driver for the cc2538 Hardware Random Number Generator.
Function Documentation
void random_init (unsigned short seed)
Seed the cc2538 random number generator.
Parameters
seed Ignored. It's here because the function prototype is in core.
        We form a seed for the RNG by sampling IF_ADC as
        discussed in the user guide.
        Seeding with this method should not be done during
        normal radio operation. Thus, use this function before
        initialising the network.
Note
Must not be called after the RF driver has been initialised and is in normal operation. If it is absolutely necessary to do so, the radio will need re-initialised.
Definition at line 84 of file random.c.
Referenced by main().
unsigned short random_rand (void)
Generates a new random number using the cc2538 RNG.
Returns
The random number.
Definition at line 58 of file random.c.
Referenced by rpl_timers_schedule_dao(), rpl_timers_schedule_periodic_dis(), uip_ds6_addr_add(), uip_ds6_compute_reachable_time(), and uip_ds6_init().