Contiki-NG: CoAP transport implementation for uIP
CoAP transport implementation for uIP
IoT networking » Application-layer protocols and profiles » An implementation of CoAP » CoAP transport API
This is an implementation of CoAP transport and CoAP endpoint over uIP with DTLS support.
Functions
void coap_endpoint_log (const coap_endpoint_t *ep)
Print a CoAP endpoint via the logging module.
void coap_endpoint_print (const coap_endpoint_t *ep)
Print a CoAP endpoint.
int coap_endpoint_snprint (char *buf, size_t size, const coap_endpoint_t *ep)
Print a CoAP endpoint to a string.
void coap_endpoint_copy (coap_endpoint_t *destination, const coap_endpoint_t *from)
Copy a CoAP endpoint from one memory area to another.
int coap_endpoint_cmp (const coap_endpoint_t *e1, const coap_endpoint_t *e2)
Compare two CoAP endpoints.
int coap_endpoint_parse (const char *text, size_t size, coap_endpoint_t *ep)
Parse a CoAP endpoint.
int coap_endpoint_is_secure (const coap_endpoint_t *ep)
Check if a CoAP endpoint is secure (encrypted).
int coap_endpoint_is_connected (const coap_endpoint_t *ep)
Check if a CoAP endpoint is connected.
int coap_endpoint_connect (coap_endpoint_t *ep)
Request a connection to a CoAP endpoint.
void coap_endpoint_disconnect (coap_endpoint_t *ep)
Request that any connection to a CoAP endpoint is discontinued.
uint8_t * coap_databuf (void)
Returns a common data buffer that can be used when generating CoAP messages for transmission.
void coap_transport_init (void)
Initialize the CoAP transport.
int coap_sendto (const coap_endpoint_t *ep, const uint8_t *data, uint16_t length)
Send a message to the specified CoAP endpoint.
Detailed Description
This is an implementation of CoAP transport and CoAP endpoint over uIP with DTLS support.
Function Documentation
uint8_t* coap_databuf (void)
Returns a common data buffer that can be used when generating CoAP messages for transmission.
The buffer size is at least COAP_MAX_PACKET_SIZE bytes.
In Contiki-NG, this corresponds to the uIP buffer.
Returns
A pointer to a data buffer where a CoAP message can be stored.
Definition at line 337 of file coap-uip.c.
References uip_appdata.
Referenced by coap_separate_accept().
int coap_endpoint_cmp (const coap_endpoint_t * e1, const coap_endpoint_t * e2)
Compare two CoAP endpoints.
Parameters
e1 A pointer to the first CoAP endpoint.
e2 A pointer to the second CoAP endpoint.
Returns
Non-zero if the endpoints are identical and zero otherwise.
Definition at line 174 of file coap-uip.c.
int coap_endpoint_connect (coap_endpoint_t * ep)
Request a connection to a CoAP endpoint.
Parameters
ep A pointer to a CoAP endpoint.
Returns
Returns zero if an error occured and non-zero otherwise.
Definition at line 302 of file coap-uip.c.
void coap_endpoint_copy (coap_endpoint_t * dest, const coap_endpoint_t * src)
Copy a CoAP endpoint from one memory area to another.
Parameters
dest A pointer to a CoAP endpoint to copy to.
src A pointer to a CoAP endpoint to copy from.
Definition at line 165 of file coap-uip.c.
References uip_ipaddr_copy.
Referenced by coap_separate_accept().
void coap_endpoint_disconnect (coap_endpoint_t * ep)
Request that any connection to a CoAP endpoint is discontinued.
Parameters
ep A pointer to a CoAP endpoint.
Definition at line 327 of file coap-uip.c.
int coap_endpoint_is_connected (const coap_endpoint_t * ep)
Check if a CoAP endpoint is connected.
Parameters
ep A pointer to a CoAP endpoint.
Returns
Returns non-zero if the endpoint is connected and zero otherwise.
Definition at line 264 of file coap-uip.c.
References rpl_get_any_dag().
Referenced by coap_sendto().
int coap_endpoint_is_secure (const coap_endpoint_t * ep)
Check if a CoAP endpoint is secure (encrypted).
Parameters
ep A pointer to a CoAP endpoint.
Returns
Returns non-zero if the endpoint is secure and zero otherwise.
Definition at line 258 of file coap-uip.c.
Referenced by coap_sendto().
void coap_endpoint_log (const coap_endpoint_t * ep)
Print a CoAP endpoint via the logging module.
Parameters
ep A pointer to the CoAP endpoint to log.
Definition at line 105 of file coap-uip.c.
References log_6addr().
int coap_endpoint_parse (const char * text, size_t size, coap_endpoint_t * ep)
Parse a CoAP endpoint.
Parameters
text The string to parse.
size The max number of characters in the string.
ep A pointer to the CoAP endpoint to write to.
Returns
Returns non-zero if the endpoint was successfully parsed and zero otherwise.
Secure CoAP should use a different port but for now the same port is used.
Definition at line 212 of file coap-uip.c.
References start(), UIP_HTONS, UIP_IP_BUF, uip_ipaddr_copy, and uiplib_ipaddrconv.
void coap_endpoint_print (const coap_endpoint_t * ep)
Print a CoAP endpoint.
Parameters
ep A pointer to the CoAP endpoint to print.
Definition at line 121 of file coap-uip.c.
References uiplib_ipaddr_print().
int coap_endpoint_snprint (char * str, size_t size, const coap_endpoint_t * ep)
Print a CoAP endpoint to a string.
The output is always null-terminated unless size is zero.
Parameters
str The string to write to.
size The max number of characters to write.
ep A pointer to the CoAP endpoint to print.
Returns
Returns the number of characters needed for the output excluding the ending null-terminator or negative if an error occurred.
Definition at line 137 of file coap-uip.c.
References uiplib_ipaddr_snprint().
int coap_sendto (const coap_endpoint_t * ep, const uint8_t * data, uint16_t len)
Send a message to the specified CoAP endpoint.
Parameters
ep A pointer to a CoAP endpoint
data A pointer to data to send
len The size of the data to send
Returns
The number of bytes sent or negative if an error occurred.
Definition at line 384 of file coap-uip.c.
References coap_endpoint_is_connected(), coap_endpoint_is_secure(), coap_set_keystore(), uip_udp_conn::lport, PROCESS_BEGIN, PROCESS_END, PROCESS_THREAD(), PROCESS_YIELD, tcpip_event, udp_bind, udp_new(), and uip_newdata.
Referenced by coap_separate_accept().
void coap_transport_init (void)
Initialize the CoAP transport.
This function initializes the CoAP transport implementation and should only be called by the CoAP engine.
Definition at line 343 of file coap-uip.c.
References coap_keystore_simple_init(), process_start(), uip_appdata, uip_datalen, and UIP_IP_BUF.