Contiki-NG: cc2538 AES-CBC
cc2538 AES-CBC
cc2538 AES
Driver for the cc2538 AES-CBC mode of the security core.
Files
file cbc.c
Implementation of the cc2538 AES-CBC driver.
file cbc.h
Header file for the cc2538 AES-CBC driver.
AES-CBC constants
#define CBC_IV_LEN AES_IV_LEN
AES-CBC functions
uint8_t cbc_crypt_start (uint8_t encrypt, uint8_t key_area, const void *iv, const void *mdata_in, void *mdata_out, uint16_t mdata_len, struct process *process)
Starts a CBC crypto operation.
int8_t cbc_crypt_check_status (void)
Checks the status of the CBC crypto operation.
Detailed Description
Driver for the cc2538 AES-CBC mode of the security core.
Function Documentation
int8_t cbc_crypt_check_status (void)
Checks the status of the CBC crypto operation.
Returns
CRYPTO_PENDING if operation still pending, CRYPTO_SUCCESS if successful, or CRYPTO/AES/CBC error code
Note
This function must be called only after cbc_crypt_start().
Definition at line 60 of file cbc.c.
References aes_auth_crypt_check_status(), and aes_auth_crypt_get_result().
uint8_t cbc_crypt_start (uint8_t encrypt, uint8_t key_area, const void * iv, const void * mdata_in, void * mdata_out, uint16_t mdata_len, struct process * process)
Starts a CBC crypto operation.
Parameters
encrypt true to encrypt, or false to decrypt
key_area Area in Key RAM where the key is stored (0 to AES_KEY_AREAS - 1)
iv Pointer to 128-bit initialization vector
mdata_in Pointer to input message in SRAM
mdata_out Pointer to output message in SRAM (may be mdata_in)
mdata_len Length of message in octets
process Process to be polled upon completion of the operation, or NULL
Returns
CRYPTO_SUCCESS if successful, or CRYPTO/AES/CBC error code
Definition at line 45 of file cbc.c.
References AES_AES_CTRL_CBC, AES_AES_CTRL_DIRECTION_ENCRYPT, and aes_auth_crypt_start().