Contiki-NG: The Contiki-NG main function
The Contiki-NG main function
System functions
A platform-independent main function.
Files
file contiki-main.c
Implementation of Contiki-NG's main routine.
file platform.h
Header file for the Contiki-NG main routine.
Macros
#define PLATFORM_PROVIDES_MAIN_LOOP 0
Controls whether the platform provides a custom main loop.
#define PLATFORM_MAIN_ACCEPTS_ARGS 0
Controls whether the main function accepts arguments.
Functions
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
void platform_init_stage_two (void)
Stage 2 of platform driver initialisation.
void platform_init_stage_three (void)
Final stage of platform driver initialisation.
void platform_idle (void)
The platform's idle/sleep function.
void platform_main_loop (void)
The platform's main loop, if provided.
void platform_process_args (int argc, char **argv)
Allow the platform to process main's command line arguments.
Detailed Description
A platform-independent main function.
Contiki-NG provides a modular, platform-independent main function that aims to support all hardware ports.
In a nutshell, the main routine has the following steps below:
Calls a platform-provided function to initialise basic hardware drivers
Initialises core Contiki-NG modules, such as the process scheduler and timers
Calls a platform-provided function to initialise more hardware drivers
Initialises the network stack and TCP/IP
Calls a platform-provided function to initialise any remaining drivers
Enters the main loop
The main loop will service all pending events and will then call a platform-dependent function to put the hardware in a low-power state.
For more detail of which hardware driver should be implemented in which stage of the boot process, see the documentation of platform_init_stage_one(), platform_init_stage_two() and platform_init_stage_three()
Macro Definition Documentation
#define PLATFORM_MAIN_ACCEPTS_ARGS 0
Controls whether the main function accepts arguments.
By default our main does not accept arguments. However, when running on native targets, command line arguments to main are required.
Definition at line 95 of file platform.h.
#define PLATFORM_PROVIDES_MAIN_LOOP 0
Controls whether the platform provides a custom main loop.
By default we will use the main loop provided here. This however does not work for some platforms, so we allow them to override it.
Definition at line 83 of file platform.h.
Function Documentation
void platform_idle (void)
The platform's idle/sleep function.
This function will be called as part of the main loop after all events have been serviced. This is where you will normally put the device in a low-power state. Waking up from this state and tidying up the hardware is the port's responsibility.
It is the port developer's responsibility to implement this function.
Definition at line 185 of file platform.c.
References CLOCK_SECOND, clock_seconds(), lpm_drop(), process_nevents(), timer_expired(), timer_reset(), watchdog_periodic(), watchdog_start(), and watchdog_stop().
Referenced by platform_main_loop().
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
This function will get called early on in the Contiki-NG boot sequence.
In this function, the platform should initialise all core device drivers. For example, this is where you will normally want to initialise hardware timers/clocks, GPIO, LEDS. Normally this function will also enable the MCU's global interrupt.
The Contiki-NG process scheduler, software clocks and timers will not be running yet, so any platform drivers that rely on it should not be initialised here. Instead, they should be initialised in platform_init_stage_two() or in platform_init_stage_three()
It is the port developer's responsibility to implement this function.
See also
platform_init_stage_two()
platform_init_stage_three()
Definition at line 114 of file platform.c.
References board_init(), button_hal_init(), clock_init(), gpio_hal_init(), LEDS_ALL, leds_init(), leds_on(), lpm_init(), oscillators_select_lf_xosc(), random_init(), rtimer_init(), soc_init(), soc_rtc_init(), and uip_lladdr.
void platform_init_stage_three (void)
Final stage of platform driver initialisation.
Initialisation of platform-specific drivers that require networking to be running. This is also a good place to initialise sensor drivers.
When this function returns, the main routine will assume that the hardware is fully initialised.
It is the port developer's responsibility to implement this function.
See also
platform_init_stage_one()
platform_init_stage_two()
Definition at line 169 of file platform.c.
References adc_init(), ble_advertising_start(), ble_get_mac(), board_init(), CLOCK_SECOND, DEVICE_NAME, eeprom_init(), LEDS_ALL, leds_off(), linkaddr_copy(), linkaddr_node_addr, linkaddr_set_node_addr(), process_start(), serial_line_input_byte(), soc_print_info(), and timer_set().
void platform_init_stage_two (void)
Stage 2 of platform driver initialisation.
This function will be called by the Contiki-NG boot sequence after parts of the core have been initialised. More specifically, when this function gets called, the following modules will be running:
Software clock
Process scheduler
Event timer (etimer)
Callback timer (ctimer)
rtimer
Energest (if enabled)
Therefore, any platform driver that relies on any of the above modules should be initialised here or in platform_init_stage_three(), but not in platform_init_stage_one()
The Contiki-NG network stack will not be running yet, so any platform drivers that rely on networking should not be initialised here.
When this function returns, the main routine will assume that the platform has enabled character I/O and can print to console. When this function returns, main() will attempt to initialise the network stack. For this to work properly, this function should also populate linkaddr_node_addr.
It is the port developer's responsibility to implement this function.
See also
platform_init_stage_one()
platform_init_stage_three()
Definition at line 123 of file platform.c.
References ble_advertising_init(), ble_eui64_addr_cpy_to(), ble_stack_init(), button_hal_init(), cc26xx_uart_init(), cc26xx_uart_set_input(), crypto_disable(), crypto_init(), DEVICE_NAME, i2c_init(), ieee_addr_cpy_to(), INTERRUPTS_ENABLE, leds_off(), leds_on(), linkaddr_node_addr, random_init(), SERIAL_LINE_CONF_UART, serial_line_input_byte(), uart0_init(), uart1_init(), uart_init(), uart_set_input(), udma_init(), uip_lladdr, usb_serial_init(), and usb_serial_set_input().
void platform_main_loop (void)
The platform's main loop, if provided.
If the platform developer wishes to do so, it is possible to override the main loop provided by Contiki-NG's core. To do so, define PLATFORM_CONF_PROVIDES_MAIN_LOOP as 1.
It is the port developer's responsibility to implement this function.
Definition at line 192 of file platform.c.
References clock_seconds(), etimer_request_poll(), leds_init(), platform_idle(), platform_main_loop(), process_nevents(), process_run(), uart0_init(), watchdog_init(), watchdog_periodic(), watchdog_start(), and watchdog_stop().
Referenced by platform_main_loop().
void platform_process_args (int argc, char ** argv)
Allow the platform to process main's command line arguments.
If the platform wishes main() to accept arguments, then the Contiki-NG main will call this function here so that the platform can process/store those arguments.
This function will only get called if PLATFORM_MAIN_ACCEPTS_ARGS is non-zero.
It is the port developer's responsibility to implement this function.
Definition at line 235 of file platform.c.