Contiki-NG: Cache Functions
Cache Functions
Functions and Instructions Reference
Functions that configure Instruction and Data cache.
Functions
__STATIC_INLINE void SCB_EnableICache (void)
Enable I-Cache.
__STATIC_INLINE void SCB_DisableICache (void)
Disable I-Cache.
__STATIC_INLINE void SCB_InvalidateICache (void)
Invalidate I-Cache.
__STATIC_INLINE void SCB_EnableDCache (void)
Enable D-Cache.
__STATIC_INLINE void SCB_DisableDCache (void)
Disable D-Cache.
__STATIC_INLINE void SCB_InvalidateDCache (void)
Invalidate D-Cache.
__STATIC_INLINE void SCB_CleanDCache (void)
Clean D-Cache.
__STATIC_INLINE void SCB_CleanInvalidateDCache (void)
Clean & Invalidate D-Cache.
__STATIC_INLINE void SCB_InvalidateDCache_by_Addr (uint32_t *addr, int32_t dsize)
D-Cache Invalidate by address.
__STATIC_INLINE void SCB_CleanDCache_by_Addr (uint32_t *addr, int32_t dsize)
D-Cache Clean by address.
__STATIC_INLINE void SCB_CleanInvalidateDCache_by_Addr (uint32_t *addr, int32_t dsize)
D-Cache Clean and Invalidate by address.
Detailed Description
Functions that configure Instruction and Data cache.
Function Documentation
__STATIC_INLINE void SCB_CleanDCache (void)
Clean D-Cache.
Cleans D-Cache
Definition at line 2246 of file core_cm7.h.
References __DSB(), __ISB(), SCB, SCB_DCCSW_SET_Msk, SCB_DCCSW_SET_Pos, SCB_DCCSW_WAY_Msk, and SCB_DCCSW_WAY_Pos.
__STATIC_INLINE void SCB_CleanDCache_by_Addr (uint32_t * addr, int32_t dsize)
D-Cache Clean by address.
Cleans D-Cache for the given address
Parameters
[in] addr address (aligned to 32-byte boundary)
[in] dsize size of memory block (in number of bytes)
Definition at line 2345 of file core_cm7.h.
References __DSB(), __ISB(), and SCB.
__STATIC_INLINE void SCB_CleanInvalidateDCache (void)
Clean & Invalidate D-Cache.
Cleans and Invalidates D-Cache
Definition at line 2281 of file core_cm7.h.
References __DSB(), __ISB(), SCB, SCB_DCCISW_SET_Msk, SCB_DCCISW_SET_Pos, SCB_DCCISW_WAY_Msk, and SCB_DCCISW_WAY_Pos.
__STATIC_INLINE void SCB_CleanInvalidateDCache_by_Addr (uint32_t * addr, int32_t dsize)
D-Cache Clean and Invalidate by address.
Cleans and invalidates D_Cache for the given address
Parameters
[in] addr address (aligned to 32-byte boundary)
[in] dsize size of memory block (in number of bytes)
Definition at line 2372 of file core_cm7.h.
References __DSB(), __ISB(), and SCB.
__STATIC_INLINE void SCB_DisableDCache (void)
Disable D-Cache.
Turns off D-Cache
Definition at line 2174 of file core_cm7.h.
References __DSB(), __ISB(), SCB, SCB_CCR_DC_Msk, SCB_DCCISW_SET_Msk, SCB_DCCISW_SET_Pos, SCB_DCCISW_WAY_Msk, and SCB_DCCISW_WAY_Pos.
__STATIC_INLINE void SCB_DisableICache (void)
Disable I-Cache.
Turns off I-Cache
Definition at line 2103 of file core_cm7.h.
References __DSB(), __ISB(), SCB, and SCB_CCR_IC_Msk.
__STATIC_INLINE void SCB_EnableDCache (void)
Enable D-Cache.
Turns on D-Cache
Definition at line 2136 of file core_cm7.h.
References __DSB(), __ISB(), SCB, SCB_CCR_DC_Msk, SCB_DCISW_SET_Msk, SCB_DCISW_SET_Pos, SCB_DCISW_WAY_Msk, and SCB_DCISW_WAY_Pos.
__STATIC_INLINE void SCB_EnableICache (void)
Enable I-Cache.
Turns on I-Cache
Definition at line 2086 of file core_cm7.h.
References __DSB(), __ISB(), SCB, and SCB_CCR_IC_Msk.
__STATIC_INLINE void SCB_InvalidateDCache (void)
Invalidate D-Cache.
Invalidates D-Cache
Definition at line 2211 of file core_cm7.h.
References __DSB(), __ISB(), SCB, SCB_DCISW_SET_Msk, SCB_DCISW_SET_Pos, SCB_DCISW_WAY_Msk, and SCB_DCISW_WAY_Pos.
__STATIC_INLINE void SCB_InvalidateDCache_by_Addr (uint32_t * addr, int32_t dsize)
D-Cache Invalidate by address.
Invalidates D-Cache for the given address
Parameters
[in] addr address (aligned to 32-byte boundary)
[in] dsize size of memory block (in number of bytes)
Definition at line 2318 of file core_cm7.h.
References __DSB(), __ISB(), and SCB.
__STATIC_INLINE void SCB_InvalidateICache (void)
Invalidate I-Cache.
Invalidates I-Cache
Definition at line 2120 of file core_cm7.h.
References __DSB(), __ISB(), and SCB.