Contiki-NG: memb: Memory block management functions
memb: Memory block management functions
Memory functions
The memory block allocation routines provide a simple yet powerful set of functions for managing a set of memory blocks of fixed size.
Files
file memb.c
Memory block allocation routines.
file memb.h
    Memory block allocation routines.
Macros
#define MEMB(name, structure, num)
Declare a memory block.
Functions
void memb_init (struct memb *m)
Initialize a memory block that was declared with MEMB().
void * memb_alloc (struct memb *m)
Allocate a memory block from a block of memory declared with MEMB().
char memb_free (struct memb *m, void *ptr)
Deallocate a memory block from a memory block previously declared with MEMB().
Detailed Description
The memory block allocation routines provide a simple yet powerful set of functions for managing a set of memory blocks of fixed size.
A set of memory blocks is statically declared with the MEMB() macro. Memory blocks are allocated from the declared memory by the memb_alloc() function, and are deallocated with the memb_free() function.
Macro Definition Documentation
#define MEMB (name, structure, num)
Value:
static char CC_CONCAT(name,_memb_count)[num]; \
        static structure CC_CONCAT(name,_memb_mem)[num]; \
        static struct memb name = {sizeof(structure), num, \
                                          CC_CONCAT(name,_memb_count), \
                                          (void *)CC_CONCAT(name,_memb_mem)}
Declare a memory block.
This macro is used to statically declare a block of memory that can be used by the block allocation functions. The macro statically declares a C array with a size that matches the specified number of blocks and their individual sizes.
Example:
MEMB(connections, struct connection, 16);
Parameters
name The name of the memory block (later used with memb_init(), memb_alloc() and memb_free()).
structure The name of the struct that the memory block holds
num The total number of memory chunks in the block.
Definition at line 89 of file memb.h.
Function Documentation
void * memb_alloc (struct memb * m)
Allocate a memory block from a block of memory declared with MEMB().
Parameters
m A memory block previously declared with MEMB().
Definition at line 59 of file memb.c.
Referenced by rpl_ns_update_node(), sixp_trans_alloc(), uip_mcast6_route_add(), and uip_nameserver_update().
char memb_free (struct memb * m, void * ptr)
Deallocate a memory block from a memory block previously declared with MEMB().
Parameters
m m A memory block previously declared with MEMB().
ptr A pointer to the memory block that is to be deallocated.
Returns
The new reference count for the memory block (should be 0 if successfully deallocated) or -1 if the pointer "ptr" did not point to a legal memory block.
Definition at line 79 of file memb.c.
Referenced by rpl_ns_free_all(), rpl_ns_periodic(), uip_mcast6_route_rm(), and uip_nameserver_update().
void memb_init (struct memb * m)
Initialize a memory block that was declared with MEMB().
Parameters
m A memory block previously declared with MEMB().
Definition at line 52 of file memb.c.
Referenced by rpl_ns_init(), sixp_trans_init(), and uip_mcast6_route_init().