Contiki-NG: Software Clock
Software Clock
Hardware support » CPUs » The TI CC13xx and CC26xx Systems-on-Chip » CC13xx/CC26xx clock and timer subsystem
Implementation of the clock module for the CC26xx and CC13xx.
Files
file clock.c
Software clock implementation for the TI CC13xx/CC26xx.
Functions
void clock_init (void)
Initialize the clock library.
clock_time_t clock_time (void)
Get the current clock time.
unsigned long clock_seconds (void)
Get the current value of the platform seconds.
void clock_wait (clock_time_t i)
Wait for a given number of ticks.
void clock_delay_usec (uint16_t len)
Delay a given number of microseconds.
void clock_delay (unsigned int i)
Obsolete delay function but we implement it here since some code still uses it.
Detailed Description
Implementation of the clock module for the CC26xx and CC13xx.
The software clock uses the facilities provided by the AON RTC driver
Function Documentation
void clock_delay_usec (uint16_t dt)
Delay a given number of microseconds.
Parameters
dt How many microseconds to delay.
Note
Interrupts could increase the delay by a variable amount.
Definition at line 173 of file clock.c.
void clock_init (void)
Initialize the clock library.
This function initializes the clock library and should be called from the main() function of the system.
Initialize the clock library.
We initialise the SysTick to fire 128 interrupts per second, giving us a value of 128 for CLOCK_SECOND
We also initialise GPT0:Timer A, which is used by clock_delay_usec(). We use 16-bit range (individual), count-down, one-shot, no interrupts. The prescaler is computed according to the system clock in order to get 1 tick per usec.
Definition at line 61 of file clock.c.
References CLOCK_SECOND.
unsigned long clock_seconds (void)
Get the current value of the platform seconds.
This could be the number of seconds since startup, or since a standard epoch.
Returns
The value.
Definition at line 146 of file clock.c.
clock_time_t clock_time (void)
Get the current clock time.
This function returns the current system clock time.
Returns
The current clock time, measured in system ticks.
Definition at line 128 of file clock.c.
References etimer_pending(), and etimer_request_poll().
void clock_wait (clock_time_t t)
Wait for a given number of ticks.
Parameters
t How many ticks.
Definition at line 164 of file clock.c.
References clock_time(), and start().