Contiki-NG: An implementation of CoAP
An implementation of CoAP
IoT networking » Application-layer protocols and profiles
This is an implementation of the Constrained Application Protocol.
Modules
CoAP keystore API
The CoAP keystore API defines a common interface for retrieving authorization information for CoAP/DTLS.
CoAP timer API
The CoAP timer API defines a common interface for CoAP timer and time functionality.
CoAP transport API
The CoAP transport API defines a common interface for sending/receiving CoAP messages.
Macros
#define COAP_MAX_PACKET_SIZE (COAP_MAX_HEADER_SIZE + COAP_MAX_CHUNK_SIZE)
The max size of the CoAP messages.
Enumerations
Functions
int coap_block1_handler (coap_message_t *request, coap_message_t *response, uint8_t *target, size_t *len, size_t max_len)
Block 1 support within a coap-ressource.
void coap_activate_resource (coap_resource_t *resource, const char *path)
Makes a resource available under the given URI path.
coap_resource_t * coap_get_first_resource (void)
Returns the first of registered CoAP resources.
coap_resource_t * coap_get_next_resource (coap_resource_t *resource)
Returns the next registered CoAP resource.
void coap_log_string (const char *text, size_t len)
Logs a CoAP string that has a length but might not be 0-terminated.
void coap_separate_reject ()
Reject a request that would require a separate response with an error message.
void coap_separate_accept (coap_message_t *coap_req, coap_separate_t *separate_store)
Initiate a separate response with an empty ACK.
Detailed Description
This is an implementation of the Constrained Application Protocol.
Function Documentation
void coap_activate_resource (coap_resource_t * resource, const char * path)
Makes a resource available under the given URI path.
Resources wanted to be accessible should be activated with the following code.
Parameters
resource A pointer to a resource implementation
path The URI path string for this resource
The resource implementation must be imported first using the extern keyword. The build system takes care of compiling every *.c file in the ./resources/ sub-directory (see example Makefile).
Parameters
resource A CoAP resource defined through the RESOURCE macros.
path The local URI path where to provide the resource.
Definition at line 400 of file coap-engine.c.
References coap_timer_set(), coap_timer_set_callback(), coap_timer_set_user_data(), and list_add().
int coap_block1_handler (coap_message_t * request, coap_message_t * response, uint8_t * target, size_t * len, size_t max_len)
Block 1 support within a coap-ressource.
This function will help you to use block 1. If target is null error handling and response configuration is active. On return value 0, the last block was recived, while on return value 1 more blocks will follow. With target, len and maxlen this function will assemble the blocks.
You can find an example in: examples/er-rest-example/resources/res-b1-sep-b2.c
Parameters
request Request pointer from the handler
response Response pointer from the handler
target Pointer to the buffer where the request payload can be assembled
len Pointer to the variable, where the function stores the actual length
max_len Length of the "target"-Buffer
Returns
0 if initialisation was successful -1 if initialisation failed
Definition at line 79 of file coap-block1.c.
coap_resource_t * coap_get_first_resource (void)
Returns the first of registered CoAP resources.
Returns
The first registered CoAP resource or NULL if none exists.
Definition at line 425 of file coap-engine.c.
References list_head().
coap_resource_t * coap_get_next_resource (coap_resource_t * resource)
Returns the next registered CoAP resource.
Returns
The next resource or NULL if no more exists.
Definition at line 431 of file coap-engine.c.
References coap_timer_get_user_data(), coap_timer_set(), list_head(), and list_item_next().
void coap_log_string (const char * text, size_t len)
Logs a CoAP string that has a length but might not be 0-terminated.
Parameters
text The CoAP string
len The number of characters in the CoAP string
Definition at line 47 of file coap-log.c.
void coap_separate_accept (coap_message_t * coap_req, coap_separate_t * separate_store)
Initiate a separate response with an empty ACK.
Parameters
coap_req The request to accept
separate_store A pointer to the data structure that will store the relevant information for the response
When the server does not have enough resources left to store the information for a separate response or otherwise cannot execute the resource handler, this function will respond with 5.03 Service Unavailable. The client can then retry later.
Definition at line 86 of file coap-separate.c.
References coap_databuf(), coap_endpoint_copy(), and coap_sendto().
void coap_separate_reject ()
Reject a request that would require a separate response with an error message.
When the server does not have enough resources left to store the information for a separate response or otherwise cannot execute the resource handler, this function will respond with 5.03 Service Unavailable. The client can then retry later.
Definition at line 67 of file coap-separate.c.