Contiki-NG: SensorTag 2.0 Pressure Sensor
SensorTag 2.0 Pressure Sensor
Sensortag CC1350/CC2650 common
Due to the time required for the sensor to startup, this driver is meant to be used in an asynchronous fashion.
Files
file bmp-280-sensor.c
Driver for the Sensortag BMP280 Altimeter / Pressure Sensor.
file bmp-280-sensor.h
Header file for the Sensortag BMP280 Altimeter / Pressure Sensor.
Functions
static void init (void)
Initalise the sensor.
static void enable_sensor (bool enable)
Enable/disable measurements.
static bool read_data (uint8_t *data)
Read temperature and pressure data.
static void convert (uint8_t *data, int32_t *temp, uint32_t *press)
Convert raw data to values in degrees C (temp) and Pascal (pressure)
static int value (int type)
Returns a reading from the sensor.
static int configure (int type, int enable)
Configuration function for the BMP280 sensor.
static int status (int type)
Returns the status of the sensor.
Detailed Description
Due to the time required for the sensor to startup, this driver is meant to be used in an asynchronous fashion.
The caller must first activate the sensor by calling SENSORS_ACTIVATE(). This will trigger the sensor's startup sequence, but the call will not wait for it to complete so that the CPU can perform other tasks or drop to a low power mode.
Once the sensor is stable, the driver will generate a sensors_changed event.
We take readings in "Forced" mode. In this mode, the BMP will take a single measurement and it will then automatically go to sleep.
SENSORS_ACTIVATE must be called again to trigger a new reading cycle
Function Documentation
static int configure (int type, int enable) static
Configuration function for the BMP280 sensor.
Parameters
type Activate, enable or disable the sensor. See below
enable When type == SENSORS_HW_INIT we turn on the hardware When type == SENSORS_ACTIVE and enable==1 we enable the sensor When type == SENSORS_ACTIVE and enable==0 we disable the sensor
Definition at line 342 of file bmp-280-sensor.c.
References ctimer_set(), ctimer_stop(), enable_sensor(), and init().
static void convert (uint8_t * data, int32_t * temp, uint32_t * press) static
Convert raw data to values in degrees C (temp) and Pascal (pressure)
Parameters
data Pointer to a buffer that holds raw sensor data
temp Pointer to a variable where the converted temperature will be written
press Pointer to a variable where the converted pressure will be written
Definition at line 227 of file bmp-280-sensor.c.
Referenced by value().
static void enable_sensor (bool enable) static
Enable/disable measurements.
Parameters
enable 0: disable, enable otherwise
Returns
none
Definition at line 182 of file bmp-280-sensor.c.
References sensor_common_write_reg().
Referenced by configure().
static bool read_data (uint8_t * data) static
Read temperature and pressure data.
Parameters
data Pointer to a buffer where temperature and pressure will be written (6 bytes)
Returns
True if valid data could be retrieved
Definition at line 204 of file bmp-280-sensor.c.
References sensor_common_read_reg(), and sensor_common_set_error_data().
Referenced by value().
static int status (int type) static
Returns the status of the sensor.
Parameters
type SENSORS_ACTIVE or SENSORS_READY
Returns
1 if the sensor is enabled
Definition at line 377 of file bmp-280-sensor.c.
static int value (int type) static
Returns a reading from the sensor.
Parameters
type BMP_280_SENSOR_TYPE_TEMP or BMP_280_SENSOR_TYPE_PRESS
Returns
Temperature (centi degrees C) or Pressure (Pascal).
Definition at line 293 of file bmp-280-sensor.c.
References convert(), and read_data().