Contiki-NG: CoAP keystore API
CoAP keystore API
IoT networking » Application-layer protocols and profiles » An implementation of CoAP
The CoAP keystore API defines a common interface for retrieving authorization information for CoAP/DTLS.
Data Structures
struct coap_keystore_psk_entry_t
The structure of a CoAP pre-shared key info.
struct coap_keystore_t
The structure of a CoAP keystore.
Functions
void coap_keystore_simple_init (void)
Registers a simple CoAP DTLS keystore with fixed pre-shared key credentials.
void coap_set_keystore (const coap_keystore_t *keystore)
Set the CoAP keystore to use by CoAP.
Detailed Description
The CoAP keystore API defines a common interface for retrieving authorization information for CoAP/DTLS.
Function Documentation
void coap_keystore_simple_init (void)
Registers a simple CoAP DTLS keystore with fixed pre-shared key credentials.
The credentials can be configured in project-conf.h as shown in the following example:
#define COAP_DTLS_PSK_DEFAULT_IDENTITY "user"
#define COAP_DTLS_PSK_DEFAULT_KEY      "password"
Definition at line 84 of file coap-keystore-simple.c.
References coap_set_keystore().
Referenced by coap_transport_init().
void coap_set_keystore (const coap_keystore_t * keystore)
Set the CoAP keystore to use by CoAP.
Parameters
keystore A pointer to a CoAP keystore.
Referenced by coap_keystore_simple_init(), and coap_sendto().