Contiki-NG: cc2538 SoC
cc2538 SoC
The TI cc2538 System-on-Chip
Driver for the cc2538 SoC.
Files
file soc.c
Implementation of the cc2538 SoC driver.
file soc.h
Header file with macro and function declarations for the cc2538 SoC.
SoC features
#define SOC_FEATURE_AES_SHA 0x00000002
Security HW AES/SHA.
#define SOC_FEATURE_ECC_RSA 0x00000001
Security HW ECC/RSA.
SoC functions
uint8_t soc_get_rev (void)
Gets the SoC revision.
uint32_t soc_get_sram_size (void)
Gets the SRAM size of the SoC.
uint32_t soc_get_features (void)
Gets the hardware features of the SoC that are enabled.
void soc_print_info (void)
Prints SoC information.
void soc_init (void)
Common initialisation routine for all CC2538-based platforms.
Detailed Description
Driver for the cc2538 SoC.
Function Documentation
uint32_t soc_get_features (void)
Gets the hardware features of the SoC that are enabled.
Returns
The enabled hardware features as a bitmask of SOC_FEATURE_x values
Definition at line 90 of file soc.c.
Referenced by soc_print_info().
uint8_t soc_get_rev (void)
Gets the SoC revision.
Returns
The SoC revision as a byte with nibbles representing the major and minor revisions
Definition at line 70 of file soc.c.
Referenced by soc_print_info().
uint32_t soc_get_sram_size (void)
Gets the SRAM size of the SoC.
Returns
The SRAM size in bytes
Definition at line 81 of file soc.c.
Referenced by soc_print_info().