Contiki-NG: SmartRF+CC13xx/CC26xx EM, SensorTags and LaunchPads
SmartRF+CC13xx/CC26xx EM, SensorTags and LaunchPads
TI CC26xx-powered platforms
This platform supports a number of different boards:
Modules
CC1350 Sensortag Peripherals
Defines related to the CC1350 Sensortag.
CC13xx/CC26xx peripheral driver pool
Drivers for peripherals present on more than one CC13xx/CC26xx board.
CC2650 Sensortag Peripherals
Defines related to the CC2650 Sensortag.
LaunchPad peripherals
Defines related to LaunchPad peripherals.
Peripherals for the SmartRF06EB + CC1310EM
Defines related to the SmartRF06 Evaluation Board with a CC1310EM.
Peripherals for the SmartRF06EB + CC26xxEM
Defines related to the SmartRF06 Evaluation Board with a CC26xxEM.
Sensortag CC1350/CC2650 common
Defines related to Sensortag sensors.
SmartRF06EB + CC13xx/CC26xx common
Defines related to the SmartRF06 Evaluation Board irrespective of the EM mounted on it.
Files
file contiki-conf.h
Configuration for the srf06-cc26xx platform.
Functions
void board_init (void)
Board specific iniatialisation.
void platform_init_stage_one ()
Basic (Stage 1) platform driver initialisation.
void platform_init_stage_two ()
Stage 2 of platform driver initialisation.
void platform_init_stage_three ()
Final stage of platform driver initialisation.
void platform_idle ()
The platform's idle/sleep function.
Network Stack Configuration
#define CC2650_FAST_RADIO_STARTUP (MAC_CONF_WITH_TSCH)
#define RF_CORE_CONF_CHANNEL 25
#define PROP_MODE_CONF_RX_BUF_CNT 4
#define NETSTACK_CONF_RADIO ieee_mode_driver
#define CSMA_CONF_SEND_SOFT_ACK 0
#define NETSTACK_RADIO_MAX_PAYLOAD_LEN 125
IEEE address configuration
Used to generate our link-local & IPv6 address
#define IEEE_ADDR_CONF_HARDCODED 0
Location of the IEEE address 0 => Read from InfoPage, 1 => Use a hardcoded address, configured by IEEE_ADDR_CONF_ADDRESS.
#define IEEE_ADDR_CONF_ADDRESS { 0x00, 0x12, 0x4B, 0x00, 0x89, 0xAB, 0xCD, 0xEF }
The hardcoded IEEE address to be used when IEEE_ADDR_CONF_HARDCODED is defined as 1.
RF configuration
#define IEEE_MODE_CONF_AUTOACK 1
RF H/W generates ACKs.
#define IEEE_MODE_CONF_PROMISCOUS 0
1 to enable promiscous mode
#define RF_BLE_CONF_ENABLED 0
0 to disable BLE support
Character I/O Configuration
#define CC26XX_UART_CONF_ENABLE 1
Enable/Disable UART I/O.
#define CC26XX_UART_CONF_BAUD_RATE 115200
Default UART0 baud rate.
#define BOARD_CONF_DEBUGGER_DEVPACK 1
#define SLIP_BRIDGE_CONF_NO_PUTCHAR 1
#define SLIP_RADIO_CONF_NO_PUTCHAR 1
ROM Bootloader configuration
Enable/Disable the ROM bootloader in your image, if the board supports it.
Look in board.h to choose the DIO and corresponding level that will cause the chip to enter bootloader mode.
#define ROM_BOOTLOADER_ENABLE 0
Button configurations
Configure a button as power on/off: We use the right button for both boards.
#define BUTTON_SENSOR_CONF_ENABLE_SHUTDOWN 1
#define PLATFORM_HAS_BUTTON 1
#define button_sensor button_left_sensor
#define button_sensor2 button_right_sensor
Compiler configuration and platform-specific type definitions
Those values are not meant to be modified by the user
typedef uint32_t clock_time_t
typedef uint32_t uip_stats_t
typedef uint32_t rtimer_clock_t
#define CLOCK_CONF_SECOND 128
#define CCIF
#define CLIF
#define CLOCK_LT(a, b) ((signed long)((a) - (b)) < 0)
#define RTIMER_CLOCK_DIFF(a, b) ((int32_t)((a) - (b)))
#define RADIO_DELAY_BEFORE_TX ((unsigned)US_TO_RTIMERTICKS(81))
#define RADIO_DELAY_BEFORE_RX ((unsigned)US_TO_RTIMERTICKS(15))
#define RADIO_DELAY_BEFORE_DETECT ((unsigned)US_TO_RTIMERTICKS(352))
#define RADIO_TIMER_SECOND 4000000u
#define RADIO_TO_RTIMER(X) ((uint32_t)(((uint64_t)(X) * (RTIMER_SECOND / 256)) / (RADIO_TIMER_SECOND / 256)))
#define USEC_TO_RADIO(X) ((X) * 4)
#define RADIO_IEEE_802154_PHY_HEADER_DURATION_USEC 160
#define TSCH_CONF_RADIO_ON_DURING_TIMESLOT 1
#define TSCH_CONF_HW_FRAME_FILTERING 0
#define TSCH_CONF_RESYNC_WITH_SFD_TIMESTAMPS 1
#define TSCH_CONF_TIMESYNC_REMOVE_JITTER 0
#define TSCH_CONF_BASE_DRIFT_PPM -977
#define TSCH_CONF_CHANNEL_SCAN_DURATION (CLOCK_SECOND / 10)
#define TSCH_CONF_RX_WAIT 1800
Detailed Description
This platform supports a number of different boards:
A standard TI SmartRF06EB with a CC26xx EM mounted on it
A standard TI SmartRF06EB with a CC1310 EM mounted on it
The TI CC2650 SensorTag
The TI CC1350 SensorTag
The TI CC2650 LaunchPad
The TI CC1310 LaunchPad
The TI CC1350 LaunchPad
Function Documentation
void platform_idle (void)
The platform's idle/sleep function.
This function will be called as part of the main loop after all events have been serviced. This is where you will normally put the device in a low-power state. Waking up from this state and tidying up the hardware is the port's responsibility.
It is the port developer's responsibility to implement this function.
Definition at line 203 of file platform.c.
References lpm_drop().
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
This function will get called early on in the Contiki-NG boot sequence.
In this function, the platform should initialise all core device drivers. For example, this is where you will normally want to initialise hardware timers/clocks, GPIO, LEDS. Normally this function will also enable the MCU's global interrupt.
The Contiki-NG process scheduler, software clocks and timers will not be running yet, so any platform drivers that rely on it should not be initialised here. Instead, they should be initialised in platform_init_stage_two() or in platform_init_stage_three()
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_two()
platform_init_stage_three()
Definition at line 125 of file platform.c.
References board_init(), gpio_interrupt_init(), LEDS_RED, LEDS_YELLOW, lpm_init(), oscillators_select_lf_xosc(), and soc_rtc_init().
void platform_init_stage_three (void)
Final stage of platform driver initialisation.
Initialisation of platform-specific drivers that require networking to be running. This is also a good place to initialise sensor drivers.
When this function returns, the main routine will assume that the hardware is fully initialised.
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_one()
platform_init_stage_two()
Definition at line 178 of file platform.c.
References LEDS_ORANGE, and process_start().
void platform_init_stage_two (void)
Stage 2 of platform driver initialisation.
This function will be called by the Contiki-NG boot sequence after parts of the core have been initialised. More specifically, when this function gets called, the following modules will be running:
Software clock
Process scheduler
Event timer (etimer)
Callback timer (ctimer)
rtimer
Energest (if enabled)
Therefore, any platform driver that relies on any of the above modules should be initialised here or in platform_init_stage_three(), but not in platform_init_stage_one()
The Contiki-NG network stack will not be running yet, so any platform drivers that rely on networking should not be initialised here.
When this function returns, the main routine will assume that the platform has enabled character I/O and can print to console. When this function returns, main() will attempt to initialise the network stack. For this to work properly, this function should also populate linkaddr_node_addr.
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_one()
platform_init_stage_three()
Definition at line 160 of file platform.c.
References cc26xx_uart_init(), ieee_addr_cpy_to(), LEDS_GREEN, linkaddr_node_addr, and random_init().