Contiki-NG: CC13xx/CC26xx oscillator control
CC13xx/CC26xx oscillator control
The TI CC26xx and CC13xx CPUs
Wrapper around CC26xxware/CC13xxware OSC functions that we need in Contiki.
Files
file oscillators.c
Implementation of CC26xxware oscillator control wrappers.
file oscillators.h
Header file for the CC13xx/CC26xx oscillator control.
Functions
void oscillators_select_lf_xosc (void)
Set the LF clock source to be the LF XOSC.
void oscillators_select_lf_rcosc (void)
Set the LF clock source to be the LF RCOSC.
void oscillators_request_hf_xosc (void)
Requests the HF XOSC as the source for the HF clock, but does not perform the actual switch.
void oscillators_switch_to_hf_xosc (void)
Performs the switch to the XOSC.
void oscillators_switch_to_hf_rc (void)
Switches MF and HF clock source to be the HF RC OSC.
Detailed Description
Wrapper around CC26xxware/CC13xxware OSC functions that we need in Contiki.
All CC26xxware OSC control requires access to the semaphore module within AUX. Thus, in addition to enabling the oscillator interface, we need to start the clock to SMPH and restore it to its previous state when we are done.
Function Documentation
void oscillators_request_hf_xosc (void)
Requests the HF XOSC as the source for the HF clock, but does not perform the actual switch.
This triggers the startup sequence of the HF XOSC and returns so the CPU can perform other tasks while the XOSC is starting.
The XOSC is requested as the source for the HF as well as the MF clock.
Definition at line 94 of file oscillators.c.
References aux_ctrl_register_consumer(), and aux_ctrl_unregister_consumer().
void oscillators_select_lf_rcosc (void)
Set the LF clock source to be the LF RCOSC.
This function is only called once, when the systen transitions to a full shutdown
Do not switch the LF clock source to the RC OSC for normal system operation See CC26xx Errata (swrz058)
Definition at line 73 of file oscillators.c.
References aux_ctrl_register_consumer(), and aux_ctrl_unregister_consumer().
Referenced by lpm_shutdown().
void oscillators_select_lf_xosc (void)
Set the LF clock source to be the LF XOSC.
This function is only called once as soon as the system starts.
Do not switch the LF clock source to the RC OSC for normal system operation See CC26xx Errata (swrz058)
Definition at line 45 of file oscillators.c.
References aux_ctrl_register_consumer(), and aux_ctrl_unregister_consumer().
Referenced by platform_init_stage_one().
void oscillators_switch_to_hf_xosc (void)
Performs the switch to the XOSC.
This function must be preceded by a call to oscillators_request_hf_xosc()
Definition at line 116 of file oscillators.c.
References aux_ctrl_register_consumer(), and aux_ctrl_unregister_consumer().