Contiki-NG: Nullnet
Nullnet
IoT networking » Network layer
A network layer that does nothing.
Typedefs
typedef void(* nullnet_input_callback) (const void *data, uint16_t len, const linkaddr_t *src, const linkaddr_t *dest)
Function prototype for NullNet input callback.
Functions
void nullnet_set_input_callback (nullnet_input_callback callback)
Set input callback for NullNet.
Variables
uint8_t * nullnet_buf
Buffer used by the output function.
uint8_t * nullnet_buf
Buffer used by the output function.
Detailed Description
A network layer that does nothing.
Useful for lower-layer testing and for non-IPv6 scenarios.
Function Documentation
void nullnet_set_input_callback (nullnet_input_callback callback)
Set input callback for NullNet.
Parameters
callback The input callback
Definition at line 80 of file nullnet.c.
References network_driver::init, input(), linkaddr_node_addr, linkaddr_null, nullnet_buf, output(), packetbuf_clear(), packetbuf_copyfrom(), packetbuf_datalen(), and mac_driver::send.