Contiki-NG: nRF52 Development Kit
nRF52 Development Kit
Platforms
Modules
Contiki configuration
Debug IO over UART
Device drivers
Platform configuration
nRF52 SDK configuration
Functions
static void board_init (void)
Board specific initialization.
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
void platform_init_stage_two (void)
Stage 2 of platform driver initialisation.
void platform_init_stage_three (void)
Final stage of platform driver initialisation.
void platform_idle ()
The platform's idle/sleep function.
Detailed Description
Function Documentation
static void board_init (void) static
Board specific initialization.
This function will enable SoftDevice is present.
Definition at line 101 of file platform.c.
Referenced by platform_init_stage_one().
void platform_idle (void)
The platform's idle/sleep function.
This function will be called as part of the main loop after all events have been serviced. This is where you will normally put the device in a low-power state. Waking up from this state and tidying up the hardware is the port's responsibility.
It is the port developer's responsibility to implement this function.
Definition at line 163 of file platform.c.
References lpm_drop().
void platform_init_stage_one (void)
Basic (Stage 1) platform driver initialisation.
This function will get called early on in the Contiki-NG boot sequence.
In this function, the platform should initialise all core device drivers. For example, this is where you will normally want to initialise hardware timers/clocks, GPIO, LEDS. Normally this function will also enable the MCU's global interrupt.
The Contiki-NG process scheduler, software clocks and timers will not be running yet, so any platform drivers that rely on it should not be initialised here. Instead, they should be initialised in platform_init_stage_two() or in platform_init_stage_three()
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_two()
platform_init_stage_three()
Definition at line 115 of file platform.c.
References board_init().
void platform_init_stage_three (void)
Final stage of platform driver initialisation.
Initialisation of platform-specific drivers that require networking to be running. This is also a good place to initialise sensor drivers.
When this function returns, the main routine will assume that the hardware is fully initialised.
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_one()
platform_init_stage_two()
Definition at line 144 of file platform.c.
References ble_advertising_start(), ble_get_mac(), DEVICE_NAME, linkaddr_set_node_addr(), and process_start().
void platform_init_stage_two (void)
Stage 2 of platform driver initialisation.
This function will be called by the Contiki-NG boot sequence after parts of the core have been initialised. More specifically, when this function gets called, the following modules will be running:
Software clock
Process scheduler
Event timer (etimer)
Callback timer (ctimer)
rtimer
Energest (if enabled)
Therefore, any platform driver that relies on any of the above modules should be initialised here or in platform_init_stage_three(), but not in platform_init_stage_one()
The Contiki-NG network stack will not be running yet, so any platform drivers that rely on networking should not be initialised here.
When this function returns, the main routine will assume that the platform has enabled character I/O and can print to console. When this function returns, main() will attempt to initialise the network stack. For this to work properly, this function should also populate linkaddr_node_addr.
It is the port developer's responsibility to implement this function.
See Also
platform_init_stage_one()
platform_init_stage_three()
Definition at line 122 of file platform.c.
References ble_advertising_init(), ble_stack_init(), DEVICE_NAME, random_init(), serial_line_input_byte(), slip_arch_init(), and uart0_init().