Contiki-NG: EEPROM API
EEPROM API
CPUs and Device driver
The EEPROM API defines a common interface for EEPROM access on Contiki platforms.
Functions
void eeprom_write (eeprom_addr_t addr, unsigned char *buf, int size)
Write a buffer into EEPROM.
void eeprom_read (eeprom_addr_t addr, unsigned char *buf, int size)
Read data from the EEPROM.
void eeprom_init (void)
Initialize the EEPROM module.
Detailed Description
The EEPROM API defines a common interface for EEPROM access on Contiki platforms.
A platform with EEPROM support must implement this API.
Function Documentation
void eeprom_init (void)
Initialize the EEPROM module.
This function initializes the EEPROM module and is called from the bootup code.
Definition at line 72 of file eeprom.c.
Referenced by eeprom_read(), and eeprom_write().
void eeprom_read (eeprom_addr_t addr, unsigned char * buf, int size)
Read data from the EEPROM.
This function reads a number of bytes from the specified address in EEPROM and into a buffer in memory.
Parameters
addr The address in EEPROM from which the data should be read.
buf A pointer to the buffer to which the data should be stored.
size The number of bytes to read.
Definition at line 146 of file eeprom.c.
References addr, and eeprom_init().
void eeprom_write (eeprom_addr_t addr, unsigned char * buf, int size)
Write a buffer into EEPROM.
This function writes a buffer of the specified size into EEPROM.
Parameters
addr The address in EEPROM to which the buffer should be written.
buf A pointer to the buffer from which data is to be read.
size The number of bytes to write into EEPROM.
Definition at line 121 of file eeprom.c.
References addr, and eeprom_init().