Contiki-NG: Contiki processes
Contiki processes
System functions » Threads and processes
A process in Contiki consists of a single protothread.
Files
file process.c
    Implementation of the Contiki process kernel.
file process.h
Header file for the Contiki process interface.
Return values
#define PROCESS_ERR_OK 0
Return value indicating that an operation was successful.
#define PROCESS_ERR_FULL 1
Return value indicating that the event queue was full.
Process protothread functions
#define PROCESS_BEGIN()
Define the beginning of a process.
#define PROCESS_END()
Define the end of a process.
#define PROCESS_WAIT_EVENT()
Wait for an event to be posted to the process.
#define PROCESS_WAIT_EVENT_UNTIL(c)
Wait for an event to be posted to the process, with an extra condition.
#define PROCESS_YIELD()
Yield the currently running process.
#define PROCESS_YIELD_UNTIL(c)
Yield the currently running process until a condition occurs.
#define PROCESS_WAIT_UNTIL(c)
Wait for a condition to occur.
#define PROCESS_WAIT_WHILE(c) PT_WAIT_WHILE(process_pt, c)
#define PROCESS_EXIT()
Exit the currently running process.
#define PROCESS_PT_SPAWN(pt, thread)
Spawn a protothread from the process.
#define PROCESS_PAUSE()
Yield the process for a short while.
Poll and exit handlers
#define PROCESS_POLLHANDLER(handler)
Specify an action when a process is polled.
#define PROCESS_EXITHANDLER(handler)
Specify an action when a process exits.
Process declaration and definition
#define PROCESS_THREAD(name, ev, data)
Define the body of a process.
#define PROCESS_NAME(name)
Declare the name of a process.
#define PROCESS(name, strname)
Declare a process.
Functions called from application programs
struct process * process_current
process_event_t process_alloc_event (void)
Allocate a global event number.
void process_start (struct process *p, process_data_t data)
Start a process.
void process_exit (struct process *p)
Cause a process to exit.
int process_post (struct process *p, process_event_t ev, process_data_t data)
Post an asynchronous event.
void process_post_synch (struct process *p, process_event_t ev, process_data_t data)
Post a synchronous event to a process.
#define PROCESS_CURRENT()
Get a pointer to the currently running process.
#define PROCESS_CONTEXT_BEGIN(p)
Switch context to another process.
#define PROCESS_CONTEXT_END(p) process_current = tmp_current; }
End a context switch.
Functions called from device drivers
void process_poll (struct process *p)
Request a process to be polled.
Functions called by the system and boot-up code
void process_init (void)
Initialize the process module.
int process_run (void)
Run the system once - call poll handlers and process one event.
int process_nevents (void)
Number of events waiting to be processed.
int process_is_running (struct process *p)
Check if a process is running.
Detailed Description
A process in Contiki consists of a single protothread.
Macro Definition Documentation
#define PROCESS (name, strname)
Declare a process.
This macro declares a process. The process has two names: the variable of the process structure, which is used by the C program, and a human readable string name, which is used when debugging. A configuration option allows removal of the readable name to save RAM.
Parameters
name The variable name of the process structure.
strname The string representation of the process' name.
Definition at line 307 of file process.h.
Referenced by rtcc_date_increment_seconds(), tcpip_output(), and usb_serial_writeb().
#define PROCESS_BEGIN ()
Define the beginning of a process.
This macro defines the beginning of a process, and must always appear in a PROCESS_THREAD() definition. The PROCESS_END() macro must come at the end of the process.
Definition at line 120 of file process.h.
Referenced by ble_mac_ipsp_evt_handler_irq(), button_hal_init(), cc2420_interrupt(), coap_sendto(), PROCESS_THREAD(), resolv_get_hostname(), rf_ble_beacon_single(), rf_core_primary_mode_restore(), rtcc_date_increment_seconds(), serial_line_input_byte(), simple_udp_register(), slip_send(), soc_trng_rand_asynchronous(), stack_check_get_reserved_size(), tcpip_poll_tcp(), tsch_disassociate(), and usb_serial_writeb().
#define PROCESS_CONTEXT_BEGIN (p)
Value:
{\
struct process *tmp_current = PROCESS_CURRENT();\
process_current = p
Switch context to another process.
This function switch context to the specified process and executes the code as if run by that process. Typical use of this function is to switch context in services, called by other processes. Each PROCESS_CONTEXT_BEGIN() must be followed by the PROCESS_CONTEXT_END() macro to end the context switch.
Example:
 PROCESS_CONTEXT_BEGIN(&test_process);
 etimer_set(&timer, CLOCK_SECOND);
 PROCESS_CONTEXT_END(&test_process);
Parameters
p The process to use as context
See also
PROCESS_CONTEXT_END()
PROCESS_CURRENT()
Definition at line 426 of file process.h.
Referenced by ctimer_reset(), ctimer_restart(), ctimer_set_with_process(), and simple_udp_register().
#define PROCESS_CONTEXT_END (p) process_current = tmp_current; }
End a context switch.
This function ends a context switch and changes back to the previous process.
Parameters
p The process used in the context switch
See also
PROCESS_CONTEXT_START()
Definition at line 440 of file process.h.
Referenced by ctimer_reset(), ctimer_restart(), ctimer_set_with_process(), and simple_udp_register().
#define PROCESS_CURRENT ()
Get a pointer to the currently running process.
This macro get a pointer to the currently running process. Typically, this macro is used to post an event to the current process with process_post().
Definition at line 402 of file process.h.
Referenced by ctimer_set(), etimer_request_poll(), process_exit(), process_post(), serial_line_input_byte(), tcp_listen(), tcp_unlisten(), and tcpip_poll_tcp().
#define PROCESS_END ()
Define the end of a process.
This macro defines the end of a process. It must appear in a PROCESS_THREAD() definition and must always be included. The process exits when the PROCESS_END() macro is reached.
Definition at line 131 of file process.h.
Referenced by ble_mac_ipsp_evt_handler_irq(), button_hal_init(), cc2420_interrupt(), coap_sendto(), PROCESS_THREAD(), resolv_get_hostname(), rf_ble_beacon_single(), rf_core_primary_mode_restore(), rtcc_date_increment_seconds(), serial_line_input_byte(), simple_udp_register(), slip_send(), soc_trng_rand_asynchronous(), stack_check_get_reserved_size(), tcpip_poll_tcp(), tsch_disassociate(), and usb_serial_writeb().
#define PROCESS_ERR_FULL 1
Return value indicating that the event queue was full.
This value is returned from process_post() to indicate that the event queue was full and that an event could not be posted.
Definition at line 82 of file process.h.
Referenced by process_post().
#define PROCESS_ERR_OK 0
Return value indicating that an operation was successful.
This value is returned to indicate that an operation was successful.
Definition at line 74 of file process.h.
Referenced by process_post(), and serial_line_input_byte().
#define PROCESS_EXITHANDLER (handler)
Specify an action when a process exits.
Note
This declaration must come immediately before the PROCESS_BEGIN() macro.
Parameters
handler The action to be performed.
Definition at line 254 of file process.h.
Referenced by rtcc_date_increment_seconds().
#define PROCESS_NAME (name)
Declare the name of a process.
This macro is typically used in header files to declare the name of a process that is implemented in the C file.
Definition at line 286 of file process.h.
#define PROCESS_PAUSE ()
Yield the process for a short while.
This macro yields the currently running process for a short while, thus letting other processes run before the process continues.
Definition at line 221 of file process.h.
#define PROCESS_POLLHANDLER (handler)
Specify an action when a process is polled.
Note
This declaration must come immediately before the PROCESS_BEGIN() macro.
Parameters
handler The action to be performed.
Definition at line 242 of file process.h.
#define PROCESS_PT_SPAWN (pt, thread)
Spawn a protothread from the process.
Parameters
pt The protothread state (struct pt) for the new protothread
thread The call to the protothread function.
See also
PT_SPAWN()
Definition at line 211 of file process.h.
Referenced by tsch_disassociate().
#define PROCESS_THREAD (name, ev, data)
Define the body of a process.
This macro is used to define the body (protothread) of a process. The process is called whenever an event occurs in the system, A process always start with the PROCESS_BEGIN() macro and end with the PROCESS_END() macro.
Definition at line 273 of file process.h.
#define PROCESS_WAIT_EVENT ()
Wait for an event to be posted to the process.
This macro blocks the currently running process until the process receives an event.
Definition at line 141 of file process.h.
Referenced by ble_mac_ipsp_evt_handler_irq(), resolv_get_hostname(), simple_udp_register(), and usb_serial_writeb().
#define PROCESS_WAIT_EVENT_UNTIL (c)
Wait for an event to be posted to the process, with an extra condition.
This macro is similar to PROCESS_WAIT_EVENT() in that it blocks the currently running process until the process receives an event. But PROCESS_WAIT_EVENT_UNTIL() takes an extra condition which must be true for the process to continue.
Parameters
c The condition that must be true for the process to continue.
See also
PT_WAIT_UNTIL()
Definition at line 157 of file process.h.
Referenced by resolv_get_hostname(), rf_ble_beacon_single(), serial_line_input_byte(), and stack_check_get_reserved_size().
#define PROCESS_WAIT_UNTIL (c)
Wait for a condition to occur.
This macro does not guarantee that the process yields, and should therefore be used with care. In most cases, PROCESS_WAIT_EVENT(), PROCESS_WAIT_EVENT_UNTIL(), PROCESS_YIELD() or PROCESS_YIELD_UNTIL() should be used instead.
Parameters
c The condition to wait for.
Definition at line 192 of file process.h.
Referenced by tsch_disassociate().
#define PROCESS_YIELD_UNTIL (c)
Yield the currently running process until a condition occurs.
This macro is different from PROCESS_WAIT_UNTIL() in that PROCESS_YIELD_UNTIL() is guaranteed to always yield at least once. This ensures that the process does not end up in an infinite loop and monopolizing the CPU.
Parameters
c The condition to wait for.
Definition at line 178 of file process.h.
Referenced by button_hal_init(), cc2420_interrupt(), PROCESS_THREAD(), rf_core_primary_mode_restore(), rtcc_date_increment_seconds(), slip_send(), soc_trng_rand_asynchronous(), and tsch_disassociate().
Function Documentation
process_event_t process_alloc_event (void)
Allocate a global event number.
Returns
The allocated event number
        In Contiki, event numbers above 128 are global and may
        be posted from one process to another. This function
        allocates one such event number.
Note
There currently is no way to deallocate an allocated event number.
Definition at line 93 of file process.c.
Referenced by button_hal_init(), resolv_get_hostname(), send_to_peer(), serial_line_input_byte(), soc_trng_init(), and tcpip_poll_tcp().
void process_exit (struct process * p)
Cause a process to exit.
Parameters
p The process that is to be exited
        This function causes a process to exit. The process can
        either be the currently executing process, or another
        process that is currently running.
See also
PROCESS_CURRENT()
Definition at line 202 of file process.c.
References PROCESS_CURRENT.
Referenced by rf_ble_beacond_stop().
void process_init (void)
Initialize the process module.
This function initializes the process module and should be called by the system boot-up code.
Definition at line 208 of file process.c.
int process_is_running (struct process * p)
Check if a process is running.
This function checks if a specific process is running.
Parameters
p The process.
Return values
Non-zero if the process is running.
Zero if the process is not running.
Definition at line 383 of file process.c.
Referenced by process_start().
int process_nevents (void)
Number of events waiting to be processed.
Returns
The number of events that are currently waiting to be processed.
Definition at line 316 of file process.c.
Referenced by lpm_shutdown(), platform_idle(), and platform_main_loop().
void process_poll (struct process * p)
Request a process to be polled.
This function typically is called from an interrupt handler to cause a process to be polled.
Parameters
p A pointer to the process' process structure.
Definition at line 371 of file process.c.
Referenced by ble_mac_ipsp_evt_handler_irq(), cc2420_interrupt(), cc2538_rf_err_isr(), cc2538_rf_rx_tx_isr(), crypto_isr(), etimer_request_poll(), init(), pka_isr(), rf_cmd_ieee_rx(), rf_core_primary_mode_restore(), rtcc_print(), serial_line_input_byte(), slip_input_byte(), slip_send(), and tsch_radio_off().
int process_post (struct process * p, process_event_t ev, process_data_t data)
Post an asynchronous event.
This function posts an asynchronous event to one or more processes. The handing of the event is deferred until the target process is scheduled by the kernel. An event can be broadcast to all processes, in which case all processes in the system will be scheduled to handle the event.
Parameters
ev The event to be posted.
data The auxiliary data to be sent with the event
p The process to which the event should be posted, or PROCESS_BROADCAST if the event should be posted to all processes.
Return values
PROCESS_ERR_OK The event could be posted.
PROCESS_ERR_FULL The event queue was full and the event could not be posted.
Definition at line 322 of file process.c.
References PROCESS_CURRENT, PROCESS_ERR_FULL, and PROCESS_ERR_OK.
Referenced by ble_mac_interface_add(), ble_mac_interface_delete(), mqtt_connect(), mqtt_disconnect(), mqtt_publish(), mqtt_subscribe(), mqtt_unsubscribe(), newdata(), resolv_lookup(), resolv_query(), serial_line_input_byte(), soc_trng_rand_asynchronous(), tcpip_poll_tcp(), tcpip_poll_udp(), and tsch_disassociate().
void process_post_synch (struct process * p, process_event_t ev, process_data_t data)
Post a synchronous event to a process.
Parameters
p A pointer to the process' process structure.
ev The event to be posted.
data A pointer to additional data that is posted together with the event.
Definition at line 362 of file process.c.
Referenced by process_start(), tcpip_icmp6_call(), tcpip_input(), tcpip_poll_tcp(), and tsch_set_eb_period().
int process_run (void)
Run the system once - call poll handlers and process one event.
This function should be called repeatedly from the main() program to actually run the Contiki system. It calls the necessary poll handlers, and processes one event. The function returns the number of events that are waiting in the event queue so that the caller may choose to put the CPU to sleep when there are no pending events.
Returns
The number of events that are currently waiting in the event queue.
Definition at line 302 of file process.c.
Referenced by platform_main_loop().
void process_start (struct process * p, process_data_t data)
Start a process.
Parameters
p A pointer to a process structure.
data An argument pointer that can be passed to the new process
Definition at line 99 of file process.c.
References process_is_running(), process_post_synch(), and PT_INIT.
Referenced by button_hal_init(), coap_transport_init(), ctimer_init(), init(), platform_init_stage_three(), resolv_get_hostname(), rf_ble_beacond_start(), rf_cmd_ieee_rx(), rtcc_init(), send_to_peer(), serial_line_input_byte(), serial_shell_init(), soc_trng_init(), stack_check_init(), tsch_disassociate(), and usb_serial_init().