Contiki-NG: LED Hardware Abstraction Layer
LED Hardware Abstraction Layer
Hardware support » Device Drivers
The LED HAL provides a set of functions that can manipulate LEDS.
Files
file leds.c
Implementation of the platform-independent aspects of the LED HAL.
Functions
void leds_init ()
Initialise the LED HAL.
void leds_single_on (leds_num_t led)
Turn a single LED on.
void leds_single_off (leds_num_t led)
Turn a single LED off.
void leds_single_toggle (leds_num_t led)
Toggle a single LED.
void leds_on (leds_mask_t leds)
Turn on multiple LEDs.
void leds_off (leds_mask_t leds)
Turn off multiple LEDs.
void leds_toggle (leds_mask_t leds)
Toggle multiple LEDs.
void leds_set (leds_mask_t leds)
Set all LEDs to a specific state.
leds_mask_t leds_get ()
Get the status of LEDs.
Detailed Description
The LED HAL provides a set of functions that can manipulate LEDS.
Currently, the LED HAL supports two APIs:
The new, platform-independent API (recommended for all new platforms).
The legacy API (supported until all existing platforms have been ported to support the new API).
The two APIs use very similar semantics and have an overlapping set of function calls. This is done so that platform-independent examples can work on all platforms, irrespective of which API each platform supports.
The legacy API can be enabled by the platform code by defining LEDS_CONF_LEGACY_API 1.
Once all platforms supported in contiki-ng/contiki-ng have been ported to the new API, the legacy API will be deleted without warning. For this reason, it is strongly recommended to use the new API for new platforms and for platforms hosted in external repositories.
The new API provides a set of common LED manipulation functions that can be used in a platform-independent fashion. Functions exist to manipulate one LED at a time (leds_single_XYZ), as well as to manipulate multiple LEDs at a time (leds_XYZ).
The assumption is that each LED is connected to a GPIO pin using either positive or negative logic.
LEDs on a device are numbered incrementally, starting from 0 and counting upwards. Thus, if a device has 3 LEDs they will be numbered 0, 1 and 2. Convenience macros (LEDS_LED_n) are provided to refer to LEDs. These macros can be used as arguments to functions that manipulate a single LED, such as leds_single_on() but not leds_on().
The legacy scheme that uses colours to refer to LEDs is maintained, without semantic changes, but with minor changes in logic:
Firstly, we now define 5 LED colours: Red, Green, Blue, Yellow, Orange. These are sufficient to cover all currently-supported platforms.
Secondly, unless a platform specifies that a LED of a specific colour exists, the HAL will assume that it does not.
Trying to manipulate a non-existent LED will not cause build errors, but will not cause any changes to LED state either.
We no longer map non-existing LED colours to existing ones.
Note that, in order to avoid changes to LED colour semantics between the two APIs, references to LED by colour are bitwise OR masks and should therefore only be used as argument to functions that manipulate multiple LEDS (e.g. leds_off() and not leds_single_off()).
In terms of porting for new platforms, developers simply have to:
Define variables of type leds_t to represent their platform's LEDs
Specify the number of LEDs on their device by defining LEDS_CONF_COUNT
Map red colours to numbers (e.g. #define LEDS_CONF_RED 1)
Function Documentation
leds_mask_t leds_get (void)
Get the status of LEDs.
Returns
A bitwise mask indicating whether each individual LED is on or off
The return value is a bitwise mask. If a bit is set then the corresponding LED is on.
Definition at line 207 of file leds.c.
References LEDS_COUNT.
void leds_init (void)
Initialise the LED HAL.
This function will set corresponding LED GPIO pins to output and will also set the initial state of all LEDs to off.
Definition at line 107 of file leds.c.
References LEDS_ALL, LEDS_COUNT, and leds_off().
void leds_off (leds_mask_t leds)
Turn off multiple LEDs.
Parameters
leds The leds to be turned off as an OR mask
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will not change the state of other LEDs.
Definition at line 172 of file leds.c.
References LEDS_ALL, and LEDS_COUNT.
Referenced by leds_init(), and leds_set().
void leds_on (leds_mask_t leds)
Turn on multiple LEDs.
Parameters
leds The leds to be turned on as an OR mask
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will not change the state of other LEDs.
Definition at line 156 of file leds.c.
References LEDS_ALL, and LEDS_COUNT.
Referenced by leds_set().
void leds_set (leds_mask_t leds)
Set all LEDs to a specific state.
Parameters
leds The state of all LEDs afer this function returns
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will change the state of all LEDs. LEDs not set in the leds mask will be turned off.
Definition at line 200 of file leds.c.
References LEDS_ALL, leds_off(), and leds_on().
void leds_single_off (leds_num_t led)
Turn a single LED off.
Parameters
led The led
The led argument should be the LED's number, in other words one of the LED_Ln macros.
This function will not change the state of other LEDs.
Definition at line 132 of file leds.c.
References LEDS_COUNT.
void leds_single_on (leds_num_t led)
Turn a single LED on.
Parameters
led The led
The led argument should be the LED's number, in other words one of the LED_Ln macros.
This function will not change the state of other LEDs.
Definition at line 118 of file leds.c.
References LEDS_COUNT.
void leds_single_toggle (leds_num_t led)
Toggle a single LED.
Parameters
led The led
The led argument should be the LED's number, in other words one of the LED_Ln macros.
This function will not change the state of other LEDs.
Definition at line 146 of file leds.c.
References gpio_hal_arch_toggle_pin(), and LEDS_COUNT.
void leds_toggle (leds_mask_t leds)
Toggle multiple LEDs.
Parameters
leds The leds to be toggled as an OR mask
The led argument should be a bitwise mask of the LEDs to be changed. For example, to turn on LEDs 1 and 3, you should pass LED_NUM_TO_MASK(LED_L1) | LED_NUM_TO_MASK(LED_L3) = 1 | 4 = 5
This function will not change the state of other LEDs.
Definition at line 188 of file leds.c.
References gpio_hal_arch_toggle_pin(), LEDS_ALL, and LEDS_COUNT.