Contiki-NG: Zoul User Button Driver
Zoul User Button Driver
Zoul Sensors
Driver for the Zoul user button.
Files
file button-sensor.c
Driver for the Zoul user button.
file button-sensor.h
Header file for the Zoul User Button Driver.
Functions
static int value (int type)
Retrieves the value of the button pin.
static void btn_callback (uint8_t port, uint8_t pin)
Callback registered with the GPIO module.
static int config_user (int type, int value)
Init function for the User button.
Variables
const struct sensors_sensor button_sensor
Exports a global symbol to be used by the sensor API.
Detailed Description
Driver for the Zoul user button.
The user button (on Zoul-based platforms like the RE-Mote and the Firefly) will generate a sensors_changed event on press as well as on release.
Unlike many other platforms, the user button has the ability to generate events when the user keeps the button pressed. The user can configure the button driver with a timer interval in clock ticks. When the button is kept pressed, the driver will then generate a broadcast event each time the interval passes. For example the driver can be configured to generate an event every second while the button is kept pressed. This functionality can be enabled through the configure() function, by passing BUTTON_SENSOR_CONFIG_TYPE_INTERVAL as the type argument.
Function Documentation
static void btn_callback (uint8_t port, uint8_t pin) static
Callback registered with the GPIO module.
Gets fired with a button port/pin generates an interrupt
Parameters
port The port number that generated the interrupt
pin The pin number that generated the interrupt. This is the pin absolute number (i.e. 0, 1, ..., 7), not a mask
Definition at line 105 of file button-sensor.c.
References button_sensor, ctimer_set(), ctimer_stop(), DEBOUNCE_DURATION, timer_expired(), timer_set(), and value().
Referenced by config_user().
static int config_user (int type, int value) static
Init function for the User button.
Parameters
type SENSORS_ACTIVE: Activate / Deactivate the sensor (value == 1 or 0 respectively)
value Depends on the value of the type argument
Returns
Depends on the value of the type argument
Definition at line 135 of file button-sensor.c.
References btn_callback(), BUTTON_USER_PORT, GPIO_DETECT_EDGE, GPIO_DISABLE_INTERRUPT, GPIO_ENABLE_INTERRUPT, gpio_register_callback(), GPIO_SET_INPUT, GPIO_SOFTWARE_CONTROL, GPIO_TRIGGER_BOTH_EDGES, IOC_OVERRIDE_PUE, ioc_set_over(), NVIC_DisableIRQ(), NVIC_EnableIRQ(), process_alloc_event(), and value().
static int value (int type) static
Retrieves the value of the button pin.
Parameters
type Returns the pin level or the counter of press duration events. type == BUTTON_SENSOR_VALUE_TYPE_LEVEL or type == BUTTON_SENSOR_VALUE_TYPE_PRESS_DURATION respectively
Definition at line 85 of file button-sensor.c.
References GPIO_READ_PIN.
Referenced by btn_callback(), and config_user().