Contiki-NG: Event timers
Event timers
Timers
Event timers provides a way to generate timed events.
Files
file etimer.c
Event timer library implementation.
Data Structures
struct etimer
A timer.
Functions called from application programs
void etimer_set (struct etimer *et, clock_time_t interval)
Set an event timer.
void etimer_reset_with_new_interval (struct etimer *et, clock_time_t interval)
Reset an event timer with a new interval.
void etimer_reset (struct etimer *et)
Reset an event timer with the same interval as was previously set.
void etimer_restart (struct etimer *et)
Restart an event timer from the current point in time.
void etimer_adjust (struct etimer *et, int td)
Adjust the expiration time for an event timer.
int etimer_expired (struct etimer *et)
Check if an event timer has expired.
clock_time_t etimer_expiration_time (struct etimer *et)
Get the expiration time for the event timer.
clock_time_t etimer_start_time (struct etimer *et)
Get the start time for the event timer.
void etimer_stop (struct etimer *et)
Stop a pending event timer.
Functions called from timer interrupts, by the system
void etimer_request_poll (void)
Make the event timer aware that the clock has changed.
int etimer_pending (void)
Check if there are any non-expired event timers.
clock_time_t etimer_next_expiration_time (void)
Get next event timer expiration time.
Detailed Description
Event timers provides a way to generate timed events.
An event timer will post an event to the process that set the timer when the event timer expires.
An event timer is declared as a struct etimer and all access to the event timer is made by a pointer to the declared event timer.
See Also
Simple timer library
Clock library (used by the timer library)
Function Documentation
void etimer_adjust (struct etimer * et, int td)
Adjust the expiration time for an event timer.
Parameters
et A pointer to the event timer.
td The time difference to adjust the expiration time with.
        This function is used to adjust the time the event
        timer will expire. It can be used to synchronize
        periodic timers without the need to restart the timer
        or change the timer interval.
        \note This function should only be used for small
        adjustments. For large adjustments use etimer_set()
        instead.
        \note A periodic timer will drift unless the
        etimer_reset() function is used.
See Also
etimer_set()
etimer_reset()
Definition at line 206 of file etimer.c.
clock_time_t etimer_expiration_time (struct etimer * et)
Get the expiration time for the event timer.
Parameters
et A pointer to the event timer
Returns
The expiration time for the event timer.
        This function returns the expiration time for an event timer.
Definition at line 219 of file etimer.c.
CCIF int etimer_expired (struct etimer * et)
Check if an event timer has expired.
Parameters
et A pointer to the event timer
Returns
Non-zero if the timer has expired, zero otherwise.
        This function tests if an event timer has expired and
        returns true or false depending on its status.
Definition at line 213 of file etimer.c.
Referenced by ctimer_expired(), and PROCESS_THREAD().
clock_time_t etimer_next_expiration_time (void)
Get next event timer expiration time.
Returns
Next expiration time of all pending event timers. If there are no pending event timers this function returns 0.
This functions returns next expiration time of all pending event timers.
Definition at line 237 of file etimer.c.
References etimer_pending().
Referenced by clock_isr(), and Java_org_contikios_cooja_corecomm_CLASSNAME_tick().
int etimer_pending (void)
Check if there are any non-expired event timers.
Returns
True if there are active event timers, false if there are no active timers.
This function checks if there are any active event timers that have not expired.
Definition at line 231 of file etimer.c.
Referenced by clock_isr(), etimer_next_expiration_time(), Java_org_contikios_cooja_corecomm_CLASSNAME_tick(), and update_ticks().
void etimer_request_poll (void)
Make the event timer aware that the clock has changed.
This function is used to inform the event timer module that the system clock has been updated. Typically, this function would be called from the timer interrupt handler when the clock has ticked.
Definition at line 145 of file etimer.c.
References process_poll().
Referenced by clock_isr(), Java_org_contikios_cooja_corecomm_CLASSNAME_tick(), and update_ticks().
CCIF void etimer_reset (struct etimer * et)
Reset an event timer with the same interval as was previously set.
Parameters
et A pointer to the event timer.
        This function resets the event timer with the same
        interval that was given to the event timer with the
        etimer_set() function. The start point of the interval
        is the exact time that the event timer last
        expired. Therefore, this function will cause the timer
        to be stable over time, unlike the etimer_restart()
        function.
See Also
etimer_restart()
Definition at line 192 of file etimer.c.
References timer_reset().
Referenced by ctimer_reset(), and uip_ds6_periodic().
void etimer_reset_with_new_interval (struct etimer * et, clock_time_t interval)
Reset an event timer with a new interval.
Parameters
et A pointer to the event timer.
interval The interval before the timer expires.
        This function very similar to etimer_reset. Opposed to
        etimer_reset it is possible to change the timout.
        This allows accurate, non-periodic timers without drift.
See Also
etimer_reset()
Definition at line 184 of file etimer.c.
References timer_reset().
void etimer_restart (struct etimer * et)
Restart an event timer from the current point in time.
Parameters
et A pointer to the event timer.
        This function restarts the event timer with the same
        interval that was given to the etimer_set()
        function. The event timer will start at the current
        time.
        \note A periodic timer will drift if this function is
        used to reset it. For periodic timers, use the
        etimer_reset() function instead.
See Also
etimer_reset()
Definition at line 199 of file etimer.c.
References timer_restart().
Referenced by ctimer_restart().
CCIF void etimer_set (struct etimer * et, clock_time_t interval)
Set an event timer.
Parameters
et A pointer to the event timer
interval The interval before the timer expires.
        This function is used to set an event timer for a time
        sometime in the future. When the event timer expires,
        the event PROCESS_EVENT_TIMER will be posted to the
        process that called the etimer_set() function.
Definition at line 177 of file etimer.c.
References timer_set().
Referenced by ctimer_set_with_process(), PROCESS_THREAD(), rest_activate_resource(), uip_ds6_init(), and uip_ds6_send_rs().
clock_time_t etimer_start_time (struct etimer * et)
Get the start time for the event timer.
Parameters
et A pointer to the event timer
Returns
The start time for the event timer.
        This function returns the start time (when the timer
        was last set) for an event timer.
Definition at line 225 of file etimer.c.
void etimer_stop (struct etimer * et)
Stop a pending event timer.
Parameters
et A pointer to the pending event timer.
        This function stops an event timer that has previously
        been set with etimer_set() or etimer_reset(). After
        this function has been called, the event timer will not
        emit any event when it expires.
Definition at line 243 of file etimer.c.
Referenced by ctimer_stop(), uip_ds6_send_rs(), and uip_reass_over().