Contiki-NG: 802.15.4 frame creation and parsing
802.15.4 frame creation and parsing
IoT networking » Link layer
Files
file frame802154.h
802.15.4 frame creation and parsing functions
Data Structures
struct frame802154_fcf_t
The IEEE 802.15.4 frame has a number of constant/fixed fields that can be counted to make frame construction and max payload calculations easier.
struct frame802154_scf_t
802.15.4 security control bitfield.
struct frame802154_aux_hdr_t
802.15.4 Aux security header
struct frame802154_t
Parameters used by the frame802154_create() function.
Variables
static uint16_t mac_pan_id = IEEE802154_PANID
The 16-bit identifier of the PAN on which the device is operating.
FCF element values definitions
These are some definitions of values used in the FCF.
See the 802.15.4 spec for details.
uint16_t frame802154_get_pan_id (void)
void frame802154_set_pan_id (uint16_t pan_id)
void frame802154_has_panid (frame802154_fcf_t *fcf, int *has_src_pan_id, int *has_dest_pan_id)
int frame802154_check_dest_panid (frame802154_t *frame)
int frame802154_is_broadcast_addr (uint8_t mode, uint8_t *addr)
int frame802154_extract_linkaddr (frame802154_t *frame, linkaddr_t *source_address, linkaddr_t *dest_address)
int frame802154_hdrlen (frame802154_t *p)
Calculates the length of the frame header.
void frame802154_create_fcf (frame802154_fcf_t *fcf, uint8_t *buf)
int frame802154_create (frame802154_t *p, uint8_t *buf)
Creates a frame for transmission over the air.
void frame802154_parse_fcf (uint8_t *data, frame802154_fcf_t *pfcf)
int frame802154_parse (uint8_t *data, int len, frame802154_t *pf)
Parses an input frame.
#define FRAME802154_BEACONFRAME (0x00)
#define FRAME802154_DATAFRAME (0x01)
#define FRAME802154_ACKFRAME (0x02)
#define FRAME802154_CMDFRAME (0x03)
#define FRAME802154_BEACONREQ (0x07)
#define FRAME802154_IEEERESERVED (0x00)
#define FRAME802154_NOADDR (0x00)
Only valid for ACK or Beacon frames.
#define FRAME802154_SHORTADDRMODE (0x02)
#define FRAME802154_LONGADDRMODE (0x03)
#define FRAME802154_NOBEACONS (0x0F)
#define FRAME802154_BROADCASTADDR (0xFFFF)
#define FRAME802154_BROADCASTPANDID (0xFFFF)
#define FRAME802154_IEEE802154_2003 (0x00)
#define FRAME802154_IEEE802154_2006 (0x01)
#define FRAME802154_IEEE802154_2015 (0x02)
#define FRAME802154_SECURITY_LEVEL_NONE (0)
#define FRAME802154_SECURITY_LEVEL_MIC_32 (1)
#define FRAME802154_SECURITY_LEVEL_MIC_64 (2)
#define FRAME802154_SECURITY_LEVEL_MIC_128 (3)
#define FRAME802154_SECURITY_LEVEL_ENC (4)
#define FRAME802154_SECURITY_LEVEL_ENC_MIC_32 (5)
#define FRAME802154_SECURITY_LEVEL_ENC_MIC_64 (6)
#define FRAME802154_SECURITY_LEVEL_ENC_MIC_128 (7)
#define FRAME802154_IMPLICIT_KEY (0)
#define FRAME802154_1_BYTE_KEY_ID_MODE (1)
#define FRAME802154_5_BYTE_KEY_ID_MODE (2)
#define FRAME802154_9_BYTE_KEY_ID_MODE (3)
Detailed Description
Macro Definition Documentation
#define FRAME802154_NOADDR (0x00)
Only valid for ACK or Beacon frames.
Definition at line 109 of file frame802154.h.
Function Documentation
int frame802154_create (frame802154_t * p, uint8_t * buf)
Creates a frame for transmission over the air.
This function is meant to be called by a higher level function, that interfaces to a MAC.
Parameters
p Pointer to frame802154_t struct, which specifies the frame to send.
buf Pointer to the buffer to use for the frame.
Returns
The length of the frame header
Definition at line 392 of file frame802154.c.
References frame802154_fcf_t::ack_required, frame802154_t::aux_hdr, frame802154_t::dest_addr, frame802154_fcf_t::dest_addr_mode, frame802154_t::dest_pid, frame802154_t::fcf, frame802154_aux_hdr_t::frame_counter, frame802154_scf_t::frame_counter_size, frame802154_scf_t::frame_counter_suppression, frame802154_fcf_t::frame_pending, frame802154_fcf_t::frame_type, frame802154_fcf_t::frame_version, frame802154_fcf_t::ie_list_present, frame802154_scf_t::key_id_mode, frame802154_aux_hdr_t::key_index, frame802154_aux_hdr_t::key_source, frame802154_fcf_t::panid_compression, frame802154_aux_hdr_t::security_control, frame802154_fcf_t::security_enabled, frame802154_scf_t::security_level, frame802154_t::seq, frame802154_fcf_t::sequence_number_suppression, frame802154_t::src_addr, frame802154_fcf_t::src_addr_mode, and frame802154_t::src_pid.
Referenced by tsch_packet_create_eack().
int frame802154_hdrlen (frame802154_t * p)
Calculates the length of the frame header.
This function is meant to be called by a higher level function, that interfaces to a MAC.
Parameters
p Pointer to frame802154_t_t struct, which specifies the frame to send.
Returns
The length of the frame header.
Definition at line 358 of file frame802154.c.
References frame802154_fcf_t::ack_required, frame802154_fcf_t::dest_addr_mode, frame802154_fcf_t::frame_pending, frame802154_fcf_t::frame_type, frame802154_fcf_t::frame_version, frame802154_fcf_t::ie_list_present, frame802154_fcf_t::panid_compression, frame802154_fcf_t::security_enabled, frame802154_fcf_t::sequence_number_suppression, and frame802154_fcf_t::src_addr_mode.
Referenced by tsch_packet_create_eack().
int frame802154_parse (uint8_t * data, int len, frame802154_t * pf)
Parses an input frame.
Scans the input frame to find each section, and stores the information of each section in a frame802154_t structure.
Parameters
data The input data from the radio chip.
len The size of the input data
pf The frame802154_t struct to store the parsed frame information.
Definition at line 500 of file frame802154.c.
References frame802154_t::aux_hdr, frame802154_t::dest_addr, frame802154_fcf_t::dest_addr_mode, frame802154_t::dest_pid, frame802154_t::fcf, frame802154_aux_hdr_t::frame_counter, frame802154_scf_t::frame_counter_size, frame802154_scf_t::frame_counter_suppression, frame802154_scf_t::key_id_mode, frame802154_aux_hdr_t::key_index, frame802154_aux_hdr_t::key_source, linkaddr_copy(), linkaddr_null, frame802154_t::payload, frame802154_t::payload_len, frame802154_aux_hdr_t::security_control, frame802154_fcf_t::security_enabled, frame802154_scf_t::security_level, frame802154_t::seq, frame802154_fcf_t::sequence_number_suppression, frame802154_t::src_addr, frame802154_fcf_t::src_addr_mode, and frame802154_t::src_pid.
Referenced by sixtop_input(), tsch_packet_parse_eack(), tsch_packet_parse_eb(), tsch_radio_off(), tsch_schedule_keepalive_immediately(), and tsch_security_secure_frame().
Variable Documentation
uint16_t mac_pan_id = IEEE802154_PANID static
The 16-bit identifier of the PAN on which the device is operating.
If this value is 0xffff, the device is not associated.
Definition at line 76 of file frame802154.c.