Contiki-NG: uIP: the IPv6 stack
uIP: the IPv6 stack
Network layer
The low-power IPv6 stack.
Modules
A simple UDP API
The default Contiki UDP API is difficult to use.
Architecture specific uIP functions
The functions in the architecture specific module implement the IP check sum and 32-bit additions.
Configuration options for uIP
uIP is configured using the per-project configuration file "uipopt.h".
IPv6 Multicast Forwarding
We currently support 2 engines:
Protosockets library
The protosocket library provides an interface to the uIP stack that is similar to the traditional BSD socket interface.
Sicslowpan
The Contiki/uIP interface
TCP/IP support in Contiki is implemented using the uIP TCP/IP stack.
Variables used in uIP device drivers
uIP has a few global variables that are used in device drivers for uIP.
uIP application functions
Functions used by an application running on top of uIP.
uIP configuration functions
The uIP configuration functions are used for setting run-time parameters in uIP such as IP addresses.
uIP conversion functions
These functions can be used for converting between different data formats used by uIP.
uIP device driver functions
These functions are used by a network device driver for interacting with uIP.
uIP hostname resolver functions
The uIP DNS resolver functions are used to lookup a hostname and map it to a numerical IP address.
uIP initialization functions
The uIP initialization functions are used for booting uIP.
Files
file uip-ds6-nbr.c
IPv6 Neighbor cache (link-layer/IPv6 address mapping)
file uip-ds6-nbr.h
IPv6 Neighbor cache (link-layer/IPv6 address mapping)
file uip-ds6-route.c
Routing table manipulation.
file uip-ds6-route.h
Header file for routing table manipulation.
file uip-ds6.c
IPv6 data structure manipulation.
file uip-ds6.h
Header file for IPv6-related data structures.
file uip-icmp6.c
ICMPv6 (RFC 4443) implementation, with message and error handling.
file uip-icmp6.h
Header file for ICMPv6 message and error handing (RFC 4443)
file uip-nameserver.c
    uIP Name Server interface
file uip-nameserver.h
    uIP Name Server interface
file uip-nd6.c
Neighbor discovery (RFC 4861)
file uip-nd6.h
Header file for IPv6 Neighbor discovery (RFC 4861)
file uip.h
Header file for the uIP TCP/IP stack.
file uip6.c
The uIP TCP/IPv6 stack code.
file rpl-nbr-policy.c
Default RPL NBR policy decides when to add a new discovered node to the nbr table from RPL.
Data Structures
struct uip_ds6_nbr
An entry in the nbr cache.
struct uip_ds6_route_neighbor_routes
The neighbor routes hold a list of routing table entries that are attached to a specific neihbor.
struct uip_ds6_route
An entry in the routing table.
struct uip_ds6_route_neighbor_route
A neighbor route list entry, used on the uip_ds6_route->neighbor_routes->route_list list.
struct uip_ds6_defrt
An entry in the default router list.
struct uip_ds6_prefix
A prefix list entry.
struct uip_ds6_addr
Unicast address structure.
struct uip_ds6_aaddr
Anycast address.
struct uip_ds6_maddr
A multicast address.
struct uip_ds6_netif
Interface structure (contains all the interface variables)
struct uip_ds6_element
Generic type for a DS6, to use a common loop though all DS.
struct uip_icmp6_error
ICMPv6 Error message constant part.
struct uip_nd6_ns
A neighbor solicitation constant part.
struct uip_nd6_na
A neighbor advertisement constant part.
struct uip_nd6_rs
A router solicitation constant part.
struct uip_nd6_ra
A router advertisement constant part.
struct uip_nd6_redirect
A redirect message constant part.
struct uip_nd6_opt_hdr
ND option header.
struct uip_nd6_opt_prefix_info
ND option prefix information.
struct uip_nd6_opt_mtu
ND option MTU.
struct uip_nd6_opt_dns
ND option RDNSS.
union uip_ip4addr_t
Representation of an IP address.
struct uip_802154_shortaddr
16 bit 802.15.4 address
struct uip_802154_longaddr
64 bit 802.15.4 address
struct uip_80211_addr
802.11 address
struct uip_eth_addr
802.3 address
struct uip_conn
Representation of a uIP TCP connection.
struct uip_udp_conn
Representation of a uIP UDP connection.
struct uip_stats
The structure holding the TCP/IP statistics that are gathered if UIP_STATISTICS is set to 1.
struct uip_eth_hdr
The Ethernet header.
Macros
#define NBR_INCOMPLETE 0
Possible states for the nbr cache entries.
#define UIP_DS6_ROUTE_STATE_TYPE rpl_route_entry_t
define some additional RPL related route state and neighbor callback for RPL - if not a DS6_ROUTE_STATE is already set
#define UIP_DS6_DEFRT_NBS 0
Configuration.
#define ADDR_TENTATIVE 0
Possible states for the an address (RFC 4862)
#define ADDR_ANYTYPE 0
How the address was acquired: Autoconf, DHCP or manually.
#define UIP_DS6_PERIOD (CLOCK_SECOND/10)
General DS6 definitions.
#define UIP_ICMP6_ECHO_REQUEST_LEN 4
Echo Request constant part length.
#define UIP_ICMP6_ERROR_LEN 4
ICMPv6 Error message constant part length.
#define DNS_EXPIRATION(r)
Expiration time in seconds.
#define UIP_ND6_OPT_HDR_BUF ((uip_nd6_opt_hdr *)&uip_buf[uip_l2_l3_icmp_hdr_len + nd6_opt_offset])
Pointer to ND option.
#define UIP_ND6_DEF_MAXDADNS UIP_ND6_SEND_NS
Do not try DAD when using EUI-64 as allowed by draft-ietf-6lowpan-nd-15 section 8.2.
#define uip_l2_l3_hdr_len (UIP_LLH_LEN + UIP_IPH_LEN + uip_ext_len)
The sums below are quite used in ND.
#define UIP_LLADDR_LEN UIP_802154_LONGADDR_LEN
Link layer address length.
#define UIP_STAT(s)
The uIP TCP/IP statistics.
#define UIP_APPDATA_SIZE
The buffer size available for user data in the uip_buf buffer.
#define UIP_LLPREF_LEN 10
Length of the link local prefix.
#define uip_is_addr_loopback(a)
Is IPv6 address a the unspecified address a is of type uip_ipaddr_t.
#define uip_is_addr_unspecified(a)
Is IPv6 address a the unspecified address a is of type uip_ipaddr_t.
#define uip_is_addr_linklocal_allnodes_mcast(a)
Is IPv6 address a the link local all-nodes multicast address.
#define uip_is_addr_linklocal_allrouters_mcast(a)
Is IPv6 address a the link local all-routers multicast address.
#define uip_is_addr_linklocal(a)
is addr (a) a link local unicast address, see RFC 4291 i.e.
#define uip_create_unspecified(a) uip_ip6addr(a, 0, 0, 0, 0, 0, 0, 0, 0)
set IP address a to unspecified
#define uip_create_linklocal_allnodes_mcast(a) uip_ip6addr(a, 0xff02, 0, 0, 0, 0, 0, 0, 0x0001)
set IP address a to the link local all-nodes multicast address
#define uip_create_linklocal_allrouters_mcast(a) uip_ip6addr(a, 0xff02, 0, 0, 0, 0, 0, 0, 0x0002)
set IP address a to the link local all-routers multicast address
#define uip_is_addr_solicited_node(a)
is addr (a) a solicited node multicast address, see RFC 4291 a is of type uip_ipaddr_t*
#define uip_create_solicited_node(a, b)
put in b the solicited node address corresponding to address a both a and b are of type uip_ipaddr_t*
#define uip_is_addr_mac_addr_based(a, m)
was addr (a) forged based on the mac address m a type is uip_ipaddr_t m type is uiplladdr_t
#define uip_is_addr_mcast(a) (((a)->u8[0]) == 0xFF)
is address a multicast address, see RFC 4291 a is of type uip_ipaddr_t*
#define uip_is_addr_mcast_global(a)
is address a global multicast address (FFxE::/16), a is of type uip_ip6addr_t*
#define uip_is_addr_mcast_non_routable(a)
is address a non-routable multicast address.
#define uip_is_addr_mcast_routable(a)
is address a routable multicast address.
#define uip_is_mcast_group_id_all_nodes(a)
is group-id of multicast address a the all nodes group-id
#define uip_is_mcast_group_id_all_routers(a)
is group-id of multicast address a the all routers group-id
#define uip_are_solicited_bytes_equal(a, b)
are last three bytes of both addresses equal? This is used to compare solicited node multicast addresses
#define UIP_FW_LOCAL
A non-error message that indicates that a packet should be processed locally.
#define UIP_FW_OK
A non-error message that indicates that something went OK.
#define UIP_FW_FORWARDED
A non-error message that indicates that a packet was forwarded.
#define UIP_FW_ZEROLEN
A non-error message that indicates that a zero-length packet transmission was attempted, and that no packet was sent.
#define UIP_FW_TOOLARGE
An error message that indicates that a packet that was too large for the outbound network interface was detected.
#define UIP_FW_NOROUTE
An error message that indicates that no suitable interface could be found for an outbound packet.
#define UIP_FW_DROPPED
An error message that indicates that a packet that should be forwarded or output was dropped.
Typedefs
typedef struct uip_ds6_nbr uip_ds6_nbr_t
An entry in the nbr cache.
typedef struct uip_ds6_route uip_ds6_route_t
An entry in the routing table.
typedef struct uip_ds6_defrt uip_ds6_defrt_t
An entry in the default router list.
typedef struct uip_ds6_prefix uip_ds6_prefix_t
A prefix list entry.
typedef struct uip_ds6_addr uip_ds6_addr_t
Unicast address structure.
typedef struct uip_ds6_aaddr uip_ds6_aaddr_t
Anycast address.
typedef struct uip_ds6_maddr uip_ds6_maddr_t
A multicast address.
typedef struct uip_ds6_netif uip_ds6_netif_t
Interface structure (contains all the interface variables)
typedef struct uip_ds6_element uip_ds6_element_t
Generic type for a DS6, to use a common loop though all DS.
typedef struct uip_icmp6_error uip_icmp6_error
ICMPv6 Error message constant part.
typedef struct
uip_nameserver_record uip_nameserver_record
Nameserver record.
typedef union uip_ip4addr_t uip_ip4addr_t
Representation of an IP address.
typedef struct uip_802154_shortaddr uip_802154_shortaddr
16 bit 802.15.4 address
typedef struct uip_802154_longaddr uip_802154_longaddr
64 bit 802.15.4 address
typedef struct uip_80211_addr uip_80211_addr
802.11 address
typedef struct uip_eth_addr uip_eth_addr
802.3 address
typedef uip_802154_longaddr uip_lladdr_t
802.15.4 address
Functions
uip_ds6_nbr_t * uip_ds6_nbr_add (const uip_ipaddr_t *ipaddr, const uip_lladdr_t *lladdr, uint8_t isrouter, uint8_t state, nbr_table_reason_t reason, void *data)
Neighbor Cache basic routines.
uip_ds6_nbr_t * uip_ds6_get_least_lifetime_neighbor (void)
This searches inside the neighbor table for the neighbor that is about to expire the next.
void uip_ds6_init (void)
Initialize data structures.
void uip_ds6_periodic (void)
Periodic processing of data structures.
uint8_t uip_ds6_list_loop (uip_ds6_element_t *list, uint8_t size, uint16_t elementsize, uip_ipaddr_t *ipaddr, uint8_t ipaddrlen, uip_ds6_element_t **out_element)
Generic loop routine on an abstract data structure, which generalizes all data structures used in DS6.
uip_ds6_addr_t * uip_ds6_addr_add (uip_ipaddr_t *ipaddr, unsigned long vlifetime, uint8_t type)
Add a unicast address to the interface.
void uip_ds6_select_src (uip_ipaddr_t *src, uip_ipaddr_t *dst)
Source address selection, see RFC 3484.
void uip_ds6_set_addr_iid (uip_ipaddr_t *ipaddr, uip_lladdr_t *lladdr)
set the last 64 bits of an IP address based on the MAC address
void uip_ds6_set_lladdr_from_iid (uip_lladdr_t *lladdr, const uip_ipaddr_t *ipaddr)
Build a link-layer address from an IPv6 address based on its UUID64.
uint8_t get_match_length (uip_ipaddr_t *src, uip_ipaddr_t *dst)
Get the number of matching bits of two addresses.
void uip_ds6_dad (uip_ds6_addr_t *addr)
Perform Duplicate Address Selection on one address.
int uip_ds6_dad_failed (uip_ds6_addr_t *addr)
Callback when DAD failed.
void uip_ds6_send_rs (void)
Send periodic RS to find router.
uint32_t uip_ds6_compute_reachable_time (void)
Compute the reachable time based on base reachable time, see RFC 4861.
void uip_process (uint8_t flag)
process the options within a hop by hop or destination option header
uint16_t uip_chksum (uint16_t *data, uint16_t len)
Calculate the Internet checksum over a buffer.
uint16_t uip_ipchksum (void)
Calculate the IP header checksum of the packet header in uip_buf.
uint16_t uip_tcpchksum (void)
Calculate the TCP checksum of the packet in uip_buf and uip_appdata.
uint16_t uip_udpchksum (void)
Calculate the UDP checksum of the packet in uip_buf and uip_appdata.
uint16_t uip_icmp6chksum (void)
Calculate the ICMP checksum of the packet in uip_buf.
void uip_add32 (uint8_t *op32, uint16_t op16)
Carry out a 32-bit addition.
void uip_init (void)
uIP initialization function.
struct uip_udp_conn * uip_udp_new (const uip_ipaddr_t *ripaddr, uint16_t rport)
Set up a new UDP connection.
void uip_unlisten (uint16_t port)
Stop listening to the specified port.
void uip_listen (uint16_t port)
Start listening to the specified port.
void uip_reass_over (void)
Abandon the reassembly of the current packet.
static uint8_t ext_hdr_options_process (void)
Process the options in Destination and Hop By Hop extension headers.
uint16_t uip_htons (uint16_t val)
Convert a 16-bit quantity from host byte order to network byte order.
void uip_send (const void *data, int len)
Send data on the current connection.
void rpl_dag_init (void)
Initializes rpl-dag module.
rpl_instance_t * rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
int rpl_has_downward_route (void)
Get the RPL's best guess on if we have downward route or not.
rpl_dag_t * rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
void rpl_process_dio (uip_ipaddr_t *from, rpl_dio_t *dio)
Processes incoming DIO.
void rpl_ext_header_remove (void)
Removes all RPL extension headers.
enum rpl_mode rpl_get_mode (void)
Get the RPL mode.
enum rpl_mode rpl_set_mode (enum rpl_mode m)
Set the RPL mode.
void rpl_link_callback (const linkaddr_t *addr, int status, int numtx)
Called by lower layers after every packet transmission.
void rpl_init (void)
Initialize RPL main module.
Variables
struct etimer uip_ds6_timer_periodic
Timer for maintenance of data structures.
struct etimer uip_ds6_timer_rs
RS timer, to schedule RS sending.
static uint8_t rscount
number of rs already sent
uip_ds6_netif_t uip_ds6_if
The single interface.
struct etimer uip_ds6_timer_periodic
Timer for maintenance of data structures.
struct etimer uip_ds6_timer_rs
RS timer, to schedule RS sending.
static uip_ipaddr_t tmp_ipaddr
temporary IP address
CCIF void * uip_appdata
Pointer to the application data in the packet buffer.
CCIF struct uip_conn * uip_conn
Pointer to the current TCP connection.
struct uip_udp_conn * uip_udp_conn
The current UDP connection.
struct uip_icmp6_conn uip_icmp6_conns
single possible icmpv6 "connection"
CCIF uip_lladdr_t uip_lladdr
Host L2 address.
struct etimer uip_reass_timer
Timer for reassembly.
Default router list basic routines
uip_ds6_defrt_t * uip_ds6_defrt_head (void)
uip_ds6_defrt_t * uip_ds6_defrt_add (uip_ipaddr_t *ipaddr, unsigned long interval)
void uip_ds6_defrt_rm (uip_ds6_defrt_t *defrt)
uip_ds6_defrt_t * uip_ds6_defrt_lookup (uip_ipaddr_t *ipaddr)
uip_ipaddr_t * uip_ds6_defrt_choose (void)
void uip_ds6_defrt_periodic (void)
Routing Table basic routines
uip_ipaddr_t * uip_ds6_route_nexthop (uip_ds6_route_t *route)
uip_ds6_route_t * uip_ds6_route_head (void)
uip_ds6_route_t * uip_ds6_route_next (uip_ds6_route_t *r)
int uip_ds6_route_is_nexthop (const uip_ipaddr_t *ipaddr)
int uip_ds6_route_num_routes (void)
uip_ds6_route_t * uip_ds6_route_lookup (uip_ipaddr_t *addr)
uip_ds6_route_t * uip_ds6_route_add (uip_ipaddr_t *ipaddr, uint8_t length, uip_ipaddr_t *nexthop)
void uip_ds6_route_rm (uip_ds6_route_t *route)
void uip_ds6_route_rm_by_nexthop (uip_ipaddr_t *nexthop)
"DS6" Data structures
uip_ds6_netif_t uip_ds6_if
The single interface.
uip_ds6_prefix_t uip_ds6_prefix_list [UIP_DS6_PREFIX_NB]
Prefix list.
uint8_t uip_ds6_addr_size
uint8_t uip_ds6_netif_addr_list_offset
ICMPv6 message types
#define ICMP6_DST_UNREACH 1
dest unreachable
#define ICMP6_PACKET_TOO_BIG 2
packet too big
#define ICMP6_TIME_EXCEEDED 3
time exceeded
#define ICMP6_PARAM_PROB 4
ip6 header bad
#define ICMP6_ECHO_REQUEST 128
Echo request.
#define ICMP6_ECHO_REPLY 129
Echo reply.
#define ICMP6_RS 133
Router Solicitation.
#define ICMP6_RA 134
Router Advertisement.
#define ICMP6_NS 135
Neighbor Solicitation.
#define ICMP6_NA 136
Neighbor advertisement.
#define ICMP6_REDIRECT 137
Redirect.
#define ICMP6_RPL 155
RPL.
#define ICMP6_PRIV_EXP_100 100
Private Experimentation.
#define ICMP6_PRIV_EXP_101 101
Private Experimentation.
#define ICMP6_PRIV_EXP_200 200
Private Experimentation.
#define ICMP6_PRIV_EXP_201 201
Private Experimentation.
#define ICMP6_ROLL_TM ICMP6_PRIV_EXP_200
ROLL Trickle Multicast.
#define ICMP6_ESMRF ICMP6_PRIV_EXP_201
ESMRF Multicast.
ICMPv6 Destination Unreachable message codes
#define ICMP6_DST_UNREACH_NOROUTE 0
no route to destination
#define ICMP6_DST_UNREACH_ADMIN 1
administratively prohibited
#define ICMP6_DST_UNREACH_NOTNEIGHBOR 2
not a neighbor(obsolete)
#define ICMP6_DST_UNREACH_BEYONDSCOPE 2
beyond scope of source address
#define ICMP6_DST_UNREACH_ADDR 3
address unreachable
#define ICMP6_DST_UNREACH_NOPORT 4
port unreachable
ICMPv6 Time Exceeded message codes
#define ICMP6_TIME_EXCEED_TRANSIT 0
ttl==0 in transit
#define ICMP6_TIME_EXCEED_REASSEMBLY 1
ttl==0 in reass
ICMPv6 Parameter Problem message codes
#define ICMP6_PARAMPROB_HEADER 0
erroneous header field
#define ICMP6_PARAMPROB_NEXTHEADER 1
unrecognized next header
#define ICMP6_PARAMPROB_OPTION 2
unrecognized option
ICMPv6 RFC4443 Message processing and sending
typedef void(* uip_icmp6_echo_reply_callback_t)(uip_ipaddr_t *source, uint8_t ttl, uint8_t *data, uint16_t datalen)
typedef struct
uip_icmp6_input_handler uip_icmp6_input_handler_t
uint8_t uip_icmp6_input (uint8_t type, uint8_t icode)
Handle an incoming ICMPv6 message.
void uip_icmp6_register_input_handler (uip_icmp6_input_handler_t *handler)
Register a handler which can handle a specific ICMPv6 message type.
void uip_icmp6_error_output (uint8_t type, uint8_t code, uint32_t param)
Send an icmpv6 error message.
void uip_icmp6_send (const uip_ipaddr_t *dest, int type, int code, int payload_len)
Send an icmpv6 message.
void uip_icmp6_echo_reply_callback_add (struct uip_icmp6_echo_reply_notification *n, uip_icmp6_echo_reply_callback_t c)
Add a callback function for ping replies.
void uip_icmp6_echo_reply_callback_rm (struct uip_icmp6_echo_reply_notification *n)
Remove a callback function for ping replies.
void uip_icmp6_init (void)
Initialise the uIP ICMPv6 core.
#define UIP_ICMP6_INPUT_SUCCESS 0
#define UIP_ICMP6_INPUT_ERROR 1
#define UIP_ICMP6_HANDLER_CODE_ANY 0xFF /* Handle all codes for this type */
#define UIP_ICMP6_HANDLER(name, type, code, func) static uip_icmp6_input_handler_t name = { NULL, type, code, func }
List and memory block
static uip_ipaddr_t serveraddr
static uint32_t serverlifetime
General
#define UIP_NAMESERVER_POOL_SIZE 1
Number of Nameservers to keep.
#define UIP_NAMESERVER_INFINITE_LIFETIME 0xFFFFFFFF
Infinite Lifetime indicator.
Nameserver maintenance
void uip_nameserver_update (const uip_ipaddr_t *nameserver, uint32_t lifetime)
Initialize the module variables.
uip_ipaddr_t * uip_nameserver_get (uint8_t num)
Get a Nameserver ip address given in RA.
uint32_t uip_nameserver_next_expiration (void)
Get next expiration time.
uint16_t uip_nameserver_count (void)
Get the number of recorded name servers.
Pointers to the header structures.
All pointers except UIP_IP_BUF depend on uip_ext_len, which at packet reception, is the total length of the extension headers.
The pointer to ND6 options header also depends on nd6_opt_offset, which we set in each function.
Care should be taken when manipulating these buffers about the value of these length variables
#define UIP_IP_BUF ((struct uip_ip_hdr *)&uip_buf[UIP_LLH_LEN])
Pointer to IP header.
#define UIP_ICMP_BUF ((struct uip_icmp_hdr *)&uip_buf[uip_l2_l3_hdr_len])
Pointer to ICMP header.
#define UIP_ND6_RS_BUF ((uip_nd6_rs *)&uip_buf[uip_l2_l3_icmp_hdr_len])
#define UIP_ND6_RA_BUF ((uip_nd6_ra *)&uip_buf[uip_l2_l3_icmp_hdr_len])
#define UIP_ND6_NS_BUF ((uip_nd6_ns *)&uip_buf[uip_l2_l3_icmp_hdr_len])
#define UIP_ND6_NA_BUF ((uip_nd6_na *)&uip_buf[uip_l2_l3_icmp_hdr_len])
General
#define UIP_ND6_HOP_LIMIT 255
HOP LIMIT to be used when sending ND messages (255)
#define UIP_ND6_INFINITE_LIFETIME 0xFFFFFFFF
INFINITE lifetime.
RFC 4861 Host constant
#define UIP_ND6_MAX_RTR_SOLICITATION_DELAY 1
Maximum router solicitation delay.
#define UIP_ND6_RTR_SOLICITATION_INTERVAL 4
Router solicitation interval.
#define UIP_ND6_MAX_RTR_SOLICITATIONS 3
Maximum router solicitations.
RFC 4861 Router constants
#define UIP_ND6_SEND_RA 1 /* enable/disable RA sending */
#define UIP_ND6_SEND_NS 1 /* enable/disable NS sending */
#define UIP_ND6_SEND_NA 1 /* enable/disable NA sending */
#define UIP_ND6_AUTOFILL_NBR_CACHE 0
#define UIP_ND6_MAX_RA_INTERVAL 600
#define UIP_ND6_MIN_RA_INTERVAL (UIP_ND6_MAX_RA_INTERVAL / 3)
#define UIP_ND6_M_FLAG 0
#define UIP_ND6_O_FLAG (UIP_ND6_RA_RDNSS || UIP_ND6_RA_DNSSL)
#define UIP_ND6_ROUTER_LIFETIME 3 * UIP_ND6_MAX_RA_INTERVAL
#define UIP_ND6_MAX_INITIAL_RA_INTERVAL 16 /*seconds*/
#define UIP_ND6_MAX_INITIAL_RAS 3 /*transmissions*/
#define UIP_ND6_MIN_DELAY_BETWEEN_RAS 3 /*seconds*/
#define UIP_ND6_MAX_RA_DELAY_TIME_MS 500 /*milli seconds*/
RFC 4861 Node constant
#define UIP_ND6_MAX_MULTICAST_SOLICIT 3
#define UIP_ND6_MAX_UNICAST_SOLICIT 3
#define UIP_ND6_REACHABLE_TIME 60000
#define UIP_ND6_RETRANS_TIMER 1000
#define UIP_ND6_DELAY_FIRST_PROBE_TIME 5
#define UIP_ND6_MIN_RANDOM_FACTOR(x) (x / 2)
#define UIP_ND6_MAX_RANDOM_FACTOR(x) ((x) + (x) / 2)
RFC 6106 RA DNS Options Constants
#define UIP_ND6_RA_RDNSS 0
#define UIP_ND6_RA_DNSSL 0
ND6 option types
#define UIP_ND6_OPT_SLLAO 1
#define UIP_ND6_OPT_TLLAO 2
#define UIP_ND6_OPT_PREFIX_INFO 3
#define UIP_ND6_OPT_REDIRECTED_HDR 4
#define UIP_ND6_OPT_MTU 5
#define UIP_ND6_OPT_RDNSS 25
#define UIP_ND6_OPT_DNSSL 31
#define UIP_ND6_OPT_TYPE_OFFSET 0
#define UIP_ND6_OPT_LEN_OFFSET 1
#define UIP_ND6_OPT_DATA_OFFSET 2
ND6 message length (excluding options)
#define UIP_ND6_NA_LEN 20
#define UIP_ND6_NS_LEN 20
#define UIP_ND6_RA_LEN 12
#define UIP_ND6_RS_LEN 4
ND6 option length in bytes
#define UIP_ND6_OPT_HDR_LEN 2
#define UIP_ND6_OPT_PREFIX_INFO_LEN 32
#define UIP_ND6_OPT_MTU_LEN 8
#define UIP_ND6_OPT_RDNSS_LEN 1
#define UIP_ND6_OPT_DNSSL_LEN 1
#define UIP_ND6_OPT_LLAO_LEN 8
length of a ND6 LLAO option for default L2 type (e.g.
Neighbor Advertisement flags masks
#define UIP_ND6_NA_FLAG_ROUTER 0x80
#define UIP_ND6_NA_FLAG_SOLICITED 0x40
#define UIP_ND6_NA_FLAG_OVERRIDE 0x20
#define UIP_ND6_RA_FLAG_ONLINK 0x80
#define UIP_ND6_RA_FLAG_AUTONOMOUS 0x40
ND message structures
typedef struct uip_nd6_ns uip_nd6_ns
A neighbor solicitation constant part.
typedef struct uip_nd6_na uip_nd6_na
A neighbor advertisement constant part.
typedef struct uip_nd6_rs uip_nd6_rs
A router solicitation constant part.
typedef struct uip_nd6_ra uip_nd6_ra
A router advertisement constant part.
typedef struct uip_nd6_redirect uip_nd6_redirect
A redirect message constant part.
ND Option structures
typedef struct uip_nd6_opt_hdr uip_nd6_opt_hdr
ND option header.
typedef struct
uip_nd6_opt_prefix_info uip_nd6_opt_prefix_info
ND option prefix information.
typedef struct uip_nd6_opt_mtu uip_nd6_opt_mtu
ND option MTU.
typedef struct uip_nd6_opt_dns uip_nd6_opt_dns
ND option RDNSS.
typedef struct
uip_nd6_opt_redirected_hdr uip_nd6_opt_redirected_hdr
ND Messages Processing and Generation
void uip_nd6_ns_output (uip_ipaddr_t *src, uip_ipaddr_t *dest, uip_ipaddr_t *tgt)
Send a neighbor solicitation, send a Neighbor Advertisement.
void uip_nd6_rs_output (void)
Send a Router Solicitation.
void uip_nd6_init (void)
Initialise the uIP ND core.
#define UIP_PROTO_HBHO 0
extension headers types
#define UIP_EXT_HDR_OPT_PAD1 0
Destination and Hop By Hop extension headers option types.
#define UIP_EXT_HDR_BITMAP_HBHO 0x01
Bitmaps for extension header processing.
Layer 2 variables
uip_lladdr_t uip_lladdr = {{0x00,0x06,0x98,0x00,0x02,0x32}}
Host L2 address.
Layer 3 variables
uint8_t * uip_next_hdr
Type of the next header in IPv6 header or extension headers.
uint8_t uip_ext_bitmap = 0
bitmap we use to record which IPv6 headers we have already seen
uint8_t uip_ext_len = 0
length of the extension headers read.
uint8_t uip_ext_opt_offset = 0
length of the header options read
Buffer defines
#define FBUF ((struct uip_tcpip_hdr *)&uip_reassbuf[0])
#define UIP_IP_BUF ((struct uip_ip_hdr *)&uip_buf[UIP_LLH_LEN])
#define UIP_ICMP_BUF ((struct uip_icmp_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_UDP_BUF ((struct uip_udp_hdr *)&uip_buf[UIP_LLH_LEN + UIP_IPH_LEN])
#define UIP_TCP_BUF ((struct uip_tcp_hdr *)&uip_buf[UIP_LLH_LEN + UIP_IPH_LEN])
#define UIP_EXT_BUF ((struct uip_ext_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_ROUTING_BUF ((struct uip_routing_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_FRAG_BUF ((struct uip_frag_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_HBHO_BUF ((struct uip_hbho_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_DESTO_BUF ((struct uip_desto_hdr *)&uip_buf[uip_l2_l3_hdr_len])
#define UIP_EXT_HDR_OPT_BUF ((struct uip_ext_hdr_opt *)&uip_buf[uip_l2_l3_hdr_len + uip_ext_opt_offset])
#define UIP_EXT_HDR_OPT_PADN_BUF ((struct uip_ext_hdr_opt_padn *)&uip_buf[uip_l2_l3_hdr_len + uip_ext_opt_offset])
#define UIP_EXT_HDR_OPT_RPL_BUF ((struct uip_ext_hdr_opt_rpl *)&uip_buf[uip_l2_l3_hdr_len + uip_ext_opt_offset])
#define UIP_ICMP6_ERROR_BUF ((struct uip_icmp6_error *)&uip_buf[uip_l2_l3_icmp_hdr_len])
Buffer variables
uip_buf_t uip_aligned_buf
Packet buffer for incoming and outgoing packets.
void * uip_appdata
Pointer to the application data in the packet buffer.
void * uip_sappdata
uint16_t uip_len
The length of the packet in the uip_buf buffer.
uint16_t uip_slen
General variables
uint8_t uip_flags
struct uip_conn * uip_conn
Pointer to the current TCP connection.
static uint16_t lastport
TCP defines
#define TCP_FIN 0x01
#define TCP_SYN 0x02
#define TCP_RST 0x04
#define TCP_PSH 0x08
#define TCP_ACK 0x10
#define TCP_URG 0x20
#define TCP_CTL 0x3f
#define TCP_OPT_END 0 /* End of TCP options list */
#define TCP_OPT_NOOP 1 /* "No-operation" TCP option */
#define TCP_OPT_MSS 2 /* Maximum segment size TCP option */
#define TCP_OPT_MSS_LEN 4 /* Length of TCP MSS option. */
TCP variables
struct uip_conn uip_conns [UIP_TCP_CONNS]
uint16_t uip_listenports [UIP_LISTENPORTS]
static uint8_t iss [4]
uint8_t uip_acc32 [4]
4-byte array used for the 32-bit sequence number calculations.
UDP variables
struct uip_udp_conn * uip_udp_conn
The current UDP connection.
struct uip_udp_conn uip_udp_conns [UIP_UDP_CONNS]
ICMPv6 variables
struct uip_icmp6_conn uip_icmp6_conns
single possible icmpv6 "connection"
Detailed Description
The low-power IPv6 stack.
{@
Macro Definition Documentation
#define UIP_APPDATA_SIZE
The buffer size available for user data in the uip_buf buffer.
This macro holds the available size for user data in the uip_buf buffer. The macro is intended to be used for checking bounds of available user data.
Example:
snprintf(uip_appdata, UIP_APPDATA_SIZE, "%u\n", i);
Definition at line 1883 of file uip.h.
#define UIP_DS6_DEFRT_NBS 0
Configuration.
For all tables (Neighbor cache, Prefix List, Routing Table, Default Router List, Unicast address list, multicast address list, anycast address list), we define:
the number of elements requested by the user in contiki configuration (name suffixed by _NBU)
the number of elements assigned by the system (name suffixed by _NBS)
the total number of elements is the sum (name suffixed by _NB) The routing table definitions can be found in uip-ds6-route.h The Neighbor cache definitions can be found in nbr-table.h
Definition at line 64 of file uip-ds6.h.
#define UIP_DS6_PERIOD (CLOCK_SECOND/10)
General DS6 definitions.
Period for uip-ds6 periodic task
Definition at line 168 of file uip-ds6.h.
Referenced by uip_ds6_init().
#define UIP_EXT_HDR_BITMAP_HBHO 0x01
Bitmaps for extension header processing.
When processing extension headers, we should record somehow which one we see, because you cannot have twice the same header, except for destination We store all this in one uint8_t bitmap one bit for each header expected. The order in the bitmap is the order recommended in RFC2460
Definition at line 1919 of file uip.h.
Referenced by uip_process().
#define uip_is_addr_linklocal (a)
Value:
((a)->u8[0] == 0xfe &&                         \
   (a)->u8[1] == 0x80)
is addr (a) a link local unicast address, see RFC 4291 i.e.
is (a) on prefix FE80::/10 a is of type uip_ipaddr_t*
Definition at line 2012 of file uip.h.
Referenced by compress_hdr_iphc(), log_6addr_compact(), output(), ra_input(), rpl_dag_root_init_dag_immediately(), rpl_ext_header_update(), rpl_get_global_address(), uip_ds6_dad_failed(), uip_ds6_select_src(), and uip_process().
#define uip_is_addr_mcast_non_routable (a)
Value:
((((a)->u8[0]) == 0xFF) && \
   (((a)->u8[1] & 0x0F) <= 0x02))
is address a non-routable multicast address.
Scopes 1 (interface-local) and 2 (link-local) are non-routable See RFC4291 and draft-ietf-6man-multicast-scopes a is of type uip_ip6addr_t*
Definition at line 2113 of file uip.h.
Referenced by accept().
#define uip_is_addr_mcast_routable (a)
Value:
((((a)->u8[0]) == 0xFF) && \
   (((a)->u8[1] & 0x0F) > 0x02))
is address a routable multicast address.
Scope 3 (Realm-Local) or higher are routable Realm-Local scope is defined in draft-ietf-6man-multicast-scopes See RFC4291 and draft-ietf-6man-multicast-scopes a is of type uip_ip6addr_t*
Definition at line 2124 of file uip.h.
Referenced by uip_ds6_select_src(), and uip_process().
#define uip_l2_l3_hdr_len (UIP_LLH_LEN + UIP_IPH_LEN + uip_ext_len)
The sums below are quite used in ND.
When used for uip_buf, we include link layer length when used for uip_len, we do not, hence we need values with and without LLH_LEN we do not use capital letters as these values are variable
Definition at line 75 of file uip.h.
#define UIP_ND6_OPT_LLAO_LEN 8
length of a ND6 LLAO option for default L2 type (e.g.
Ethernet)
Definition at line 243 of file uip-nd6.h.
Referenced by uip_nd6_rs_output().
#define UIP_ND6_RS_BUF ((uip_nd6_rs *)&uip_buf[uip_l2_l3_icmp_hdr_len])
Pointers to messages just after icmp header
Definition at line 99 of file uip-nd6.c.
#define UIP_STAT (s)
The uIP TCP/IP statistics.
This is the variable in which the uIP TCP/IP statistics are gathered.
Definition at line 1430 of file uip.h.
Referenced by ra_input(), uip_icmp6_error_output(), uip_icmp6_send(), uip_nd6_rs_output(), uip_process(), and uip_reass_over().
Typedef Documentation
typedef struct uip_ds6_addr uip_ds6_addr_t
Unicast address structure.
typedef struct uip_nd6_na uip_nd6_na
A neighbor advertisement constant part.
Possible option is: TLLAO
typedef struct uip_nd6_ns uip_nd6_ns
A neighbor solicitation constant part.
Possible option is: SLLAO
typedef struct uip_nd6_ra uip_nd6_ra
A router advertisement constant part.
Possible options are: SLLAO, MTU, Prefix Information
typedef struct uip_nd6_redirect uip_nd6_redirect
A redirect message constant part.
Possible options are: TLLAO, redirected header
typedef struct uip_nd6_rs uip_nd6_rs
A router solicitation constant part.
Possible option is: SLLAO
Function Documentation
rpl_dag_t* rpl_get_any_dag (void)
Returns pointer to any DAG (for compatibility with legagy RPL code)
Returns
A pointer to the only supported DAG
Definition at line 1036 of file rpl-dag.c.
Referenced by rpl_dag_root_init_dag_immediately().
rpl_instance_t* rpl_get_default_instance (void)
Returns pointer to the default instance (for compatibility with legagy RPL code)
Returns
A pointer to the only supported instance
Definition at line 619 of file rpl-dag.c.
Referenced by rpl_dag_root_is_root().
enum rpl_mode rpl_get_mode (void)
Get the RPL mode.
Return values
The RPL mode
Definition at line 66 of file rpl.c.
int rpl_has_downward_route (void)
Get the RPL's best guess on if we have downward route or not.
Return values
1 if we have a downward route from RPL Root, 0 if not.
Definition at line 1005 of file rpl-dag.c.
void rpl_link_callback (const linkaddr_t * addr, int status, int numtx)
Called by lower layers after every packet transmission.
Parameters
addr The link-layer addrress of the packet destination
status The transmission status (see os/net/mac/mac.h)
numtx The total number of transmission attempts
Definition at line 253 of file rpl.c.
Referenced by packet_sent().
void rpl_process_dio (uip_ipaddr_t * from, rpl_dio_t * dio)
Processes incoming DIO.
Parameters
from The IPv6 address of the originator
dio A pointer to a parsed DIO
Definition at line 1437 of file rpl-dag.c.
enum rpl_mode rpl_set_mode (enum rpl_mode mode)
Set the RPL mode.
Parameters
mode The new RPL mode
Return values
The previous RPL mode
Definition at line 72 of file rpl.c.
void uip_add32 (uint8_t * op32, uint16_t op16)
Carry out a 32-bit addition.
Because not all architectures for which uIP is intended has native 32-bit arithmetic, uIP uses an external C function for doing the required 32-bit additions in the TCP protocol processing. This function should add the two arguments and place the result in the global variable uip_acc32.
Note
The 32-bit integer pointed to by the op32 parameter and the result in the uip_acc32 variable are in network byte order (big endian).
Parameters
op32 A pointer to a 4-byte array representing a 32-bit integer in network byte order (big endian).
op16 A 16-bit integer in host byte order.
Definition at line 279 of file uip6.c.
References uip_acc32.
Referenced by uip_process().
uint16_t uip_chksum (uint16_t * data, uint16_t len)
Calculate the Internet checksum over a buffer.
The Internet checksum is the one's complement of the one's complement sum of all 16-bit words in the buffer.
See RFC1071.
Parameters
data A pointer to the buffer over which the checksum is to be computed.
len The length of the buffer over which the checksum is to be computed.
Returns
The Internet checksum of the buffer.
Definition at line 340 of file uip6.c.
References uip_htons().
uip_ds6_nbr_t* uip_ds6_get_least_lifetime_neighbor (void)
This searches inside the neighbor table for the neighbor that is about to expire the next.
Returns
A reference to the neighbor about to expire the next or NULL if table is empty.
uint16_t uip_htons (uint16_t val)
Convert a 16-bit quantity from host byte order to network byte order.
This function is primarily used for converting variables from host byte order to network byte order. For converting constants to network byte order, use the UIP_HTONS() macro instead.
Definition at line 2307 of file uip6.c.
References UIP_HTONS.
Referenced by newdata(), uip_chksum(), uip_ipchksum(), and uip_udp_new().
void uip_icmp6_echo_reply_callback_add (struct uip_icmp6_echo_reply_notification * n, uip_icmp6_echo_reply_callback_t c)
Add a callback function for ping replies.
Parameters
n A struct uip_icmp6_echo_reply_notification that must have been allocated by the caller
c A pointer to the callback function to be called
        This function adds a callback function to the list of
        callback functions that are called when an ICMP echo
        reply (ping reply) is received. This is used when
        implementing a ping protocol: attach a callback
        function to the ping reply, then send out a ping packet
        with uip_icmp6_send().
        The caller must have statically allocated a struct
        uip_icmp6_echo_reply_notification to hold the internal
        state of the callback function.
        When a ping reply packet is received, all registered
        callback functions are called. The callback functions
        must not modify the contents of the uIP buffer.
Definition at line 352 of file uip-icmp6.c.
References list_add().
Referenced by shell_commands_init().
void uip_icmp6_echo_reply_callback_rm (struct uip_icmp6_echo_reply_notification * n)
Remove a callback function for ping replies.
Parameters
n A struct uip_icmp6_echo_reply_notification that must have been previously added with uip_icmp6_echo_reply_callback_add()
        This function removes a callback function from the list of
        callback functions that are called when an ICMP echo
        reply (ping reply) is received.
Definition at line 362 of file uip-icmp6.c.
References list_remove().
void uip_icmp6_error_output (uint8_t type, uint8_t code, uint32_t param)
Send an icmpv6 error message.
Parameters
type type of the error message
code of the error message
param 32 bit parameter of the error message, semantic depends on error
Definition at line 182 of file uip-icmp6.c.
References ICMP6_PARAM_PROB, ICMP6_PARAMPROB_OPTION, rpl_ext_header_remove(), tmp_ipaddr, uip_ds6_if, uip_ds6_select_src(), uip_ext_len, UIP_ICMP6_ERROR_LEN, uip_icmp6chksum(), UIP_ICMP_BUF, UIP_IP_BUF, uip_ipaddr_copy, uip_is_addr_mcast, uip_is_addr_unspecified, uip_len, UIP_LINK_MTU, and UIP_STAT.
Referenced by ext_hdr_options_process(), uip_process(), and uip_reass_over().
uint8_t uip_icmp6_input (uint8_t type, uint8_t icode)
Handle an incoming ICMPv6 message.
Parameters
type The ICMPv6 message type
icode The ICMPv6 message code
Returns
Success: UIP_ICMP6_INPUT_SUCCESS, Error: UIP_ICMP6_INPUT_ERROR
Generic handler for unknown ICMPv6 types. It will lookup for a registered function capable of handing this message type. The function must have first been registered with uip_icmp6_register_input_handler. The function is in charge of setting uip_len to 0, otherwise the uIPv6 core will attempt to send whatever remains in the UIP_IP_BUF.
A return value of UIP_ICMP6_INPUT_ERROR means that a handler could not be invoked. This is most likely because the ICMPv6 type does not have a valid handler associated with it.
UIP_ICMP6_INPUT_SUCCESS signifies that a handler was found for this ICMPv6 type and that it was invoked. It does NOT provide any indication whatsoever regarding whether the handler itself succeeded.
Definition at line 97 of file uip-icmp6.c.
Referenced by uip_process().
void uip_icmp6_register_input_handler (uip_icmp6_input_handler_t * handler)
Register a handler which can handle a specific ICMPv6 message type.
Parameters
handler A pointer to the handler
Definition at line 114 of file uip-icmp6.c.
References list_add().
Referenced by rpl_icmp6_init(), uip_icmp6_init(), and uip_nd6_init().
void uip_icmp6_send (const uip_ipaddr_t * dest, int type, int code, int payload_len)
Send an icmpv6 message.
Parameters
dest destination address of the message
type type of the message
code of the message
payload_len length of the payload
Definition at line 269 of file uip-icmp6.c.
References tcpip_ipv6_output(), uip_ds6_if, uip_ds6_select_src(), uip_icmp6chksum(), UIP_ICMP_BUF, UIP_IP_BUF, uip_len, and UIP_STAT.
Referenced by rpl_icmp6_dao_output(), rpl_icmp6_dio_output(), and rpl_icmp6_dis_output().
uint16_t uip_icmp6chksum (void)
Calculate the ICMP checksum of the packet in uip_buf.
Returns
The ICMP checksum of the ICMP packet in uip_buf
Definition at line 391 of file uip6.c.
Referenced by uip_icmp6_error_output(), uip_icmp6_send(), uip_nd6_rs_output(), and uip_process().
void uip_init (void)
uIP initialization function.
This function should be called at boot up to initilize the uIP TCP/IP stack.
Definition at line 415 of file uip6.c.
References uip_mcast6_driver::init, uip_udp_conn::lport, uip_conn::tcpstateflags, uip_ds6_init(), uip_icmp6_init(), UIP_LISTENPORTS, uip_nd6_init(), UIP_TCP_CONNS, and UIP_UDP_CONNS.
uint16_t uip_ipchksum (void)
Calculate the IP header checksum of the packet header in uip_buf.
The IP header checksum is the Internet checksum of the 20 bytes of the IP header.
Returns
The IP header checksum of the IP header in the uip_buf buffer.
Definition at line 347 of file uip6.c.
References uip_buf, uip_htons(), and UIP_LLH_LEN.
void uip_listen (uint16_t port)
Start listening to the specified port.
Note
Since this function expects the port number in network byte order, a conversion using UIP_HTONS() or uip_htons() is necessary.
uip_listen(UIP_HTONS(80));
Parameters
port A 16-bit port number in network byte order.
Definition at line 603 of file uip6.c.
References UIP_LISTENPORTS.
Referenced by tcp_listen().
uip_ipaddr_t * uip_nameserver_get (uint8_t num)
Get a Nameserver ip address given in RA.
Parameters
num The number of the nameserver to obtain, starting at 0 and going up to the pool size.
Definition at line 164 of file uip-nameserver.c.
References list_head(), and list_item_next().
uint32_t uip_nameserver_next_expiration (void)
Get next expiration time.
The least expiration time is returned
Definition at line 191 of file uip-nameserver.c.
References DNS_EXPIRATION, list_head(), list_item_next(), list_length(), and UIP_NAMESERVER_INFINITE_LIFETIME.
void uip_nameserver_update (const uip_ipaddr_t * nameserver, uint32_t lifetime)
Initialize the module variables.
Insert or update a nameserver into/from the pool.
The list is kept according to the RFC6106, which indicates that new entries will replace old ones (with lower lifetime) and existing entries will update their lifetimes.
Parameters
nameserver Pointer to the nameserver ip address
lifetime Life time of the given address. Minimum is 0, which is considered to remove an entry. Maximum is 0xFFFFFFFF which is considered infinite.
Definition at line 95 of file uip-nameserver.c.
References clock_seconds(), DNS_EXPIRATION, init(), list_add(), list_head(), list_item_next(), list_remove(), memb_alloc(), memb_free(), and uip_ipaddr_copy.
Referenced by ra_input().
void uip_nd6_ns_output (uip_ipaddr_t * src, uip_ipaddr_t * dest, uip_ipaddr_t * tgt)
Send a neighbor solicitation, send a Neighbor Advertisement.
Parameters
src pointer to the src of the NS if known
dest pointer to ip address to send the NS, for DAD or ADDR Resol, MUST be NULL, for NUD, must be correct unicast dest
tgt pointer to ip address to fill the target address field, must not be NULL
RFC 4861, 7.2.2 : "If the source address of the packet prompting the solicitation is the same as one of the addresses assigned to the outgoing interface, that address SHOULD be placed in the IP Source Address of the outgoing solicitation. Otherwise, any one of the addresses assigned to the interface should be used." This is why we have a src ip address as argument. If NULL, we will do src address selection, otherwise we use the argument.
we check if it is a NS for Address resolution or NUD, if yes we include a SLLAO option, otherwise no.
Referenced by uip_ds6_dad().
void uip_nd6_rs_output (void)
Send a Router Solicitation.
src is chosen through the uip_netif_select_src function. If src is unspecified (i.e. we do not have a preferred address yet), then we do not put a SLLAO option (MUST NOT in RFC 4861). Otherwise we do.
RS message format, possible option is SLLAO, MUST NOT be included if source = unspecified SHOULD be included otherwise
Send a Router Solicitation.
The NS can be received in 3 cases (procedures):
sender is performing DAD (ip src = unspecified, no SLLAO option)
sender is performing NUD (ip dst = unicast)
sender is performing address resolution (ip dest = solicited node mcast address)
We do:
if the tgt belongs to me, reply, otherwise ignore
if i was performing DAD for the same address, two cases: – I already sent a NS, hence I win – I did not send a NS yet, hence I lose
If we need to send a NA in response (i.e. the NS was done for NUD, or address resolution, or DAD and there is a conflict), we do it in this function: set src, dst, tgt address in the three cases, then for all cases set the rest, including SLLAO
Definition at line 815 of file uip-nd6.c.
References ICMP6_RS, uip_buf, uip_create_linklocal_allrouters_mcast, uip_ds6_select_src(), uip_icmp6chksum(), UIP_ICMP_BUF, UIP_IP_BUF, uip_is_addr_unspecified, uip_len, UIP_ND6_HOP_LIMIT, UIP_ND6_OPT_LLAO_LEN, and UIP_STAT.
Referenced by uip_ds6_send_rs().
void uip_process (uint8_t flag)
process the options within a hop by hop or destination option header
Return values
0 nothing to send,
1 drop pkt
2 ICMP error message to send
Definition at line 928 of file uip6.c.
References ext_hdr_options_process(), ICMP6_DST_UNREACH, ICMP6_DST_UNREACH_NOPORT, ICMP6_DST_UNREACH_NOTNEIGHBOR, ICMP6_PACKET_TOO_BIG, ICMP6_PARAM_PROB, ICMP6_PARAMPROB_HEADER, ICMP6_PARAMPROB_NEXTHEADER, ICMP6_TIME_EXCEED_TRANSIT, ICMP6_TIME_EXCEEDED, uip_mcast6_driver::in, uip_conn::initialmss, uip_conn::len, uip_conn::lport, uip_udp_conn::lport, uip_conn::mss, uip_conn::nrtx, uip_conn::rcv_nxt, uip_conn::ripaddr, uip_udp_conn::ripaddr, rpl_ext_header_srh_update(), uip_conn::rport, uip_udp_conn::rport, uip_conn::rto, uip_conn::sa, uip_conn::snd_nxt, uip_conn::sv, uip_conn::tcpstateflags, uip_conn::timer, uip_udp_conn::ttl, uip_acc32, uip_add32(), UIP_APPCALL, uip_appdata, uip_buf, uip_conn, uip_ds6_if, uip_ds6_select_src(), uip_ext_bitmap, UIP_EXT_HDR_BITMAP_HBHO, uip_ext_len, UIP_HTONS, uip_icmp6_error_output(), uip_icmp6_input(), uip_icmp6chksum(), UIP_ICMP_BUF, UIP_IP_BUF, uip_ipaddr_copy, uip_is_addr_linklocal, uip_is_addr_loopback, uip_is_addr_mcast, uip_is_addr_mcast_routable, uip_is_addr_unspecified, uip_len, UIP_LINK_MTU, UIP_LISTENPORTS, UIP_LLH_LEN, UIP_MAXRTX, UIP_MAXSYNRTX, uip_next_hdr, UIP_PROTO_HBHO, UIP_RECEIVE_WINDOW, UIP_RTO, UIP_STAT, UIP_TCP_CONNS, UIP_TCP_MSS, uip_tcpchksum(), UIP_TIME_WAIT_TIMEOUT, uip_udp_conn, UIP_UDP_CONNS, and uip_udpchksum().
void uip_reass_over (void)
Abandon the reassembly of the current packet.
Note
We don't have a complete packet to put in the error message. We could include the first fragment but since its not mandated by any RFC, we decided not to include it as it reduces the size of the packet.
Definition at line 799 of file uip6.c.
References etimer_stop(), ICMP6_TIME_EXCEED_REASSEMBLY, ICMP6_TIME_EXCEEDED, uip_icmp6_error_output(), UIP_IP_BUF, uip_reass_timer, and UIP_STAT.
void uip_send (const void * data, int len)
Send data on the current connection.
This function is used to send out a single segment of TCP data. Only applications that have been invoked by uIP for event processing can send data.
The amount of data that actually is sent out after a call to this function is determined by the maximum amount of data TCP allows. uIP will automatically crop the data so that only the appropriate amount of data is sent. The function uip_mss() can be used to query uIP for the amount of data that actually will be sent.
Note
This function does not guarantee that the sent data will arrive at the destination. If the data is lost in the network, the application will be invoked with the uip_rexmit() event being set. The application will then have to resend the data using this function.
Parameters
data A pointer to the data which is to be sent.
len The maximum amount of data bytes to be sent.
Definition at line 2319 of file uip6.c.
References uip_buf, UIP_BUFSIZE, and UIP_LLH_LEN.
uint16_t uip_tcpchksum (void)
Calculate the TCP checksum of the packet in uip_buf and uip_appdata.
The TCP checksum is the Internet checksum of data contents of the TCP segment, and a pseudo-header as defined in RFC793.
Returns
The TCP checksum of the TCP segment in uip_buf and pointed to by uip_appdata.
Definition at line 399 of file uip6.c.
Referenced by uip_process().
struct uip_udp_conn* uip_udp_new (const uip_ipaddr_t * ripaddr, uint16_t rport)
Set up a new UDP connection.
This function sets up a new UDP connection. The function will automatically allocate an unused local port for the new connection. However, another port can be chosen by using the uip_udp_bind() call, after the uip_udp_new() function has been called.
Example:
uip_ipaddr_t addr;
struct uip_udp_conn *c;
uip_ipaddr(&addr, 192,168,2,1);
c = uip_udp_new(&addr, UIP_HTONS(12345));
if(c != NULL) {
uip_udp_bind(c, UIP_HTONS(12344));
}
Parameters
ripaddr The IP address of the remote host.
rport The remote port number in network byte order.
Returns
The uip_udp_conn structure for the new connection, or NULL if no connection could be allocated.
Definition at line 545 of file uip6.c.
References uip_udp_conn::lport, uip_udp_conn::ripaddr, uip_udp_conn::rport, uip_udp_conn::ttl, uip_ds6_if, UIP_HTONS, uip_htons(), uip_ipaddr_copy, and UIP_UDP_CONNS.
Referenced by udp_new().
uint16_t uip_udpchksum (void)
Calculate the UDP checksum of the packet in uip_buf and uip_appdata.
The UDP checksum is the Internet checksum of data contents of the UDP segment, and a pseudo-header as defined in RFC768.
Returns
The UDP checksum of the UDP segment in uip_buf and pointed to by uip_appdata.
Referenced by uip_process().
void uip_unlisten (uint16_t port)
Stop listening to the specified port.
Note
Since this function expects the port number in network byte order, a conversion using UIP_HTONS() or uip_htons() is necessary.
uip_unlisten(UIP_HTONS(80));
Parameters
port A 16-bit port number in network byte order.
Definition at line 591 of file uip6.c.
References UIP_LISTENPORTS.
Referenced by tcp_unlisten().
Variable Documentation
void* uip_appdata
Pointer to the application data in the packet buffer.
This pointer points to the application data when the application is called. If the application wishes to send data, the application may use this space to write the data into before calling uip_send().
Definition at line 175 of file uip6.c.
Referenced by coap_separate_accept(), newdata(), and uip_process().
CCIF void* uip_appdata
Pointer to the application data in the packet buffer.
This pointer points to the application data when the application is called. If the application wishes to send data, the application may use this space to write the data into before calling uip_send().
Definition at line 175 of file uip6.c.
Referenced by coap_separate_accept(), newdata(), and uip_process().
struct uip_conn* uip_conn
Pointer to the current TCP connection.
The uip_conn pointer can be used to access the current TCP connection.
Definition at line 201 of file uip6.c.
Referenced by uip_process().
CCIF struct uip_conn* uip_conn
Pointer to the current TCP connection.
The uip_conn pointer can be used to access the current TCP connection.
Definition at line 201 of file uip6.c.
Referenced by uip_process().
uint8_t uip_ext_len = 0
length of the extension headers read.
The length of the extension headers.
updated each time we process a header
Definition at line 136 of file uip6.c.
Referenced by ext_hdr_options_process(), rpl_ext_header_remove(), rpl_ext_header_srh_get_next_hop(), rpl_ext_header_srh_update(), uip_icmp6_error_output(), and uip_process().
uint16_t uip_len
The length of the packet in the uip_buf buffer.
The global variable uip_len holds the length of the packet in the uip_buf buffer.
When the network device driver calls the uIP input function, uip_len should be set to the length of the packet in the uip_buf buffer.
When sending packets, the device driver should use the contents of the uip_len variable to determine the length of the outgoing packet.
Definition at line 186 of file uip6.c.
Referenced by accept(), input(), output(), ra_input(), rpl_ext_header_remove(), slip_send(), tcpip_ipv6_output(), uip_ds6_periodic(), uip_icmp6_error_output(), uip_icmp6_send(), uip_nd6_rs_output(), and uip_process().
uint8_t* uip_next_hdr
Type of the next header in IPv6 header or extension headers.
Can be the next header field in the IPv6 header or in an extension header. When doing fragment reassembly, we must change the value of the next header field in the header before the fragmentation header, hence we need a pointer to this field.
Definition at line 129 of file uip6.c.
Referenced by rpl_ext_header_remove(), rpl_ext_header_srh_get_next_hop(), rpl_ext_header_srh_update(), and uip_process().