Contiki-NG: nrf52832 SoC
nrf52832 SoC
CPUs and Device driver
Modules
Bluetooth Low Energy drivers
Device drivers
Files
file putchar.c
Hardware specific implementation of putchar() and puts() functions.
file rtimer-arch.c
Implementation of the architecture dependent rtimer functions for the nRF52.
file rtimer-arch.h
Architecture dependent rtimer implementation header file.
Functions
static void timer_event_handler (nrf_timer_event_t event_type, void *p_context)
Handler for timer events.
void rtimer_arch_init (void)
Initialize platform rtimer.
void rtimer_arch_schedule (rtimer_clock_t t)
Schedules an rtimer task to be triggered at time t.
rtimer_clock_t rtimer_arch_now ()
Returns the current real-time clock time.
Variables
static const nrf_drv_timer_t timer = NRF_DRV_TIMER_INSTANCE(PLATFORM_TIMER_INSTANCE_ID)
Timer instance used for rtimer.
Detailed Description
Function Documentation
void rtimer_arch_init (void)
Initialize platform rtimer.
We don't need to explicitly initialise anything but this routine is required by the API.
Definition at line 75 of file rtimer-arch.c.
References timer_event_handler().
rtimer_clock_t rtimer_arch_now ()
Returns the current real-time clock time.
Returns
The current rtimer time in ticks
Definition at line 103 of file rtimer-arch.c.
void rtimer_arch_schedule (rtimer_clock_t t)
Schedules an rtimer task to be triggered at time t.
Parameters
t The time when the task will need executed.
t is an absolute time, in other words the task will be executed AT time t, not IN t rtimer ticks.
This function schedules a one-shot event with the nRF RTC.
Definition at line 92 of file rtimer-arch.c.
static void timer_event_handler (nrf_timer_event_t event_type, void * p_context) static
Handler for timer events.
Parameters
event_type type of an event that should be handled
p_context opaque data pointer passed from nrf_drv_timer_init()
Definition at line 58 of file rtimer-arch.c.
References rtimer_run_next().
Referenced by rtimer_arch_init().