Contiki-NG: cc2538 watchdog timer driver
cc2538 watchdog timer driver
The TI cc2538 System-on-Chip
Driver for the cc2538 Watchdog Timer.
Files
file watchdog.c
Implementation of the cc2538 watchdog driver.
Functions
void watchdog_init (void)
Initialisation function for the WDT.
void watchdog_start (void)
Starts the WDT in watchdog mode if enabled by user configuration, maximum interval.
void watchdog_periodic (void)
Writes the WDT clear sequence.
void watchdog_reboot (void)
Keeps control until the WDT throws a reset signal.
Detailed Description
Driver for the cc2538 Watchdog Timer.
Function Documentation
void watchdog_init (void)
Initialisation function for the WDT.
Currently simply explicitly sets the WDT interval to max interval
Definition at line 63 of file watchdog.c.
void watchdog_periodic (void)
Writes the WDT clear sequence.
Due to how the SMWDTHROSC_WDCTL works, it is OK to simply write these bits rather than use RMW operations.
Definition at line 85 of file watchdog.c.
Referenced by cfs_coffee_arch_erase(), cfs_coffee_arch_read(), cfs_coffee_arch_write(), clock_delay(), clock_wait(), lpm_shutdown(), platform_idle(), platform_main_loop(), and send_packet().
void watchdog_reboot (void)
Keeps control until the WDT throws a reset signal.
Starts the WDT if not already started.
Definition at line 94 of file watchdog.c.