Contiki-NG: os/net/mac/mac-sequence.c File Reference
mac-sequence.c File Reference
    MAC sequence numbers management
#include <string.h>
#include "contiki-net.h"
#include "net/mac/mac-sequence.h"
#include "net/packetbuf.h"
Functions
int mac_sequence_is_duplicate (void)
Tell whether the packetbuf is a duplicate packet.
void mac_sequence_register_seqno (void)
Register the sequence number of the packetbuf.
Detailed Description
    MAC sequence numbers management
Author
Adam Dunkels adam@.nosp@m.sics.nosp@m..se Benoît Thébaudeau benoi.nosp@m.t.th.nosp@m.ebaud.nosp@m.eau@.nosp@m.advan.nosp@m.see..nosp@m.com
Definition in file mac-sequence.c.
Function Documentation
int mac_sequence_is_duplicate (void)
Tell whether the packetbuf is a duplicate packet.
Returns
Non-zero if the packetbuf is a duplicate packet, zero otherwise
        This function is used to check for duplicate packet by comparing
        the sequence number of the incoming packet with the last few ones
        we saw, filtering with the link-layer address.
Definition at line 72 of file mac-sequence.c.
References clock_time(), and linkaddr_cmp().
void mac_sequence_register_seqno (void)
Register the sequence number of the packetbuf.
This function is used to add the sequence number of the incoming packet to the history.
Definition at line 101 of file mac-sequence.c.
References clock_time(), linkaddr_cmp(), and linkaddr_copy().