Contiki-NG: mac_driver Struct Reference
mac_driver Struct Reference
The structure of a MAC protocol driver in Contiki.
#include <os/net/mac/mac.h>
Data Fields
void(* init)(void)
Initialize the MAC driver.
void(* send)(mac_callback_t sent_callback, void *ptr)
Send a packet from the packetbuf.
void(* input)(void)
Callback for getting notified of incoming packet.
int(* on)(void)
Turn the MAC layer on.
int(* off)(void)
Turn the MAC layer off.
Detailed Description
The structure of a MAC protocol driver in Contiki.
Definition at line 54 of file mac.h.
Field Documentation
void(* mac_driver::input) (void)
Callback for getting notified of incoming packet.
Definition at line 64 of file mac.h.
Referenced by cc2420_interrupt(), PROCESS_THREAD(), and rf_core_primary_mode_restore().
int(* mac_driver::off) (void)
Turn the MAC layer off.
Definition at line 70 of file mac.h.
int(* mac_driver::on) (void)
Turn the MAC layer on.
Definition at line 67 of file mac.h.
Referenced by tsch_disassociate().